DataHandler Class Reference
The OWL Data object.
Public Member Functions
__construct ($tablename= '')
reset ($level=DATA_RESET_PREPARE)
getDbLink ()
set ($variable, $value, $table=null, array $fieldFunction=null, array $valueFunction=null)
setKey ($variable)
escapeString ($string)
get ($variable)
setJoin ($lvalue, $rvalue, $linktype= '=')
setTablename ($tblname)
prepare ($type=DATA_READ)
db (&$data=null, $line=0, $file= '[unknown]')
setPrefix ($prefix)
dbStatus ()
insertedId ()
getLastWarning ()
getStatus ()
getSeverity ($status=null)
succeeded ($_ok=OWL_SUCCESS, &$_object=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Protected Member Functions
init ()
setCallback ($_dispatcher)
setCallbackArgument (array $_arg)
getCallback ()
reset ()
saveStatus ()
restoreStatus ()
check (&$object, $level=OWL_WARNING)
setStatus ($status, $params=array())
setHighSeverity (&$object=null)
Protected Attributes
$owl_tablename
$owl_database
$severity
Private Member Functions
findField ($fld, &$expanded)
Private Attributes
$owl_data
$owl_joins
$owl_keys
$owl_prepared
$last_id
Detailed Description
The OWL Data object.
This class contains DB datasets
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Aug 4, 2008 -- O van Eijk -- initial version
Examples:
exa.datahandler-set.php.
Constructor & Destructor Documentation
DataHandler::__construct ($ tablename = '')
Class constructor.
Parameters
in $tablename Default table name for this dataset
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in HDataHandler .
References OWL::factory(), _OWL::init(), and _OWL::setStatus().
Member Function Documentation
_OWL::check (&$ object, $ level = OWL_WARNING) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
in $object Pointer to an object to check against
in $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::reset(), _OWL::setHighSeverity(), and _OWL::traceback().
Referenced by SessionHandler::write().
DataHandler::db (&$ data = null, $ line = 0, $ file = '[unknown]')
Forward a call to the DBHandler object (which is private in this DataHandler)
Parameters
out $data The result of DBHandler function, or false when no query was prepared yet
in $line Line number of this call
in $file File that made the call to this method
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setHighSeverity().
DataHandler::dbStatus ()
Return the last status of the database
Returns
Current status of the database object
Author
Oscar van Eijk, Oveas Functionality Provider
DataHandler::escapeString ($ string)
Interface to the DbHander::escapeString()
Parameters
in $string String to escape
Returns
Return value of DbHandler::escapeString()
Author
Oscar van Eijk, Oveas Functionality Provider
DataHandler::findField ($ fld, &$ expanded) [private]
Try to exand a field to a fully qualified 'table#field' name
Parameters
in $fld The fieldname that has to be expanded
out $expanded An array with all matching fully qualified fieldnames.
Returns
The number of matches
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by get().
DataHandler::get ($ variable)
Retrieve a value from the data array. The variable name can be a fully qualified table/fieldname (format `table#field`), or only a field name, in which case it has to be unique. If the fieldname cannot be found directly, the array is scanned to find a matching field. If more matches are found, the object status is set to DATA_AMBFIELD.
Note
The data array contains arrays where the first element is the matchtype (=, <, <= etc) and the second element is the actual value!
Parameters
in $variable The name of the variable that should be retrieved
Returns
The value, or NULL when the value was not found or abigious.
Author
Oscar van Eijk, Oveas Functionality Provider
References findField(), and _OWL::setStatus().
_OWL::getCallback () [protected, inherited]
Retrieve a previously set (callback) dispatcher. The (callback) dispatcher is cleared immediatly.
Returns
The dispatcher, of null on failure.
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in Dispatcher .
References OWL::factory().
DataHandler::getDbLink ()
Get the link to the actual database object of the dataset, which might be the original singleton, or the clone in use.
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::getLastWarning () [inherited]
Get the last warning or error message.
Returns
null if there was no error (severity below OWL_WARNING), otherwise the error text.
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
_OWL::getSeverity ($ status = null) [inherited]
Get the current object severity level.
Parameters
in $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::$status.
Referenced by LogHandler::composeMessage(), LogHandler::log(), and setKey().
_OWL::getStatus () [final, inherited]
Get the current object status.
Returns
Object's status code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by SchemeHandler::compare().
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory(), and _OWL::setStatus().
Referenced by FormFieldPlugin::__construct(), Tablerow::__construct(), Tablecell::__construct(), Table::__construct(), Document::__construct(), ContainerPlugin::__construct(), Container::__construct(), SocketHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), HDataHandler::__construct(), __construct(), OWL::__construct(), Mail::__construct(), Group::__construct(), Form::__construct(), Dispatcher::__construct(), and User::construct().
DataHandler::insertedId ()
Return the last inserted AutoIncrement value
Returns
Last ID
Author
Oscar van Eijk, Oveas Functionality Provider
DataHandler::prepare ($ type = DATA_READ)
Prepare a database query
Parameters
in $type Specify which type of query should be prepared:
DATA_READ (default); Read data from the database
DATA_WRITE; Write new data to the database
DATA_UPDATE; Update data in the database
Returns
Severity level
Todo add limit and cache
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setHighSeverity(), and _OWL::setStatus().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in DbHandler , and SchemeHandler .
References _OWL::resetCalltree().
Referenced by _OWL::check(), SessionHandler::read(), reset(), and _OWL::setStatus().
DataHandler::reset ($ level = DATA_RESET_PREPARE)
Reset the object
Parameters
in $level Bitmap indicating which items must be reset. Default is DATA_RESET_PREPARE
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::reset().
_OWL::restoreStatus () [protected, inherited]
Restore the previously saved status object and destroy the copy
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by User::logout().
_OWL::saveStatus () [protected, inherited]
Create a copy of the status object
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::logout().
DataHandler::set ($ variable, $ value, $ table = null, array $ fieldFunction = null, array $ valueFunction = null)
Define or override a variable in the data array
Parameters
in $variable The name of the variable that should be set.
in $value Value to set the variable to. For read operations, this can be a value, in which case the fieldname be will looked for matching all given values. Values with unescaped percent signs will be searched using the SQL LIKE keyword. If the matchtype is DBMATCH_NONE, the value is ignored.
in $table An optional tablename for this field. Defaults to $this->owl_tablename
in $fieldFunction An optional array with SQL functions and statements that apply to the fieldname. This is an indexed array, where all keys must have an array as value. The following keys are supported:
function: An array where the first element is an SQL function, which must exist in the database driver as 'functionFunction' (e.g., for 'function'=> array(`ifnull`, `default`), the method `functionIfnull()` must exist). The first argument passed to the method is always the fieldname, additional arguments will be taken from the array.
groupby: Add the fieldname to a groupby list. The value for this key must be an empty array
orderby: Add the fieldname to the orderby list. The given array can contain 1 element; `ASC` or `DESC`. When empty, it defaults to the SQL default (ASC)
having: Add the fieldname to to the having clause. The array must contain 2 elements, where the first element is the matchtype and the second argument is the value to match
name: The DataHandler returns data as indexed arrays on read operations, where the index equals the fieldname. This might contain complete SQL code when functions are called; this can be overwritten by specifying a name for the field
in $valueFunction An optional array with SQL functions and statements that apply to the value. This is an indexed array, where all keys must have an array as value. The following keys are supported:
function: An array where the first element is an SQL function, which must exist in the database driver as 'functionFunction' (e.g., for 'function'=> array(`ifnull`, `default`), the method `functionIfnull()` must exist). The first argument passed to the method is always the fieldname, additional arguments will be taken from the array.
match: The matchtype. When omitted, default is DBMATCH_EQ ('='). If the field should be in a SELECT list and not in the where clause, use the matchtype DBMATCH_NONE (if no fields are set with DBMATCH_NONE, read queries will select with SELECT *)
See also
exa.datahandler-set.php
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by setPrefix().
_OWL::setCallback ($ _dispatcher) [protected, inherited]
Set a dispatcher for later callback
Parameters
in $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher()
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
_OWL::setCallbackArgument (array $ _arg) [protected, inherited]
Add an argument to a previously registered callback dispatcher
Parameters
in $_arg Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
Referenced by User::register().
_OWL::setHighSeverity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by _OWL::check(), db(), prepare(), and SessionHandler::read().
DataHandler::setJoin ($ lvalue, $ rvalue, $ linktype = '=')
Define a link between 2 fields that will be recognized when the database query is built.
Parameters
in $lvalue Left value as array(table, field)
in $rvalue Right value as array(table, field)
in $linktype How are the fields linked. Can be any binary operator as recognized by SQL.
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
DataHandler::setKey ($ variable)
Lock variables for update by adding them to an array. Fields in this array will not be overwritten on updates, but used in WHERE clauses.
Parameters
in $variable Variable name to lock, optionally as an array (table, field)
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::getSeverity(), and _OWL::setStatus().
DataHandler::setPrefix ($ prefix)
Overwrite the table prefix for this dataset. Since the prefix is stored in the database handler object, a clone is used (or made) here.
Parameters
in $prefix Table prefix
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory(), OWLCache::get(), and set().
_OWL::setStatus ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
in $status OWL status code
in $params
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::getCode(), _OWL::reset(), and _OWL::signal().
Referenced by DbHandler::__clone(), Container::__construct(), SocketHandler::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), __construct(), Session::__construct(), Mail::__construct(), BaseElement::_getContent(), Mail::addBcc(), Mail::addCc(), Form::addField(), FormFieldRadioPlugin::addOption(), Mail::addTo(), BaseElement::addToContent(), DbHandler::alt(), SchemeHandler::alterScheme(), FileHandler::close(), DbHandler::commitTransaction(), Dispatcher::composeDispatcher(), User::confirm(), SocketHandler::connect(), DbHandler::connect(), DbHandler::create(), SchemeHandler::createScheme(), SchemeHandler::defineIndex(), SchemeHandler::defineScheme(), SocketHandler::disconnect(), Dispatcher::dispatch(), FormHandler::get(), get(), SchemeHandler::getTableColumns(), SchemeHandler::getTableIndexes(), _OWL::init(), Document::loadScript(), Document::loadStyle(), DbHandler::lockTable(), User::login(), FileHandler::open(), DbHandler::open(), LogHandler::openLogfile(), prepare(), DbHandler::prepareDelete(), DbHandler::prepareField(), DbHandler::prepareInsert(), DbHandler::prepareRead(), DbHandler::prepareUpdate(), SocketHandler::read(), DbHandler::read(), FileHandler::readLine(), HDataHandler::readQuery(), User::readUserdata(), User::register(), Dispatcher::registerArgument(), Dispatcher::registerCallback(), _OWL::restoreStatus(), DbHandler::rollbackTransaction(), SchemeHandler::scheme(), Mail::send(), FormHandler::set(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), Document::setFavicon(), Form::setFieldAttributes(), Mail::setFrom(), setJoin(), setKey(), FormFieldTextPlugin::setMaxsize(), Document::setMeta(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), Mail::setSender(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), Form::showField(), DbHandler::startTransaction(), SchemeHandler::tableDescription(), DbHandler::unlockTable(), SchemeHandler::validateScheme(), SocketHandler::write(), and DbHandler::write().
DataHandler::setTablename ($ tblname)
Set or overwrite the default table name
Parameters
in $tblname Default table name
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
in $level An optional severity level; message will only be displayed when it is at least of this level.
out $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
Referenced by _OWL::getLastWarning(), _OWL::setStatus(), and _OWL::traceback().
_OWL::succeeded ($ _ok = OWL_SUCCESS, &$ _object = null) [inherited]
Check if the object currenlty has a success state
Parameters
in $_ok The highest severity that's considered successfull, default OWL_SUCCESS
in $_object REference to the object to check, defaults to the current object
Returns
Boolean true when successfull
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::construct(), Dispatcher::registerArgument(), and Dispatcher::registerCallback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
out $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
in $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
Referenced by _OWL::check(), User::login(), and SessionHandler::read().
Member Data Documentation
DataHandler::$last_id [private]
integer - Last inserted Auto Increment value. Set after all write actions, so can be 0.
DataHandler::$owl_data [private]
Indexed array holding all data values.
DataHandler::$owl_database [protected]
An optional link to a database object. This has to be specified if the data needs to be written to or read from a dabatase.
DataHandler::$owl_joins [private]
2D Array holding all relationships between the data.
DataHandler::$owl_keys [private]
Array with variable names that are used in WHERE clauses on updates
DataHandler::$owl_prepared [private]
Boolean that indicates of a query has been prepared
DataHandler::$owl_tablename [protected]
All variable names are expected to be fields in a database as well. If a table name is not given, the default table name will be used. This is useful for datasets that come from only one database table. For datasets that are not read from or written to a database, the tablename can be null.
_OWL::$severity [protected, inherited]
Severity level of the current object status
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.datahandler.php