UserHandler Class Reference
the user object
Public Member Functions
isLoggedIn ()
__destruct ()
get_status ()
get_severity ($status=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Public Attributes
$user_data
Protected Member Functions
construct ($username)
username_exists ($username)
register ($username, $email, $password, $vpassword)
logout ($reset_status)
login ($username, $password)
set_username ($username)
get_username ()
init ()
reset ()
save_status ()
restore_status ()
check (&$object, $level)
set_status ($status, $params=array())
set_high_severity (&$object=null)
Protected Attributes
$session
$dataset
$severity
Private Member Functions
read_userdata ()
hash_password ($password)
Detailed Description
the user object This class creates user sessions and handles logging in and out
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Aug 27, 2008 -- O van Eijk -- initial version
Constructor & Destructor Documentation
UserHandler::__destruct ()
Class destructor
Reimplemented from _OWL.
Reimplemented in User.
Member Function Documentation
_OWL::check (&$ object, $ level) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
[in] $object Pointer to an object to check against
[in] $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
References _OWL::reset(), _OWL::set_high_severity(), and _OWL::traceback().
Referenced by SessionHandler::write().
UserHandler::construct ($ username) [protected]
Class constructor; setup the user environment
Parameters
[in] $username Username.
Reimplemented in User.
References ConfigHandler::get(), _OWL::init(), read_userdata(), _OWL::set_status(), and set_username().
_OWL::get_severity ($ status = null) [inherited]
Get the current object severity level.
Parameters
[in] $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
References _OWL::$status.
Referenced by LogHandler::compose_message(), LogHandler::log(), and DataHandler::set_key().
_OWL::get_status () [final, inherited]
Get the current object status.
Returns
Object's status code
Referenced by SchemeHandler::compare().
UserHandler::get_username () [protected]
Return the username of the current session
Reimplemented in User.
UserHandler::hash_password ($ password) [private]
Encrypt a given password
Parameters
[in] $password Given password in plain text format
Returns
The encrypted password
References ConfigHandler::get().
Referenced by login(), and register().
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
References OWL::factory().
Referenced by FormFieldPlugin::__construct(), Tablerow::__construct(), Tablecell::__construct(), Table::__construct(), Document::__construct(), ContainerPlugin::__construct(), Container::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), OWL::__construct(), Form::__construct(), Dispatcher::__construct(), and construct().
UserHandler::isLoggedIn ()
References ConfigHandler::get().
UserHandler::login ($ username, $ password) [protected]
Attempt to log in with the current user and the given password
Parameters
[in] $username Given username. Might be taken from the session as well, but given as a parameter here to suppress the E_STRICT Declaration warning
[in] $password The user provided password
Returns
True on success, False otherwise
Reimplemented in User.
References ConfigHandler::get(), hash_password(), _OWL::set_status(), set_username(), and _OWL::traceback().
UserHandler::logout ($ reset_status) [protected]
Log out the current user.
Parameters
[in] $reset_status When true, the object status will be reset
Reimplemented in User.
References _OWL::restore_status(), and _OWL::save_status().
UserHandler::read_userdata () [private]
When a new session starts for a use that was logged in before retrieve the userdata back from the database
References _OWL::set_status().
Referenced by construct().
UserHandler::register ($ username, $ email, $ password, $ vpassword) [protected]
Store a newly registered user
Parameters
[in] $username Given username
[in] $email Given username
[in] $password Given password
[in] $vpassword Given password verification - not used here but must exist in the reimplementation
Returns
New user ID or -1 on failure
Reimplemented in User.
References hash_password(), and RandomString().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Reimplemented in DbHandler, and SchemeHandler.
References _OWL::reset_calltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::set_status().
_OWL::restore_status () [protected, inherited]
Restore the previously saved status object and destroy the copy
References _OWL::set_status().
Referenced by logout().
_OWL::save_status () [protected, inherited]
Create a copy of the status object
Referenced by logout().
_OWL::set_high_severity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
_OWL::set_status ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
[in] $status OWL status code
[in] $params
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::get_code(), _OWL::reset(), and _OWL::signal().
Referenced by DbHandler::__clone(), Container::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), BaseElement::_getContent(), Form::addField(), FormFieldRadioPlugin::addOption(), BaseElement::addToContent(), DbHandler::alt(), SchemeHandler::alter_scheme(), FileHandler::close(), Dispatcher::composeDispatcher(), DbHandler::connect(), construct(), DbHandler::create(), SchemeHandler::create_scheme(), SchemeHandler::define_index(), SchemeHandler::define_scheme(), Dispatcher::dispatch(), FormHandler::get(), DataHandler::get(), SchemeHandler::get_table_columns(), SchemeHandler::get_table_indexes(), Document::loadScript(), Document::loadStyle(), login(), FileHandler::open(), DbHandler::open(), LogHandler::open_logfile(), DataHandler::prepare(), DbHandler::prepare_delete(), DbHandler::prepare_insert(), DbHandler::prepare_read(), DbHandler::prepare_update(), DbHandler::read(), FileHandler::read_line(), read_userdata(), User::register(), _OWL::restore_status(), SchemeHandler::scheme(), FormHandler::set(), DataHandler::set(), DataHandler::set_join(), DataHandler::set_key(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), Document::setFavicon(), Form::setFieldAttributes(), FormFieldTextPlugin::setMaxsize(), Document::setMeta(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), Form::showField(), SchemeHandler::table_description(), SchemeHandler::validate_scheme(), and DbHandler::write().
UserHandler::set_username ($ username) [protected]
Set the username
Parameters
[in] $username Username
Referenced by construct(), login(), User::login(), and User::logout().
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
[in] $level An optional severity level; message will only be displayed when it is at least of this level.
[out] $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
References ConfigHandler::get().
Referenced by _OWL::set_status(), and _OWL::traceback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
[out] $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
[in] $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
References _OWL::signal().
Referenced by _OWL::check(), login(), and SessionHandler::read().
UserHandler::username_exists ($ username) [protected]
Check is a given username exists
Parameters
[in] $username The username to check
Returns
True when the username exists false otherwise
Referenced by User::register().
Member Data Documentation
UserHandler::$dataset [protected]
Link to a datahandler object. This dataset is used as an interface to all database IO.
UserHandler::$session [protected]
The PHP session object
_OWL::$severity [protected, inherited]
Severity level of the current object status
UserHandler::$user_data
An indexed array with the user information as take from the database
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.userhandler.php