OutputHandler Class Reference
Output handler.
Static Public Member Functions
static output ($text, $method=OWL_OUTPUT_RAW, $class=null)
static outputRaw ($text)
static outputAjax ($text)
static outputLine ($text, $class=null)
static outputPar ($text, $class=null)
static outputStarted ()
Static Private Attributes
static $outputStarted = false
Detailed Description
Output handler.
This abstract class contains all methods to send output to different channels. Although the normal echo statement can be used, it is adviseable to use the methods from this class.
Author
Oscar van Eijk, Oveas Functionality Provider
Version
May 30, 2011 -- O van Eijk -- initial version
Member Function Documentation
static OutputHandler::output ($ text, $ method = OWL_OUTPUT_RAW, $ class = null) [static]
Entry method for the output class which calls to correct method for the required output, although these output methods can also be called directly.
Parameters
in $text Text that should be send to the output channel. Can contain HTML
in $method Format method, must be a method as defined in Methods to send output to the output channel. If anything else is given, OWL_OUTPUT_RAW is assumed.
in $class Optional CSS class (ignored for OWL_OUTPUT_RAW and OWL_OUTPUT_AJAX)
Author
Oscar van Eijk, Oveas Functionality Provider
References outputAjax(), outputLine(), outputPar(), and outputRaw().
static OutputHandler::outputAjax ($ text) [static]
Send the output unformatted to output channel for Ajax
Parameters
in $text Text that should be send to the output channel. Can contain HTML
Todo Write this method....
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by output().
static OutputHandler::outputLine ($ text, $ class = null) [static]
Send the output to the standard output channel, formatted with a <span> and terminated with <br/>
Parameters
in $text Text that should be send to the output channel. Can contain HTML
in $class Optional CSS class used for the span tag
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by output(), and _OWL::signal().
static OutputHandler::outputPar ($ text, $ class = null) [static]
Send the output to the standard output channel, formatted with a <div>
Parameters
in $text Text that should be send to the output channel. Can contain HTML
in $class Optional CSS class used for the div tag
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by output(), OWLdbg_show(), and OWLTimers::showTimer().
static OutputHandler::outputRaw ($ text) [static]
Send the output unformatted to the standard output channel
Parameters
in $text Text that should be send to the output channel. Can contain HTML
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by LogHandler::backtrace(), OWLExceptionHandler::logException(), output(), and _OWL::signal().
static OutputHandler::outputStarted () [static]
Check if output has been sent to the browser already
Returns
True if output was sent
Author
Oscar van Eijk, Oveas Functionality Provider
References $outputStarted.
Member Data Documentation
OutputHandler::$outputStarted = false [static, private]
Boolean to keep track if the brow
Referenced by outputStarted().
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.outputhandler.php