Register Class Reference
Static Public Member Functions
static init ()
static registerApp ($name, $id)
static registerClass ($name)
static registerCode ($code)
static registerSeverity ($level, $name)
static getSeverity ($level)
static getSeverityLevel ($name)
static getRunId ()
static getCode ($value, $unknown= '*unknown *')
static setApplication ($app_id)
static setClass ($class_id)
static setSeverity ($severity_level)
static registerMessages ($_force=false)
static registerLabels ($_owl=false)
Detailed Description
OWL keeps track of all running applications, their class and all status codes their instances (objects) can have. This is done in a global Register, which is maintained by this class.
Author
Oscar van Eijk, Oveas Functionality Provider
Version
May 15, 2007 -- O van Eijk -- initial version
Member Function Documentation
static Register::getCode ($ value, $ unknown = '*unknown*') [static]
Translate an hex value code to the symbolic name
Parameters
in $value Hex value of the status code
in $unknown Return value if the code does not exist
Returns
Human readable value
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
Referenced by LogHandler::composeMessage(), StatusHandler::getMessage(), _OWL::setStatus(), and OWLException::stackDump().
static Register::getRunId () [static]
Return the ID of the current run
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
Referenced by LogHandler::composeMessage(), and LogHandler::setFilename().
static Register::getSeverity ($ level) [static]
Read a severity level from the register
Parameters
in $level Hex value of the severity level
Returns
Human readable value
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
Referenced by OWLException::stackDump().
static Register::getSeverityLevel ($ name) [static]
This function is used by a config parse to translate a string value to the appropriate severity level
Parameters
in $name The name of the severity level
Returns
Hex value of the severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
Referenced by ConfigHandler::convert().
static Register::init () [static]
Initialise the register array
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
static Register::registerApp ($ name, $ id) [static]
Store the specified application in the register
Parameters
in $name Name of the class
in $id Application ID
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, and setApplication().
static Register::registerClass ($ name) [static]
Store the specified class in the register, and setup an array to keep track of the codes
Parameters
in $name Name of the class
Todo Error handling when out of range
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
static Register::registerCode ($ code) [static]
Define a new statuscode
Parameters
in $code Symbolic name of the status code
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
static Register::registerLabels ($ _owl = false) [static]
Load the labels file for OWL or the application
Parameters
in $_owl When true, the OWL file(s) will be loaded, by default only the application's
Author
Oscar van Eijk, Oveas Functionality Provider
References $_labels, $GLOBALS, OWLCache::get(), ConfigHandler::get(), and OWLCache::set().
static Register::registerMessages ($ _force = false) [static]
Load the message file for OWL and the application
Parameters
in $_force Boolean to force a reload with (different) translations, defaults to false
Author
Oscar van Eijk, Oveas Functionality Provider
References $_messages, $GLOBALS, OWLCache::get(), ConfigHandler::get(), and OWLCache::set().
Referenced by StatusHandler::getMessage().
static Register::registerSeverity ($ level, $ name) [static]
Store the known severitylevels in the register
Parameters
in $level Symbolic name for the severity level
in $name Human readable value
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
static Register::setApplication ($ app_id) [static]
Point the register to the specified application.
Parameters
in $app_id Application ID
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
Referenced by registerApp().
static Register::setClass ($ class_id) [static]
Point the register to the specified class.
Parameters
in $class_id Class ID
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
static Register::setSeverity ($ severity_level) [static]
Set the current severity to the specified level in the Register
Parameters
in $severity_level Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.register.php