FormFieldCheckboxPlugin Class Reference
Formfield.
Public Member Functions
__construct ()
setChecked ($_value=true)
setValue ($_value)
showElement ()
setDisabled ($_value=true)
setReadonly ($_value=true)
getType ()
setId ($_value)
getId ()
setName ($_value)
setStyle ($_value)
setClass ($_value)
setContent (&$_content)
getContent ()
setEvent ($_event, $_action, $_add=false)
get_status ()
get_severity ($status=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Protected Member Functions
getGenericFieldAttributes ($_ignore=array())
setAttributes ($_attribs)
getAttributes ($_ignore=array())
init ()
reset ()
save_status ()
restore_status ()
check (&$object, $level)
set_status ($status, $params=array())
set_high_severity (&$object=null)
Protected Attributes
$type
$value
$disabled
$readonly
$class = ''
$style = ''
$events = array()
$name = ''
$id = ''
$severity
Private Attributes
$checked
Detailed Description
Formfield. Formfield Checkbox elements
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Oct 19, 2010 -- O van Eijk -- initial version
Constructor & Destructor Documentation
FormFieldCheckboxPlugin::__construct ()
Class constructor;
Reimplemented from FormFieldPlugin.
Member Function Documentation
_OWL::check (&$ object, $ level) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
[in] $object Pointer to an object to check against
[in] $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
References _OWL::reset(), _OWL::set_high_severity(), and _OWL::traceback().
Referenced by SessionHandler::write().
_OWL::get_severity ($ status = null) [inherited]
Get the current object severity level.
Parameters
[in] $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
References _OWL::$status.
Referenced by LogHandler::compose_message(), LogHandler::log(), and DataHandler::set_key().
_OWL::get_status () [final, inherited]
Get the current object status.
Returns
Object's status code
Referenced by SchemeHandler::compare().
BaseElement::getAttributes ($ _ignore = array()) [protected, inherited]
Return the general element attributes that are set
Parameters
[in] $_ignore Array with attributes names that should be ignored
Returns
string attributes in HTML format (' fld=`value`...)
References BaseElement::getEvents().
Referenced by FormFieldPlugin::getGenericFieldAttributes(), Form::openForm(), Tablerow::showElement(), Tablecell::showElement(), Table::showElement(), and Container::showElement().
BaseElement::getContent () [inherited]
Get the content of the current container, which can be plain HTML or an object, in which case the HTML will be retrieved from the object here. Enter description here ...
Referenced by Tablecell::showElement(), and Container::showElement().
FormFieldPlugin::getGenericFieldAttributes ($ _ignore = array()) [protected, inherited]
Return the attributes for an HTML formfield in the ` attrib='value' [...]` format
Parameters
[in] $_ignore Array with attributes names that should be ignored, e.g. for a textarea, the value is not returned as an attribute.
Returns
Textstring with the HTML code
References BaseElement::getAttributes().
Referenced by FormFieldTextareaPlugin::showElement(), FormFieldTextPlugin::showElement(), FormFieldSelectPlugin::showElement(), FormFieldRadioPlugin::showElement(), showElement(), and FormFieldButtonPlugin::showElement().
BaseElement::getId () [inherited]
Get the element's HTML ID
Returns
The ID
FormFieldPlugin::getType () [inherited]
Give the field type
Returns
Field type
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
References OWL::factory().
Referenced by FormFieldPlugin::__construct(), Tablerow::__construct(), Tablecell::__construct(), Table::__construct(), ContainerPlugin::__construct(), Container::__construct(), UserHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), OWL::__construct(), Form::__construct(), Dispatcher::__construct(), and DataHandler::DataHandler().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Reimplemented in DbHandler, and SchemeHandler.
References _OWL::reset_calltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::set_status().
_OWL::restore_status () [protected, inherited]
Restore the previously saved status object and destroy the copy
References _OWL::set_status().
Referenced by UserHandler::logout().
_OWL::save_status () [protected, inherited]
Create a copy of the status object
Referenced by UserHandler::logout().
_OWL::set_high_severity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
_OWL::set_status ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
[in] $status OWL status code
[in] $params
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::get_code(), _OWL::reset(), and _OWL::signal().
Referenced by Container::__construct(), UserHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), Form::__construct(), Form::addField(), SchemeHandler::alter_scheme(), FileHandler::close(), DbHandler::connect(), DbHandler::create(), SchemeHandler::create_scheme(), DataHandler::DataHandler(), SchemeHandler::define_index(), SchemeHandler::define_scheme(), Dispatcher::dispatch(), FormHandler::get(), DataHandler::get(), SchemeHandler::get_table_columns(), SchemeHandler::get_table_indexes(), UserHandler::login(), FileHandler::open(), DbHandler::open(), LogHandler::open_logfile(), DataHandler::prepare(), DbHandler::prepare_delete(), DbHandler::prepare_insert(), DbHandler::prepare_read(), DbHandler::prepare_update(), DbHandler::read(), FileHandler::read_line(), UserHandler::read_userdata(), _OWL::restore_status(), SchemeHandler::scheme(), FormHandler::set(), DataHandler::set(), DataHandler::set_join(), DataHandler::set_key(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), Form::setFieldAttributes(), FormFieldTextPlugin::setMaxsize(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), FormFieldRadioPlugin::setValue(), Form::showField(), SchemeHandler::table_description(), SchemeHandler::validate_scheme(), and DbHandler::write().
BaseElement::setAttributes ($ _attribs) [protected, inherited]
Set the attributes of the DOM element by calling the 'set<Attrib>' method for this class.
Parameters
[in] $_attribs Array with attributes in the format attrib=>value
Returns
Severity level. The status increased when a set<Attrib> method does not exist.
Reimplemented in Tablecell, and Tablerow.
References _OWL::set_status().
Referenced by Table::__construct(), and Container::__construct().
FormFieldCheckboxPlugin::setChecked ($ _value = true)
Set the Checked boolean
Parameters
[in] $_value Value indicating true (default) or false
BaseElement::setClass ($ _value) [inherited]
Set the element Class
Parameters
[in] $_value Class name
BaseElement::setContent (&$ _content) [inherited]
Fill the content for a container. Existing content (e.g. set during instantiation) will be overwritten.
Parameters
[in] $_content Reference to the content, which can be HTML code or an object, of which the showElement() method will be called to retrieve the HTML.
References _OWL::set_status().
Referenced by Tablecell::__construct(), and Container::__construct().
FormFieldPlugin::setDisabled ($ _value = true) [inherited]
Set the Disabled boolean
Parameters
[in] $_value Value indicating true (default) or false
BaseElement::setEvent ($ _event, $ _action, $ _add = false) [inherited]
Add an event to the events array
Parameters
[in] $_event Javascript event name (onXxx)
[in] $_action Javascript function or code
[in] $_add Boolean; when true, the action will be added if the event name already exists. Default is false; overwrite the action for this event.
BaseElement::setId ($ _value) [inherited]
Set the element ID
Parameters
[in] $_value Identification
Referenced by BaseElement::setName().
BaseElement::setName ($ _value) [inherited]
Set the element name
Parameters
[in] $_value Element name
References BaseElement::setId().
FormFieldPlugin::setReadonly ($ _value = true) [inherited]
Set the Readonly boolean
Parameters
[in] $_value Value indicating true (default) or false
BaseElement::setStyle ($ _value) [inherited]
Set the element style
Parameters
[in] $_value Element style
FormFieldCheckboxPlugin::setValue ($ _value)
Reimplement; value defaults to 1 for checkboxes
Parameters
[in] $_value Field value
Reimplemented from FormFieldPlugin.
FormFieldCheckboxPlugin::showElement ()
Return the HTML code to display the form element
Returns
Textstring with the complete code for the form element
Reimplemented from FormFieldPlugin.
References FormFieldPlugin::getGenericFieldAttributes().
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
[in] $level An optional severity level; message will only be displayed when it is at least of this level.
[out] $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
References ConfigHandler::get().
Referenced by _OWL::set_status(), and _OWL::traceback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
[out] $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
[in] $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
References _OWL::signal().
Referenced by _OWL::check(), UserHandler::login(), and SessionHandler::read().
Member Data Documentation
FormFieldCheckboxPlugin::$checked [private]
Boolean set to true when the box is checked
BaseElement::$class = '' [protected, inherited]
Class specification
FormFieldPlugin::$disabled [protected, inherited]
Boolean indicating a disabled field when true
BaseElement::$events = array() [protected, inherited]
Array with javascript events
Referenced by Form::setFieldEvents().
BaseElement::$id = '' [protected, inherited]
Element ID
BaseElement::$name = '' [protected, inherited]
Name of the element
Referenced by Form::addField(), and Form::showField().
FormFieldPlugin::$readonly [protected, inherited]
Boolean indicating a readonly field when true
_OWL::$severity [protected, inherited]
Severity level of the current object status
BaseElement::$style = '' [protected, inherited]
Element style
FormFieldPlugin::$type [protected, inherited]
Field type
Reimplemented in FormFieldTextareaPlugin.
Referenced by FormFieldTextPlugin::__construct(), and FormFieldButtonPlugin::__construct().
FormFieldPlugin::$value [protected, inherited]
Field value
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/plugins/formfields/class.formfield.checkbox.php