Document Class Reference
Document.
Public Member Functions
addMessage ($stack, $message)
addStyle ($_style= '')
loadStyle ($_style= '', $_condition= '')
addScript ($_script= '')
loadScript ($_script= '')
setTitle ($_value)
setFavicon ($_icon)
setBase ($_url)
setMeta (array $_tags)
setHeader (array $_hdrs)
setContenttype ($_value)
getBase ()
showElement ()
setId ($_value)
getId ()
setName ($_value)
setStyle ($_value)
setClass ($_value)
setContent (&$_content)
addToContent (&$_content, $_front=false)
getContent ()
setEvent ($_event, $_action, $_add=false)
setAttributes (array $_attribs)
getLastWarning ()
getStatus ()
getSeverity ($status=null)
succeeded ($_ok=OWL_SUCCESS, &$_object=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Static Public Member Functions
static getInstance ()
Protected Member Functions
__construct (array $_attribs=array())
getAttributes (array $_ignore=array())
init ()
setCallback ($_dispatcher)
setCallbackArgument (array $_arg)
getCallback ()
reset ()
saveStatus ()
restoreStatus ()
check (&$object, $level=OWL_WARNING)
setStatus ($status, $params=array())
setHighSeverity (&$object=null)
stackMessage ($level=OWL_WARNING)
Protected Attributes
$class = ''
$style = ''
$events = array()
$name = ''
$id = ''
$severity
Static Protected Attributes
static $instance
Private Member Functions
_getMeta ()
_loadStyles ()
_loadScripts ()
_getStyles ()
_getScripts ()
addMessagesToContent ()
Private Attributes
$base
$styles
$css
$scripts
$js
$title
$meta
$headers
$favicon
$contentType
$messages
Detailed Description
Document.
Class for Document singletons. This class can be extended defining other document types
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Jan 9, 2011 -- O van Eijk -- initial version
Constructor & Destructor Documentation
Document::__construct (array $ _attribs = array()) [protected]
Class constructor;
Parameters
in $_attribs Indexed array with the HTML attributes
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::init().
Member Function Documentation
Document::_getMeta () [private]
Get the meta tags
Returns
HTML code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by showElement().
Document::_getScripts () [private]
Get the on-the-fly javascript
Returns
HTML code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by showElement().
Document::_getStyles () [private]
Get the on-the-fly styles
Returns
HTML code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by showElement().
Document::_loadScripts () [private]
Get the javascripts to load
Returns
HTML code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by showElement().
Document::_loadStyles () [private]
Get the stylesheets to load
Returns
HTML code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by showElement().
Document::addMessage ($ stack, $ message)
Add a new message to the proper message stack. For each severity level a seperate stack will be created. When the document is displayed, these messages will be formatted and added the the documents output
Parameters
in $stack Severity level, indicating the stack
in $message The complete message as composed by signal()
Author
Oscar van Eijk, Oveas Functionality Provider
Document::addMessagesToContent () [private]
If messages have been generated during this run that have been added to the messages stacks, generate the containers now and add them to the front of the content objectlist
Author
Oscar van Eijk, Oveas Functionality Provider
References BaseElement::$class, and BaseElement::addToContent().
Referenced by showElement().
Document::addScript ($ _script = '')
Add an on-the-fly javascript to the document
Parameters
$_script Script code without the <(/)script> tags
Author
Oscar van Eijk, Oveas Functionality Provider
Document::addStyle ($ _style = '')
Add an on-the-fly style tag to the document
Parameters
$_style HTML code to define the style, without the <(/)style> tags
Author
Oscar van Eijk, Oveas Functionality Provider
BaseElement::addToContent (&$ _content, $ _front = false) [inherited]
Add a content to the container. If the container is not an array yet, it will be converted to one.
Parameters
in $_content Reference to the content, which can be HTML code or an object, of which the showElement() method will be called to retrieve the HTML.
in $_front When true, the content item will be the first item in the list with content items. By default, it is added to the end of the list.
Author
Oscar van Eijk, Oveas Functionality Provider
Examples:
exa.form.php.
References _OWL::setStatus().
Referenced by addMessagesToContent().
_OWL::check (&$ object, $ level = OWL_WARNING) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
in $object Pointer to an object to check against
in $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::reset(), _OWL::setHighSeverity(), and _OWL::traceback().
Referenced by SessionHandler::write().
BaseElement::getAttributes (array $ _ignore = array()) [protected, inherited]
Return the general element attributes that are set
Parameters
in $_ignore Array with attributes names that should be ignored
Returns
string attributes in HTML format (' fld=`value`...)
Author
Oscar van Eijk, Oveas Functionality Provider
References BaseElement::getEvents().
Referenced by FormFieldPlugin::getGenericFieldAttributes(), Form::openForm(), showElement(), and Container::showElement().
Document::getBase ()
Get the Base href
Returns
URL
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::getCallback () [protected, inherited]
Retrieve a previously set (callback) dispatcher. The (callback) dispatcher is cleared immediatly.
Returns
The dispatcher, of null on failure.
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in Dispatcher .
References OWL::factory().
BaseElement::getContent () [inherited]
Get the content of the current container, which can be plain HTML, an object, or an array which can mix both types.
Returns
HTML code
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in ContainerFieldsetPlugin , ContainerListPlugin , ContainerMenuPlugin , ContainerTablePlugin , and ContainerTablerowPlugin .
References BaseElement::_getContent().
Referenced by showElement(), Container::showElement(), and Form::showElement().
BaseElement::getId () [inherited]
Get the element's HTML ID
Returns
The ID
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by BaseElement::_getContent().
static Document::getInstance () [static]
Return a reference to my implementation. If necessary, create that implementation first.
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References $instance.
_OWL::getLastWarning () [inherited]
Get the last warning or error message.
Returns
null if there was no error (severity below OWL_WARNING), otherwise the error text.
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
_OWL::getSeverity ($ status = null) [inherited]
Get the current object severity level.
Parameters
in $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::$status.
Referenced by LogHandler::composeMessage(), LogHandler::log(), and DataHandler::setKey().
_OWL::getStatus () [final, inherited]
Get the current object status.
Returns
Object's status code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by SchemeHandler::compare().
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory(), and _OWL::setStatus().
Referenced by FormFieldPlugin::__construct(), __construct(), ContainerPlugin::__construct(), Container::__construct(), SocketHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), HDataHandler::__construct(), DataHandler::__construct(), OWL::__construct(), Mail::__construct(), Group::__construct(), Form::__construct(), Dispatcher::__construct(), and User::construct().
Document::loadScript ($ _script = '')
Add a Javascript sourcefile to the document
Parameters
$_script URL of the scriptsource
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus(), urlExpand(), and urlToPath().
Document::loadStyle ($ _style = '', $ _condition = '')
Add a CSS stylesheet to the document
Parameters
in $_style URL of the stylesheet
in $_condition Condition to specify the browser(s), e.g. `lte IE 6` means the stylesheet will be loaded only for Internet Explorer up and including version 6.
See also
http://www.thesitewizard.com/css/excludecss.shtml for the syntax
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus(), urlExpand(), and urlToPath().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in DbHandler , and SchemeHandler .
References _OWL::resetCalltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::setStatus().
_OWL::restoreStatus () [protected, inherited]
Restore the previously saved status object and destroy the copy
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by User::logout().
_OWL::saveStatus () [protected, inherited]
Create a copy of the status object
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::logout().
BaseElement::setAttributes (array $ _attribs) [inherited]
Set the attributes of the DOM element by calling the 'set<Attrib>' method for this class.
Parameters
in $_attribs Array with attributes in the format attrib=>value
Returns
Severity level. The status increased when a set<Attrib> method does not exist.
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in Container .
References _OWL::setStatus().
Referenced by Form::__construct().
Document::setBase ($ _url)
Set the base URL for the site
Parameters
in $_url Fully qualified URL
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::setCallback ($ _dispatcher) [protected, inherited]
Set a dispatcher for later callback
Parameters
in $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher()
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
_OWL::setCallbackArgument (array $ _arg) [protected, inherited]
Add an argument to a previously registered callback dispatcher
Parameters
in $_arg Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
Referenced by User::register().
BaseElement::setClass ($ _value) [inherited]
Set the element Class
Parameters
in $_value Class name
Author
Oscar van Eijk, Oveas Functionality Provider
BaseElement::setContent (&$ _content) [inherited]
Fill the content for a container. Existing content (e.g. set during instantiation) will be overwritten. If that is not desired, the addToContent method should be used instead.
Parameters
in $_content Reference to the content, which can be HTML code or an object, of which the showElement() method will be called to retrieve the HTML.
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by Container::__construct().
Document::setContenttype ($ _value)
Set the page's content type
Parameters
in $_value Title value
Author
Oscar van Eijk, Oveas Functionality Provider
BaseElement::setEvent ($ _event, $ _action, $ _add = false) [inherited]
Add an event to the events array
Parameters
in $_event Javascript event name (onXxx)
in $_action Javascript function or code
in $_add Boolean; when true, the action will be added if the event name already exists. Default is false; overwrite the action for this event.
Author
Oscar van Eijk, Oveas Functionality Provider
Document::setFavicon ($ _icon)
Set the Favorites Icon
Parameters
in $_icon URL to the icon. It must be on the local site
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus(), urlExpand(), and urlToPath().
Document::setHeader (array $ _hdrs)
Set, update or overwrite HTML headers.
Parameters
in $_hdrs Array with headers in the format 'header' => 'value'
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::setHighSeverity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
BaseElement::setId ($ _value) [inherited]
Set the element ID
Parameters
in $_value Identification
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by BaseElement::setName().
Document::setMeta (array $ _tags)
Set, update or overwrite metatags. Only the 'generator' metatag cannot be overwritten
Parameters
in $_tags Array with meta tags in the format 'name' => 'content'
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
BaseElement::setName ($ _value) [inherited]
Set the element name
Parameters
in $_value Element name
Author
Oscar van Eijk, Oveas Functionality Provider
References BaseElement::setId().
_OWL::setStatus ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
in $status OWL status code
in $params
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::getCode(), _OWL::reset(), and _OWL::signal().
Referenced by Container::__call(), DbHandler::__clone(), Container::__construct(), SocketHandler::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), Session::__construct(), Mail::__construct(), BaseElement::_getContent(), HDataHandler::_getNewLeft(), Mail::addBcc(), Mail::addCc(), Container::addContainer(), Form::addField(), FormFieldRadioPlugin::addOption(), HDataHandler::addParent(), Mail::addTo(), BaseElement::addToContent(), DbHandler::alt(), SchemeHandler::alterScheme(), FileHandler::close(), DbHandler::commitTransaction(), Dispatcher::composeDispatcher(), User::confirm(), SocketHandler::connect(), DbHandler::connect(), DbHandler::create(), SchemeHandler::createScheme(), DbHandler::dbread(), SchemeHandler::defineIndex(), SchemeHandler::defineScheme(), SocketHandler::disconnect(), Dispatcher::dispatch(), HDataHandler::enableCrossLink(), FormHandler::get(), DataHandler::get(), HDataHandler::getDirectChildren(), HDataHandler::getFullOffspring(), Group::getGroupByName(), SchemeHandler::getTableColumns(), SchemeHandler::getTableIndexes(), _OWL::init(), loadScript(), loadStyle(), DbHandler::lockTable(), User::login(), HDataHandler::moveNode(), FileHandler::open(), DbHandler::open(), LogHandler::openLogfile(), DataHandler::prepare(), DbHandler::prepareDelete(), DbHandler::prepareField(), DbHandler::prepareInsert(), DbHandler::prepareRead(), DbHandler::prepareUpdate(), SocketHandler::read(), DbHandler::read(), FileHandler::readLine(), HDataHandler::readQuery(), User::readUserdata(), User::register(), Dispatcher::registerArgument(), Dispatcher::registerCallback(), DbHandler::resetTable(), _OWL::restoreStatus(), DbHandler::rollbackTransaction(), SchemeHandler::scheme(), Mail::send(), FormHandler::set(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), setFavicon(), Form::setFieldAttributes(), Mail::setFrom(), DataHandler::setJoin(), DataHandler::setKey(), FormFieldTextPlugin::setMaxsize(), setMeta(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), Mail::setSender(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), Form::showField(), DbHandler::startTransaction(), SchemeHandler::tableDescription(), DbHandler::unlockTable(), SchemeHandler::validateScheme(), SocketHandler::write(), DbHandler::write(), and HDataHandler::writeQuery().
BaseElement::setStyle ($ _value) [inherited]
Set the element style
Parameters
in $_value Element style
Author
Oscar van Eijk, Oveas Functionality Provider
Document::setTitle ($ _value)
Set the page title
Parameters
in $_value Title value
Author
Oscar van Eijk, Oveas Functionality Provider
Document::showElement ()
Get the HTML code to display the document
Returns
string with the HTML code
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from BaseElement .
References _getMeta(), _getScripts(), _getStyles(), _loadScripts(), _loadStyles(), addMessagesToContent(), BaseElement::getAttributes(), and BaseElement::getContent().
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
in $level An optional severity level; message will only be displayed when it is at least of this level.
out $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get(), OutputHandler::outputLine(), and OutputHandler::outputRaw().
Referenced by _OWL::getLastWarning(), _OWL::setStatus(), _OWL::stackMessage(), and _OWL::traceback().
_OWL::stackMessage ($ level = OWL_WARNING) [protected, inherited]
Add the message for the latests status change to the document
See also
Document::addMessage()
Parameters
in $level Minimum severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References $_doc, _OWL::$severity, OWL::factory(), and _OWL::signal().
_OWL::succeeded ($ _ok = OWL_SUCCESS, &$ _object = null) [inherited]
Check if the object currenlty has a success state
Parameters
in $_ok The highest severity that's considered successfull, default OWL_SUCCESS
in $_object REference to the object to check, defaults to the current object
Returns
Boolean true when successfull
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::construct(), Dispatcher::registerArgument(), and Dispatcher::registerCallback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
out $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
in $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
Referenced by _OWL::check(), User::login(), and SessionHandler::read().
Member Data Documentation
Document::$base [private]
Base URL for the application, defaults to the server top
BaseElement::$class = '' [protected, inherited]
Class specification
Referenced by addMessagesToContent().
Document::$contentType [private]
String for the content type
Document::$css [private]
Array for stylesheet sources
BaseElement::$events = array() [protected, inherited]
Array with javascript events
Referenced by Form::setFieldEvents().
Document::$favicon [private]
String for the Favicon URL;
Document::$headers [private]
Array for HTML headers
BaseElement::$id = '' [protected, inherited]
Element ID
Document::$instance [static, protected]
integer - self reference
Referenced by getInstance().
Document::$js [private]
Array for javascript sources;
Document::$messages [private]
List of errors, warnings and other requested messages
Document::$meta [private]
Array for meta tags
BaseElement::$name = '' [protected, inherited]
Name of the element
Referenced by Form::addField(), and Form::showField().
Document::$scripts [private]
Array for on-the-fly scripts
_OWL::$severity [protected, inherited]
Severity level of the current object status
Referenced by _OWL::stackMessage().
BaseElement::$style = '' [protected, inherited]
Element style
Document::$styles [private]
Array for on-the-fly styles
Document::$title [private]
String for the document title
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/ui/class.document.php