Rights Class Reference
the OWL-PHP rights object
Public Member Functions
__construct ($app, $owl=true)
__wakeup ()
bitValue ($name)
__sleep ()
initBitmap ($value, $app)
getBitmap ($app)
mergeBitmaps ($bitmap, $app)
controlBitmap ($bit, $app, $controller=BIT_CHECK)
Protected Attributes
$bitmap
Private Member Functions
registerRights ()
Private Attributes
$rightslist
Detailed Description
the OWL-PHP rights object
This class handles the Rights bitmaps
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Apr 14, 2011 -- O van Eijk -- initial version
Constructor & Destructor Documentation
Rights::__construct ($ app, $ owl = true)
Class constructor
Parameters
in $app code for which the bitmap array must be setup
in $owl By default, the owl bitmap will be setup as well. Set this to false to suppress this
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from Security .
References OWLCache::get(), and registerRights().
Member Function Documentation
Security::__sleep () [inherited]
Magic function for serialize; make sure only the required data is serialized
Author
Oscar van Eijk, Oveas Functionality Provider
Rights::__wakeup ()
The rightslist is stored in cache, not in the serialized object, so we must retrieve it again on unserialize()
Author
Oscar van Eijk, Oveas Functionality Provider
References OWLCache::get(), and registerRights().
Rights::bitValue ($ name)
Get the bitvalue for a given name
Parameters
in $name Name of the rights bit
Returns
Integer value
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from Security .
Security::controlBitmap ($ bit, $ app, $ controller = BIT_CHECK) [inherited]
Check, set or unset a bit in the current users bitmap. Enter description here ...
Parameters
in $bit Bit that should be checked or (un)set
in $app Application ID the bit belongs to
in $controller Controller defining the action, defaults to check
Returns
True if the bit was set (*before* a set or unset action!)
Author
Oscar van Eijk, Oveas Functionality Provider
References toStrictBoolean().
Security::getBitmap ($ app) [inherited]
Get the bitmap value for the given application
Parameters
in $app Application ID
Returns
Bitmap value as an integer
Author
Oscar van Eijk, Oveas Functionality Provider
Security::initBitmap ($ value, $ app) [inherited]
(Re)initialise the bitmap for the given application
Parameters
in $value Bitmap value
in $app Application ID
Author
Oscar van Eijk, Oveas Functionality Provider
Security::mergeBitmaps ($ bitmap, $ app) [inherited]
Merge a given gitmap with the current users bitmap
Parameters
in $bitmap Rightlist bitmap
in $app Application the bitmap belongs to
Author
Oscar van Eijk, Oveas Functionality Provider
References Security::$bitmap.
Rights::registerRights () [private]
If the rightlist is not yet filled, do so now and store the list in cache
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get(), and OWLCache::set().
Referenced by __construct(), and __wakeup().
Member Data Documentation
Security::$bitmap [protected, inherited]
Array with security bitmaps bitmaps for the current user
Referenced by Security::mergeBitmaps().
Rights::$rightslist [private]
Array with all known right identifiers
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/bo/class.rights.php