ConfigHandler Class Reference
Configuration handler.
Static Public Member Functions
static readConfig (array $_source)
static get ($item, $default=null, $force=false)
static set ($_item, $_value)
Static Private Member Functions
static configFile ($_file)
static configTable ($_table, $_applic, $_group, $_user, $_force)
static convert ($val)
static parseItem ($_item, $_value, $_protect, $_hide)
static _set ($_item, $_value, $_hide)
Static Private Attributes
static $dataset = null
Detailed Description
Configuration handler.
This abstract class reads configution from file ort database, and fills and reads the global datastructure with config items
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Aug 20, 2008 -- O van Eijk -- initial version
Member Function Documentation
static ConfigHandler::_set ($ _item, $ _value, $ _hide) [static, private]
Set or update a configuration item
Parameters
in $_item Item name or path (seperated with '|')
in $_value The calue to be set
in $_hide Boolean which it true when this is a hidden item
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, and owlCrypt().
Referenced by parseItem(), and set().
static ConfigHandler::configFile ($ _file) [static, private]
Parse a configuration file
Parameters
in $_file Filename
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, and parseItem().
Referenced by readConfig().
static ConfigHandler::configTable ($ _table, $ _applic, $ _group, $ _user, $ _force) [static, private]
Parse a configuration table
Parameters
in $_table Config tablename without prefix
in $_applic Application name for which the config should be read
in $_group Group ID for which the config should be read
in $_user User ID for which the config should be read
in $_force Boolean that can force overwrite of protected values
Author
Oscar van Eijk, Oveas Functionality Provider
References $_table, and parseItem().
Referenced by readConfig().
static ConfigHandler::convert ($ val) [static, private]
Convert values in character string format to a known value
Parameters
in $val The value as read from the config file
Returns
Value in the desired format (or as is if nothing set)
Author
Oscar van Eijk, Oveas Functionality Provider
References Register::getSeverityLevel().
Referenced by parseItem().
static ConfigHandler::get ($ item, $ default = null, $ force = false) [static]
Return a configuration value.
Note
In order to use hidden values properly, this is the ONLY way configuration values should be retrieved!
Parameters
in $item The configuration item in the same format as it appears in the configuration file (e.g. 'group|subject|item')
in $default The default value to return if the config item was not set. This defaults to 'null'; if it is anything other than null, the CONFIG_NOVALUE status will not be set
in $force Boolean to force a reparse of the config item ignoring existing cache values
Returns
Corresponding value of null when nothing was found
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, owlCrypt(), and OWL::stat().
Referenced by SessionHandler::__construct(), LogHandler::__construct(), OWLException::__construct(), DbHandler::__construct(), Session::__construct(), Group::__construct(), OWLException::checkHide(), LogHandler::composeMessage(), DbHandler::connect(), User::construct(), OWLinstaller::enableApplication(), DbHandler::forceReread(), FormHandler::get(), Group::getGroupRights(), DbHandler::getInstance(), User::getMemberships(), OWLloader::getOWLId(), User::hashPassword(), OWLinstaller::installApplication(), User::isLoggedIn(), LogHandler::log(), OWLExceptionHandler::logException(), User::login(), User::logout(), LogHandler::logSession(), User::newUser(), owlCrypt(), OWLdbg_add(), User::readUserdata(), User::register(), Register::registerLabels(), Register::registerMessages(), Rights::registerRights(), FormHandler::set(), LogHandler::setApplicLogfile(), LogHandler::setFilename(), _OWL::setStatus(), _OWL::signal(), OWLException::traceback(), and ContentArea::trn().
static ConfigHandler::parseItem ($ _item, $ _value, $ _protect, $ _hide) [static, private]
Parse a configuration item as read from the file or database, and store is
Parameters
in $_item Name of the config item
in $_value Value of the config item
in $_protect Boolean indicating a protected value
in $_hide Boolean indicated a hidden value
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, _set(), convert(), and OWL::stat().
Referenced by configFile(), and configTable().
static ConfigHandler::readConfig (array $ _source) [static]
Parse the given configuration source
Parameters
in $_source Array describing the configuration source. It can have the following keys:
file: Full path to the configuration file
table: Config tablename without prefix. Default 'config', MUST be given with the first call
applic: Application name for which the config should be read, default 'owl'
group: Application name for which the config should be read, default 0
user: Application name for which the config should be read, default 0
force: Boolean that can force overwrite of protected values, default false
The first call must always read from a file. On subsequent calls, if no filename is given, the configuration is taken from the (owl_)config table
Author
Oscar van Eijk, Oveas Functionality Provider
References configFile(), configTable(), and toStrictBoolean().
static ConfigHandler::set ($ _item, $ _value) [static]
Set a configuration item. Existing values will be overwritten when not protected.
Parameters
in $_item The configuration item in the same format as it appears in the configuration file (e.g. 'group|subject|item')
in $_value The new value of the item
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, _set(), and OWL::stat().
Member Data Documentation
ConfigHandler::$dataset = null [static, private]
Datahandler object for database access
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.confighandler.php