OWLTimers Class Reference
Timer handler.
Static Public Member Functions
static startTimer ($name)
static stopTimer ($name)
static showTimer ()
Static Private Member Functions
static mtimeFloat ()
Static Private Attributes
static $activeTimers = array()
static $timers = array()
static $warnings = array()
Detailed Description
Timer handler.
This abstract class sets up timers that can be used to check the runtime of both the total and parts.
To enable timers, the constant OWL_TIMERS_ENABLES must be defined by the application before OWLloader.php is included, e.g.:
 define ('OWL_TIMERS_ENABLED', true);
 require (OWL_ROOT . '/OWLloader.php');
Timers can be started anywhere in the code. When timers are not enabled, it won't have any effect. Starting timers can be done with OWLTimers::startTimer('name'). Later in the code they can be stopped with OWLTimers::stopTimer('name'), where 'name' must be unique.
At the end of the run, the total running time of the application will be displayed, end the running time of the individual timers (the part between startTimer() and stopTimer()) with their percentage of the total time.
Timers that are not stopped, will be timed until the application rundown.
Author
Oscar van Eijk, Oveas Functionality Provider
Version
May 21, 2011 -- O van Eijk -- initial version
Member Function Documentation
static OWLTimers::mtimeFloat () [static, private]
Get the current microtime
Returns
Microtime as a floating int value
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by startTimer(), and stopTimer().
static OWLTimers::showTimer () [static]
Show all timers. This method is called by OCLrundown.php at the end of the run
Author
Oscar van Eijk, Oveas Functionality Provider
References OutputHandler::outputPar(), stopTimer(), and ContentArea::translate().
static OWLTimers::startTimer ($ name) [static]
Start a new timer, creating an array key with the actual timestamp.
Parameters
in $name Unique name of the timer.
Author
Oscar van Eijk, Oveas Functionality Provider
References mtimeFloat(), and ContentArea::translate().
static OWLTimers::stopTimer ($ name) [static]
Stop an active timer and update the array key with the execution time since the start timestamp.
Parameters
in $name Unique name of the timer.
Returns
Author
Oscar van Eijk, Oveas Functionality Provider
References mtimeFloat(), and ContentArea::translate().
Referenced by showTimer().
Member Data Documentation
OWLTimers::$activeTimers = array() [static, private]
Array holding the timers that are currently active
OWLTimers::$timers = array() [static, private]
Array holding all timers and their values
OWLTimers::$warnings = array() [static, private]
Array with warning messages if applicable
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.timers.php