FormFieldText Class Reference
Formfield.
Public Member Functions
__construct ($type= 'text')
setSize ($size)
setMaxsize ($maxsize)
getFieldCode ()
setValue ($_value)
setDisabled ($_value=true)
setReadonly ($_value=true)
getType ()
setId ($_value)
setName ($_value)
setStyle ($_value)
setClass ($_value)
setEvent ($_event, $_action, $_add=false)
get_status ()
get_severity ($status=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Protected Member Functions
getGenericFieldAttributes ($_ignore=array())
setAttributes ($_attribs)
getAttributes ($_ignore=array())
init ()
reset ()
save_status ()
restore_status ()
check (&$object, $level)
set_status ($status, $params=array())
set_high_severity (&$object=null)
Protected Attributes
$type
$value
$disabled
$readonly
$class = ''
$style = ''
$events = array()
$name = ''
$id = ''
$severity
Private Attributes
$size
$maxsize
Detailed Description
Formfield. Formfield text elements
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Oct 19, 2010 -- O van Eijk -- initial version
Constructor & Destructor Documentation
FormFieldText::__construct ($ type = 'text')
Class constructor;
Parameters
[in] $type Element type: text (default), password or hidden
References FormField::$type, and FormField::__construct().
Member Function Documentation
_OWL::check (&$ object, $ level) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
[in] $object Pointer to an object to check against
[in] $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
References _OWL::reset(), _OWL::set_high_severity(), and _OWL::traceback().
Referenced by SessionHandler::write().
_OWL::get_severity ($ status = null) [inherited]
Get the current object severity level.
Parameters
[in] $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
References _OWL::$status.
Referenced by LogHandler::compose_message(), LogHandler::log(), and DataHandler::set_key().
_OWL::get_status () [final, inherited]
Get the current object status.
Returns
Object's status code
Referenced by SchemeHandler::compare().
BaseElement::getAttributes ($ _ignore = array()) [protected, inherited]
Return the general element attributes that are set
Parameters
[in] $_ignore Array with attributes names that should be ignored
Returns
string attributes in HTML format (' fld=`value`...)
References BaseElement::getEvents().
Referenced by FormField::getGenericFieldAttributes(), Table::getTable(), Tablecell::getTablecell(), Tablerow::getTablerow(), and Form::openForm().
FormFieldText::getFieldCode ()
Return the HTML code to display the form element
Returns
Textstring with the complete code for the form element
References FormField::getGenericFieldAttributes().
FormField::getGenericFieldAttributes ($ _ignore = array()) [protected, inherited]
Return the attributes for an HTML formfield in the ` attrib='value' [...]` format
Parameters
[in] $_ignore Array with attributes names that should be ignored, e.g. for a textarea, the value is not returned as an attribute.
Returns
Textstring with the HTML code
References BaseElement::getAttributes().
Referenced by FormFieldTextarea::getFieldCode(), getFieldCode(), FormFieldSelect::getFieldCode(), FormFieldRadio::getFieldCode(), FormFieldCheckbox::getFieldCode(), and FormFieldButton::getFieldCode().
FormField::getType () [inherited]
Give the field type
Returns
Field type
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
References OWL::factory().
Referenced by Tablerow::__construct(), Tablecell::__construct(), Table::__construct(), FormField::__construct(), UserHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), OWL::__construct(), Form::__construct(), Dispatcher::__construct(), and DataHandler::DataHandler().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Reimplemented in DbHandler, and SchemeHandler.
References _OWL::reset_calltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::set_status().
_OWL::restore_status () [protected, inherited]
Restore the previously saved status object and destroy the copy
References _OWL::set_status().
Referenced by UserHandler::logout().
_OWL::save_status () [protected, inherited]
Create a copy of the status object
Referenced by UserHandler::logout().
_OWL::set_high_severity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
_OWL::set_status ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
[in] $status OWL status code
[in] $params
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::get_code(), _OWL::reset(), and _OWL::signal().
Referenced by UserHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), Form::__construct(), Form::addField(), SchemeHandler::alter_scheme(), FileHandler::close(), DbHandler::connect(), DbHandler::create(), SchemeHandler::create_scheme(), DataHandler::DataHandler(), SchemeHandler::define_index(), SchemeHandler::define_scheme(), Dispatcher::dispatch(), FormHandler::get(), DataHandler::get(), SchemeHandler::get_table_columns(), SchemeHandler::get_table_indexes(), UserHandler::login(), FileHandler::open(), DbHandler::open(), LogHandler::open_logfile(), DataHandler::prepare(), DbHandler::prepare_delete(), DbHandler::prepare_insert(), DbHandler::prepare_read(), DbHandler::prepare_update(), DbHandler::read(), FileHandler::read_line(), UserHandler::read_userdata(), _OWL::restore_status(), SchemeHandler::scheme(), FormHandler::set(), DataHandler::set(), DataHandler::set_join(), DataHandler::set_key(), BaseElement::setAttributes(), Form::setEncoding(), Form::setFieldAttributes(), setMaxsize(), Form::setMethod(), FormFieldRadio::setSelected(), setSize(), FormFieldSelect::setSize(), FormFieldSelect::setValue(), FormFieldRadio::setValue(), Form::showField(), SchemeHandler::table_description(), SchemeHandler::validate_scheme(), and DbHandler::write().
BaseElement::setAttributes ($ _attribs) [protected, inherited]
Set the attributes of the DOM element by calling the 'set<Attrib>' method for this class.
Parameters
[in] $_attribs Array with attributes in the format attrib=>value
Returns
Severity level. The status increased when a set<Attrib&gt method does not exist.
Reimplemented in Tablecell, and Tablerow.
References _OWL::set_status().
Referenced by Table::__construct().
BaseElement::setClass ($ _value) [inherited]
Set the element Class
Parameters
[in] $_value Class name
FormField::setDisabled ($ _value = true) [inherited]
Set the Disabled boolean
Parameters
[in] $_value Value indicating true (default) or false
BaseElement::setEvent ($ _event, $ _action, $ _add = false) [inherited]
Add an event to the events array
Parameters
[in] $_event Javascript event name (onXxx)
[in] $_action Javascript function or code
[in] $_add Boolean; when true, the action will be added if the event name already exists. Default is false; overwrite the action for this event.
BaseElement::setId ($ _value) [inherited]
Set the element ID
Parameters
[in] $_value Identification
FormFieldText::setMaxsize ($ maxsize)
Set the Maxsize attribute
Parameters
[in] $maxsize integer
References $maxsize, and _OWL::set_status().
BaseElement::setName ($ _value) [inherited]
Set the element name
Parameters
[in] $_value Element name
FormField::setReadonly ($ _value = true) [inherited]
Set the Readonly boolean
Parameters
[in] $_value Value indicating true (default) or false
FormFieldText::setSize ($ size)
Set the Size attribute
Parameters
[in] $size integer
References $size, and _OWL::set_status().
BaseElement::setStyle ($ _value) [inherited]
Set the element style
Parameters
[in] $_value Element style
FormField::setValue ($ _value) [inherited]
Set the field value
Parameters
[in] $_value Field value
Reimplemented in FormFieldCheckbox, FormFieldRadio, and FormFieldSelect.
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
[in] $level An optional severity level; message will only be displayed when it is at least of this level.
[out] $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
References ConfigHandler::get().
Referenced by _OWL::set_status(), and _OWL::traceback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
[out] $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
[in] $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
References _OWL::signal().
Referenced by _OWL::check(), UserHandler::login(), and SessionHandler::read().
Member Data Documentation
BaseElement::$class = '' [protected, inherited]
Class specification
FormField::$disabled [protected, inherited]
Boolean indicating a disabled field when true
BaseElement::$events = array() [protected, inherited]
Array with javascript events
Referenced by Form::setFieldEvents().
BaseElement::$id = '' [protected, inherited]
Element ID
FormFieldText::$maxsize [private]
Maximum field size
Referenced by setMaxsize().
BaseElement::$name = '' [protected, inherited]
Name of the element
Referenced by Form::addField(), and Form::showField().
FormField::$readonly [protected, inherited]
Boolean indicating a readonly field when true
_OWL::$severity [protected, inherited]
Severity level of the current object status
FormFieldText::$size [private]
Field size
Referenced by setSize().
BaseElement::$style = '' [protected, inherited]
Element style
FormField::$type [protected, inherited]
Field type
Reimplemented in FormFieldTextarea.
Referenced by __construct(), and FormFieldButton::__construct().
FormField::$value [protected, inherited]
Field value
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/ui/formfields/class.formfield.text.php