LogHandler Class Reference
Log handler.
Public Member Functions
__destruct ()
__clone ()
setApplicLogfile ()
logSession (array $dispatcher, FormHandler $form=null)
log ($msg, $code)
getLastWarning ()
getStatus ()
getSeverity ($status=null)
succeeded ($_ok=OWL_SUCCESS, &$_object=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Static Public Member Functions
static getInstance ()
Protected Member Functions
init ()
setCallback ($_dispatcher)
setCallbackArgument (array $_arg)
getCallback ()
reset ()
saveStatus ()
restoreStatus ()
check (&$object, $level=OWL_WARNING)
setStatus ($status, $params=array())
setHighSeverity (&$object=null)
Protected Attributes
$severity
Private Member Functions
__construct ()
setFilename ()
openLogfile ()
closeLogfile ()
writeLogfile ($msg)
composeMessage (&$msg, $code)
backtrace ($_browser_dump=false)
Private Attributes
$opened
$filename
$fpointer
$dataset = null
$session_logged = false
Static Private Attributes
static $instance
Detailed Description
Log handler.
This singleton class handles all OWL logging
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Aug 13, 2008 -- O van Eijk -- initial version
Constructor & Destructor Documentation
LogHandler::__construct () [private]
Class constructor
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get(), _OWL::init(), openLogfile(), and setFilename().
LogHandler::__destruct ()
Class destructor
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from _OWL .
References closeLogfile().
Member Function Documentation
LogHandler::__clone ()
Implementation of the __clone() function to prevent cloning of this singleton; it triggers a fatal (user)error
Author
Oscar van Eijk, Oveas Functionality Provider
LogHandler::backtrace ($ _browser_dump = false) [private]
Create a backtrace of the current log item
Parameters
in $_browser_dump Just for OWL development (early days...); when true, the trace is dumped to the browser.
Returns
Trace information of this call.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by log().
_OWL::check (&$ object, $ level = OWL_WARNING) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
in $object Pointer to an object to check against
in $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::reset(), _OWL::setHighSeverity(), and _OWL::traceback().
Referenced by SessionHandler::write().
LogHandler::closeLogfile () [private]
Close the logfile
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by __destruct(), log(), and setApplicLogfile().
LogHandler::composeMessage (&$ msg, $ code) [private]
Compose the logmessage by adding a timestamp and - when not writing multiple files - the run ID
Parameters
in,out $msg Original message by the event
in $code Status code of the message
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get(), Register::getCode(), Register::getRunId(), and _OWL::getSeverity().
Referenced by log().
_OWL::getCallback () [protected, inherited]
Retrieve a previously set (callback) dispatcher. The (callback) dispatcher is cleared immediatly.
Returns
The dispatcher, of null on failure.
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in Dispatcher .
References OWL::factory().
static LogHandler::getInstance () [static]
Return a reference to my implementation. If necessary, create that implementation first.
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References $instance.
_OWL::getLastWarning () [inherited]
Get the last warning or error message.
Returns
null if there was no error (severity below OWL_WARNING), otherwise the error text.
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
_OWL::getSeverity ($ status = null) [inherited]
Get the current object severity level.
Parameters
in $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::$status.
Referenced by composeMessage(), log(), and DataHandler::setKey().
_OWL::getStatus () [final, inherited]
Get the current object status.
Returns
Object's status code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by SchemeHandler::compare().
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory(), and _OWL::setStatus().
Referenced by FormFieldPlugin::__construct(), Tablerow::__construct(), Tablecell::__construct(), Table::__construct(), Document::__construct(), ContainerPlugin::__construct(), Container::__construct(), SocketHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), __construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), OWL::__construct(), Mail::__construct(), Group::__construct(), Form::__construct(), Dispatcher::__construct(), and User::construct().
LogHandler::log ($ msg, $ code)
Log an event signalled by OWL
Parameters
in $msg Message text
in $code Status code of the message
Author
Oscar van Eijk, Oveas Functionality Provider
References backtrace(), closeLogfile(), composeMessage(), ConfigHandler::get(), _OWL::getSeverity(), openLogfile(), and writeLogfile().
LogHandler::logSession (array $ dispatcher, FormHandler $ form = null)
Log the user action in the database. This method is called from the Dispatcher::dispatcher() and can be called moreoften, but only the first log is written.
Parameters
in $dispatcher Array with dispatcher information
in $form Form object
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get(), and OWLCache::get().
LogHandler::openLogfile () [private]
Open the logfile for write
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by __construct(), log(), and setApplicLogfile().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in DbHandler , and SchemeHandler .
References _OWL::resetCalltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::setStatus().
_OWL::restoreStatus () [protected, inherited]
Restore the previously saved status object and destroy the copy
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by User::logout().
_OWL::saveStatus () [protected, inherited]
Create a copy of the status object
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::logout().
LogHandler::setApplicLogfile ()
Find out what the filename of the application specificlogfile should be.
Author
Oscar van Eijk, Oveas Functionality Provider
References closeLogfile(), ConfigHandler::get(), openLogfile(), and setFilename().
_OWL::setCallback ($ _dispatcher) [protected, inherited]
Set a dispatcher for later callback
Parameters
in $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher()
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
_OWL::setCallbackArgument (array $ _arg) [protected, inherited]
Add an argument to a previously registered callback dispatcher
Parameters
in $_arg Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
Referenced by User::register().
LogHandler::setFilename () [private]
Find out what the filename of the logfile should be. When logs are written before the configuration is complete, a temporart startup logfile is created
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get(), and Register::getRunId().
Referenced by __construct(), and setApplicLogfile().
_OWL::setHighSeverity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
_OWL::setStatus ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
in $status OWL status code
in $params
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::getCode(), _OWL::reset(), and _OWL::signal().
Referenced by DbHandler::__clone(), Container::__construct(), SocketHandler::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), Session::__construct(), Mail::__construct(), BaseElement::_getContent(), Mail::addBcc(), Mail::addCc(), Form::addField(), FormFieldRadioPlugin::addOption(), Mail::addTo(), BaseElement::addToContent(), DbHandler::alt(), SchemeHandler::alterScheme(), FileHandler::close(), DbHandler::commitTransaction(), Dispatcher::composeDispatcher(), User::confirm(), SocketHandler::connect(), DbHandler::connect(), DbHandler::create(), SchemeHandler::createScheme(), SchemeHandler::defineIndex(), SchemeHandler::defineScheme(), SocketHandler::disconnect(), Dispatcher::dispatch(), FormHandler::get(), DataHandler::get(), SchemeHandler::getTableColumns(), SchemeHandler::getTableIndexes(), _OWL::init(), Document::loadScript(), Document::loadStyle(), User::login(), FileHandler::open(), DbHandler::open(), openLogfile(), DataHandler::prepare(), DbHandler::prepareDelete(), DbHandler::prepareField(), DbHandler::prepareInsert(), DbHandler::prepareRead(), DbHandler::prepareUpdate(), SocketHandler::read(), DbHandler::read(), FileHandler::readLine(), User::readUserdata(), User::register(), Dispatcher::registerArgument(), Dispatcher::registerCallback(), _OWL::restoreStatus(), DbHandler::rollbackTransaction(), SchemeHandler::scheme(), Mail::send(), FormHandler::set(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), Document::setFavicon(), Form::setFieldAttributes(), Mail::setFrom(), DataHandler::setJoin(), DataHandler::setKey(), FormFieldTextPlugin::setMaxsize(), Document::setMeta(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), Mail::setSender(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), Form::showField(), DbHandler::startTransaction(), SchemeHandler::tableDescription(), SchemeHandler::validateScheme(), SocketHandler::write(), and DbHandler::write().
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
in $level An optional severity level; message will only be displayed when it is at least of this level.
out $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
Referenced by _OWL::getLastWarning(), _OWL::setStatus(), and _OWL::traceback().
_OWL::succeeded ($ _ok = OWL_SUCCESS, &$ _object = null) [inherited]
Check if the object currenlty has a success state
Parameters
in $_ok The highest severity that's considered successfull, default OWL_SUCCESS
in $_object REference to the object to check, defaults to the current object
Returns
Boolean true when successfull
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::construct(), Dispatcher::registerArgument(), and Dispatcher::registerCallback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
out $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
in $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
Referenced by _OWL::check(), User::login(), and SessionHandler::read().
LogHandler::writeLogfile ($ msg) [private]
Write a message to the logfile
Parameters
in $msg The complete log message
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by log().
Member Data Documentation
LogHandler::$dataset = null [private]
Datahandler reference for the session logging in the database
LogHandler::$filename [private]
Name of the logfile
LogHandler::$fpointer [private]
File pointer
LogHandler::$instance [static, private]
integer - self reference
Referenced by getInstance().
LogHandler::$opened [private]
Boolean to keep track of the logfile status
LogHandler::$session_logged = false [private]
Boolean to ensure session data is logged only once per action
_OWL::$severity [protected, inherited]
Severity level of the current object status
Referenced by DbHandler::commitTransaction(), DbHandler::rollbackTransaction(), and DbHandler::startTransaction().
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.loghandler.php