DbHandler Class Reference
Database handler.
Public Member Functions
__destruct ()
__clone ()
alt (array $properties)
forceReread ()
create ()
isOpen ()
open ()
reset ()
tablename ($tablename, $ignore_backticks=false)
setQuery ($qry)
prepareField (array $fielddata)
startTransaction ($name)
commitTransaction ($name, $openNew=false)
rollbackTransaction ($name, $openNew=false)
read ($flag=DBHANDLE_DATA, &$data, $quick_query= '', $line=0, $file= '[unknown]')
tableExists ($tablename)
escapeString ($string)
unescapeString ($string)
prepareRead (array $values=array(), array $tables=array(), array $searches=array(), array $joins=array())
prepareDelete (array $searches=array())
prepareUpdate (array $values=array(), array $searches=array(), array $joins=array())
prepareInsert (array $values=array())
write (&$rows=null, $line=0, $file= '[unknown]')
lastInsertedId ($table=null, $field=null)
close ()
getStatus ()
getSeverity ($status=null)
succeeded ($_ok=OWL_SUCCESS, &$_object=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Static Public Member Functions
static getInstance ()
Protected Member Functions
init ()
setCallback ($_dispatcher)
setCallbackArgument (array $_arg)
getCallback ()
saveStatus ()
restoreStatus ()
check (&$object, $level=OWL_WARNING)
setStatus ($status, $params=array())
setHighSeverity (&$object=null)
Protected Attributes
$severity
Private Member Functions
__construct ($srv= 'localhost', $db= '', $usr= '', $pwd= '', $dbtype= 'MySQL')
loadDriver ()
connect ()
dbread ($qry, &$rows, &$fields)
expandField (&$field, $check_name=false)
tablelist (array $tables)
whereClause (array $searches, array $joins)
updateList (array $updates)
extractTablelist (array $fields)
additionalClauses ()
Private Attributes
$id
$errno
$error
$database
$driver
$use_backticks
$rowcount
$opened
$db_prefix
$query
$ordering
$grouping
$having
$limit
$query_type
$transaction
$cloned
Static Private Attributes
static $instance
static $original_instance
Detailed Description
Database handler.
Handler for all database I/O. This singleton class uses an (abstract) class for the actual storage. This class should not be called directly; it is implemented by class DataHandler
Author
Oscar van Eijk, Oveas Functionality Provider
Version
May 15, 2007 -- O van Eijk -- initial version for Terra-Terra
Jul 29, 2008 -- O van Eijk -- Modified version for OWL
Constructor & Destructor Documentation
DbHandler::__construct ($ srv = 'localhost', $ db = '', $ usr = '', $ pwd = '', $ dbtype = 'MySQL') [private]
Class constructor; opens the database connection.
Parameters
in $srv Database server
in $db Database name
in $usr Username to connect with
in $pwd Password to use for connection
in $dbtype Database type, used to load the driver
References ConfigHandler::get(), _OWL::init(), loadDriver(), and _OWL::setStatus().
DbHandler::__destruct ()
Class destructor; closes the database connection
Reimplemented from _OWL .
References close().
Member Function Documentation
DbHandler::__clone ()
Implementation of the __clone() function. The current connection will be closed, and a property will be set to indicate this is a cloned object. After that, the alt() method can be used to change connection info.
References $instance, close(), reset(), and _OWL::setStatus().
DbHandler::additionalClauses () [private]
Check if additional clauses (like GROUP BY, ORDER BY etc) have been defined, and compose this depending on the query type.
Returns
String with additional clauses
References expandField().
Referenced by prepareDelete(), prepareInsert(), prepareRead(), and prepareUpdate().
DbHandler::alt (array $ properties)
On a cloned database object, set an alternative, prefix or connection.
Parameters
in $properties An indexed array with the properties that should be changed. Supported are:
prefix : The table prefix
server : Database server
name : Database name
username : Username to connect with
password : Password to use for connection
dbdriver : Database type (reserved for future use, currently only MySQL is implemented)
References loadDriver(), open(), and _OWL::setStatus().
_OWL::check (&$ object, $ level = OWL_WARNING) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
in $object Pointer to an object to check against
in $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
References _OWL::reset(), _OWL::setHighSeverity(), and _OWL::traceback().
Referenced by SessionHandler::write().
DbHandler::close ()
Close the database and disconnect from the server. This function is called on program shutdown. Although the database will be closed already by PHP, this function might be called at any time manually; is also updates the 'opened' variable.
Referenced by __clone(), __destruct(), create(), and forceReread().
DbHandler::commitTransaction ($ name, $ openNew = false)
Commit database transaction
Parameters
in $name Transaction name (reserverd for future use)
in $openNew Boolean set to true when a new transaction must be opened immediately
Returns
Object severity status
References _OWL::$severity, and _OWL::setStatus().
DbHandler::connect () [private]
Connect to the database server
Returns
True on success, otherwise False
References ConfigHandler::get(), and _OWL::setStatus().
Referenced by create(), and open().
DbHandler::create ()
Create a new database
Returns
Severity level
References close(), connect(), and _OWL::setStatus().
DbHandler::dbread ($ qry, &$ rows, &$ fields) [private]
Read from the database.
Parameters
in $qry Database query string.
out $rows Number of rows matched
out $fields Number of fields per row
Returns
A 2D array with all data, or false on failures
Referenced by read().
DbHandler::escapeString ($ string)
Call the current DBtype's escape function for character strings.
Parameters
$string The string that should be escaped
Returns
The escaped string
DbHandler::expandField (&$ field, $ check_name = false) [private]
Change a fieldname in the format 'table#field' to the format '`[prefix]table.field`' The fieldname can have additional #-seperated elements, which contain the method from the database driver and its arguments (that will be passed as an array)
Parameters
in,out $field Fieldname to expand
in $check_name Boolean which is true if the fieldname should be returned with 'AS'. Default is false
References tablename().
Referenced by additionalClauses(), prepareInsert(), prepareRead(), updateList(), and whereClause().
DbHandler::extractTablelist (array $ fields) [private]
Create an array with unique tablenames as extracted from an array of fields in the format (table::field => value, ...)
Parameters
in $fields An array with fields
Returns
Array with tablenames
References $_table.
Referenced by prepareDelete(), prepareInsert(), and prepareUpdate().
DbHandler::forceReread ()
Hmmm.... we need this method as the result of a race condition; if an alternative database (clone) is opened first, that's the default connection, which is probably the case in most situation since the owl config table is read early in the init phase. I need to think about it... is this solution acceptable? So we need something smarter here? This method is allowed to be called only once by OWLLoader; maybe some checks?
References close(), ConfigHandler::get(), loadDriver(), and open().
_OWL::getCallback () [protected, inherited]
Retrieve a previously set (callback) dispatcher. The (callback) dispatcher is cleared immediatly.
Returns
The dispatcher, of null on failure.
Reimplemented in Dispatcher .
References OWL::factory().
static DbHandler::getInstance () [static]
Return a reference to my implementation. If necessary, create that implementation first.
Returns
Object instance ID
References $instance, $original_instance, and ConfigHandler::get().
_OWL::getSeverity ($ status = null) [inherited]
Get the current object severity level.
Parameters
in $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
References _OWL::$status.
Referenced by LogHandler::composeMessage(), LogHandler::log(), and DataHandler::setKey().
_OWL::getStatus () [final, inherited]
Get the current object status.
Returns
Object's status code
Referenced by SchemeHandler::compare().
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
References OWL::factory(), and _OWL::setStatus().
Referenced by FormFieldPlugin::__construct(), Tablerow::__construct(), Tablecell::__construct(), Table::__construct(), Document::__construct(), ContainerPlugin::__construct(), Container::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), __construct(), DataHandler::__construct(), OWL::__construct(), Group::__construct(), Form::__construct(), Dispatcher::__construct(), and User::construct().
DbHandler::isOpen ()
Let other objects check if th database connection is opened
Returns
boolean, True when opened
DbHandler::lastInsertedId ($ table = null, $ field = null)
Return the last ID after a newly inserted record holding an AUTO_INCREMENT field
Parameters
in $table Table name holding the auto increment field
in $field Name of the auto increment field
Returns
The number that was last inserted
DbHandler::loadDriver () [private]
Create a new instance of the database driver
References OWLloader::getDriver(), and toStrictBoolean().
Referenced by __construct(), alt(), and forceReread().
DbHandler::open ()
Opens the database connection.
Returns
Severity level
References connect(), and _OWL::setStatus().
Referenced by alt(), forceReread(), and read().
DbHandler::prepareDelete (array $ searches = array())
Prepare a delete query. Data is taken from the arrays that are passed to this function. All fieldnames are in the format 'table#field', where the table is not yet prefixed.
Parameters
in $searches Given values that have to match
Returns
Severity level
References additionalClauses(), extractTablelist(), _OWL::setStatus(), tablelist(), and whereClause().
DbHandler::prepareField (array $ fielddata)
Prepare a field for use in the upconimg query using the array as set by DbHandler::set(). Internal arrays are filled with grouping data, ordering data etc. if required.,
Parameters
in $fielddata Array with a description of the field,
See also
DbHandler::set()
Returns
An array with two elements: the fieldname in the format that will be handled by DbHandler::expandField(), and the value which might be a normal value, an array of values of a value as set by a driver function (using database functions). On errors, null is returned.
References _OWL::setStatus().
DbHandler::prepareInsert (array $ values = array())
Prepare an insert query. Data is taken from the arrays that are passed to this function. All fieldnames are in the format 'table#field', where the table is not yet prefixed.
Parameters
in $values Given database values
Returns
Severity level
References additionalClauses(), expandField(), extractTablelist(), _OWL::setStatus(), and tablename().
DbHandler::prepareRead (array $ values = array(), array $ tables = array(), array $ searches = array(), array $ joins = array())
Prepare a read query. Data is taken from the arrays that are passed to this function. All fieldnames are in the format 'table#field', where the table is not yet prefixed.
Parameters
in $values Values that will be read
in $tables Tables from which will be read
in $searches Given values that have to match
in $joins Joins on the given tables
Returns
Severity level
References additionalClauses(), expandField(), _OWL::setStatus(), tablelist(), and whereClause().
DbHandler::prepareUpdate (array $ values = array(), array $ searches = array(), array $ joins = array())
Prepare an update query. Data is taken from the arrays that are passed to this function. All fieldnames are in the format 'table#field', where the table is not yet prefixed.
Parameters
in $values Given database values
in $searches List of fieldnames that will be used in the where clause. All fields not in this array will be updated!
in $joins Joins on the given tables
Returns
Severity level
References additionalClauses(), extractTablelist(), _OWL::setStatus(), tablelist(), updateList(), and whereClause().
DbHandler::read ($ flag = DBHANDLE_DATA, &$ data, $ quick_query = '', $ line = 0, $ file = '[unknown]')
Read from the database. The return value depends on the flag. By default, the selected rows(s) are returned in a 2d array.
Parameters
in $flag Flag that identifies how data should be returned; as data (default) or the number of rows
out $data The retrieved value in a format depending on the flag:
DBHANDLE_ROWCOUNT; Number of matching rows
DBHANDLE_FIELDCOUNT; Number of fields per rows
DBHANDLE_TOTALFIELDCOUNT; Total number op fields
DBHANDLE_DATA (default); A 2D array with all data
DBHANDLE_SINGLEROW; The first matching row in a 1D array
DBHANDLE_SINGLEFIELD; The first matching field
in $quick_query Database query string. If empty, $this->query is used
in $line Line number of this call
in $file File that made the call to this method
Returns
Severity level
References dbread(), open(), and _OWL::setStatus().
DbHandler::reset ()
Reset the object
Reimplemented from _OWL .
Referenced by __clone().
_OWL::restoreStatus () [protected, inherited]
Restore the previously saved status object and destroy the copy
References _OWL::setStatus().
Referenced by User::logout().
DbHandler::rollbackTransaction ($ name, $ openNew = false)
Rollback the current transaction
Parameters
in $name Transaction name (reserverd for future use)
in $openNew Boolean set to true when a new transaction must be opened immediately
Returns
Object severity status
References _OWL::$severity, and _OWL::setStatus().
_OWL::saveStatus () [protected, inherited]
Create a copy of the status object
Referenced by User::logout().
_OWL::setCallback ($ _dispatcher) [protected, inherited]
Set a dispatcher for later callback
Parameters
in $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher()
Returns
True on success, false on failure
References OWL::factory().
_OWL::setCallbackArgument (array $ _arg) [protected, inherited]
Add an argument to a previously registered callback dispatcher
Parameters
in $_arg Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
References OWL::factory().
Referenced by User::register().
_OWL::setHighSeverity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
DbHandler::setQuery ($ qry)
Set the database query. This function should only be used if the query is too complex to be set with any of the prepare() functions.
Parameters
in $qry A complete database query. All tablenames must be prefixed (with the tablename() function)!
_OWL::setStatus ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
in $status OWL status code
in $params
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::getCode(), _OWL::reset(), and _OWL::signal().
Referenced by __clone(), Container::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), __construct(), DataHandler::__construct(), Session::__construct(), BaseElement::_getContent(), Form::addField(), FormFieldRadioPlugin::addOption(), BaseElement::addToContent(), alt(), SchemeHandler::alterScheme(), FileHandler::close(), commitTransaction(), Dispatcher::composeDispatcher(), User::confirm(), connect(), create(), SchemeHandler::createScheme(), SchemeHandler::defineIndex(), SchemeHandler::defineScheme(), Dispatcher::dispatch(), FormHandler::get(), DataHandler::get(), SchemeHandler::getTableColumns(), SchemeHandler::getTableIndexes(), _OWL::init(), Document::loadScript(), Document::loadStyle(), User::login(), FileHandler::open(), open(), LogHandler::openLogfile(), DataHandler::prepare(), prepareDelete(), prepareField(), prepareInsert(), prepareRead(), prepareUpdate(), read(), FileHandler::readLine(), User::readUserdata(), User::register(), Dispatcher::registerArgument(), Dispatcher::registerCallback(), _OWL::restoreStatus(), rollbackTransaction(), SchemeHandler::scheme(), FormHandler::set(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), Document::setFavicon(), Form::setFieldAttributes(), DataHandler::setJoin(), DataHandler::setKey(), FormFieldTextPlugin::setMaxsize(), Document::setMeta(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), Form::showField(), startTransaction(), SchemeHandler::tableDescription(), SchemeHandler::validateScheme(), and write().
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
in $level An optional severity level; message will only be displayed when it is at least of this level.
out $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
References ConfigHandler::get().
Referenced by _OWL::setStatus(), and _OWL::traceback().
DbHandler::startTransaction ($ name)
Start a new database transaction
Parameters
in $name Transaction name (reserverd for future use)
Returns
Object severity status
References _OWL::$severity, and _OWL::setStatus().
_OWL::succeeded ($ _ok = OWL_SUCCESS, &$ _object = null) [inherited]
Check if the object currenlty has a success state
Parameters
in $_ok The highest severity that's considered successfull, default OWL_SUCCESS
in $_object REference to the object to check, defaults to the current object
Returns
Boolean true when successfull
Referenced by User::construct(), Dispatcher::registerArgument(), and Dispatcher::registerCallback().
DbHandler::tableExists ($ tablename)
Check if a table exists in the database
Parameters
in $tablename Name of the table to check
Returns
True of the table exists
References tablename().
DbHandler::tablelist (array $ tables) [private]
Create a list with tables, including prefixes, that can be interpreted by SQL
Parameters
in $tables An array with tablenames
Returns
The tablelist
References $_table, and tablename().
Referenced by prepareDelete(), prepareRead(), and prepareUpdate().
DbHandler::tablename ($ tablename, $ ignore_backticks = false)
Extend a tablename with the database prefix
Parameters
in $tablename Table name to extend
in $ignore_backticks Boolean to suppress backticks if set, default false
Returns
Extended table name
Referenced by expandField(), prepareInsert(), tableExists(), and tablelist().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
out $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
in $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
References _OWL::signal().
Referenced by _OWL::check(), User::login(), and SessionHandler::read().
DbHandler::unescapeString ($ string)
Call the current DBtype's unescape function for character strings.
Parameters
$string The string that should be unescaped
Returns
The unescaped string
DbHandler::updateList (array $ updates) [private]
Create a string with 'field = value, ...' combinations in SQL format
Parameters
in $updates Array with fields to update (fieldname => values)
Returns
The UPDATE statement
References expandField().
Referenced by prepareUpdate().
DbHandler::whereClause (array $ searches, array $ joins) [private]
Create a WHERE clause that can be interpreted by SQL
Parameters
in $searches Array with values (fieldname => values) Values can be an array in which case more ORs for that field will be added to the where clause
in $joins Array of arrays with values (field, linktype, field)
Returns
The WHERE clause
References expandField().
Referenced by prepareDelete(), prepareRead(), and prepareUpdate().
DbHandler::write (&$ rows = null, $ line = 0, $ file = '[unknown]')
Database inserts and updates. The number of affected rows is stored in $this->rowcount
Parameters
out $rows (optional) The number of affected rows
in $line Line number of this call
in $file File that made the call to this method
Returns
Severity level
References _OWL::setStatus().
Member Data Documentation
DbHandler::$cloned [private]
boolean - true when the object has been cloned
DbHandler::$database [private]
array - Database location and authorization indo
DbHandler::$db_prefix [private]
string - database prefix
DbHandler::$driver [private]
object - The database driver
DbHandler::$errno [private]
integer - Error ID
DbHandler::$error [private]
string - Error text
DbHandler::$grouping [private]
array - list of fields for a GROUP BY clause
DbHandler::$having [private]
array - list of fields for a HAVING clause
DbHandler::$id [private]
integer - DB Handle ID
DbHandler::$instance [static, private]
integer - self reference
Referenced by __clone(), and getInstance().
DbHandler::$limit [private]
array with 2 elements to limit the query
Todo this ain't implemented yet
DbHandler::$opened [private]
boolean - True if the database is opened
DbHandler::$ordering [private]
array - list of fields for an ORDER BY clasue
DbHandler::$original_instance [static, private]
integer - self reference to the original object before cloning
Referenced by getInstance().
DbHandler::$query [private]
string - Query string
DbHandler::$query_type [private]
string - Prepared query type
DbHandler::$rowcount [private]
integer - Row counter
_OWL::$severity [protected, inherited]
Severity level of the current object status
Referenced by commitTransaction(), rollbackTransaction(), and startTransaction().
DbHandler::$transaction [private]
string - name of the open transaction (currently just used as a boolean)
DbHandler::$use_backticks [private]
boolean - true when Backticks should be used in the queries, this can be defined in the driver using the constant USE_BACKTICKS. Default is false
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.dbhandler.php