OldOFMStuff Class Reference
Public Member Functions
OFM_FileDetails ($Path, $File)
OFM_FileInfo ($Path, $File)
OFM_IsAscii ($File, $Type)
Member Function Documentation
OldOFMStuff::OFM_FileDetails ($ Path, $ File)
References OFM_FileInfo().
OldOFMStuff::OFM_FileInfo ($ Path, $ File)
References OFM_IsAscii().
Referenced by OFM_FileDetails().
OldOFMStuff::OFM_IsAscii ($ File, $ Type)
Referenced by OFM_FileInfo().
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.filehandler.php