FormElement Class Reference
Form element.
Public Member Functions
__construct ()
addField ($type, $name, $value= '', $attributes=array())
setFieldAttributes ($index, $attributes)
openForm ()
closeForm ()
setId ($_value)
setClass ($_value)
get_status ()
get_severity ($status=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Protected Member Functions
getAttributes ()
init ()
reset ()
check (&$object, $level)
set_status ($status, $params=array())
set_high_severity (&$object=null)
Protected Attributes
$class = ''
$style = ''
$id = ''
$severity
Private Attributes
$fields
Detailed Description
Form element. Form element
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Aug 29, 2008 -- O van Eijk -- initial version
Constructor & Destructor Documentation
FormElement::__construct ()
Class constructor;
Member Function Documentation
FormElement::addField ($ type, $ name, $ value = '', $ attributes = array())
Add a formfield to the formelement
Parameters
$\leftarrow$ $type Field type
Returns
integer Internal index of the form field object
References $_index, OWLloader::getClass(), _OWL::set_status(), and setFieldAttributes().
_OWL::check (&$ object, $ level) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
$\leftarrow$ $object Pointer to an object to check against
$\leftarrow$ $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
References _OWL::reset(), _OWL::set_high_severity(), and _OWL::traceback().
Referenced by SessionHandler::write().
FormElement::closeForm ()
_OWL::get_severity ($ status = null) [inherited]
Get the current object severity level.
Parameters
$\leftarrow$ $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
References _OWL::$status.
Referenced by LogHandler::compose_message(), LogHandler::log(), and DataHandler::set_key().
_OWL::get_status () [final, inherited]
Get the current object status.
Returns
Object's status code
Referenced by FormHandler::__get(), and SchemeHandler::compare().
DOMElement::getAttributes () [protected, inherited]
Return the general element attributes that are set
Returns
string attributes in HTML format (' fld=`value`...)
Referenced by openForm().
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
References OWL::factory().
Referenced by UserHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), OWL::__construct(), and DataHandler::DataHandler().
FormElement::openForm ()
References DOMElement::getAttributes().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Reimplemented in DbHandler, and SchemeHandler.
References _OWL::reset_calltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::set_status().
_OWL::set_high_severity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
_OWL::set_status ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
$\leftarrow$ $status OWL status code
$\leftarrow$ $params
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::get_code(), _OWL::reset(), and _OWL::signal().
Referenced by UserHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), FormHandler::__get(), DataHandler::__get(), DataHandler::__set(), addField(), SchemeHandler::alter_scheme(), FileHandler::close(), DbHandler::connect(), DbHandler::create(), SchemeHandler::create_scheme(), DataHandler::DataHandler(), SchemeHandler::define_index(), SchemeHandler::define_scheme(), SchemeHandler::get_table_columns(), SchemeHandler::get_table_indexes(), UserHandler::login(), FileHandler::open(), DbHandler::open(), LogHandler::open_logfile(), FormHandler::parse_formdata(), DataHandler::prepare(), DbHandler::prepare_delete(), DbHandler::prepare_insert(), DbHandler::prepare_read(), DbHandler::prepare_update(), DbHandler::read(), FileHandler::read_line(), UserHandler::read_userdata(), DataHandler::reset(), SchemeHandler::scheme(), DataHandler::set_join(), DataHandler::set_key(), setFieldAttributes(), SchemeHandler::table_description(), SchemeHandler::validate_scheme(), and DbHandler::write().
DOMElement::setClass ($ _value) [inherited]
Set the element Class
Parameters
$\leftarrow$ $_value Class name
FormElement::setFieldAttributes ($ index, $ attributes)
Set one or more formfield attributes
Parameters
$\leftarrow$ $index Index of the fieldobject
$\leftarrow$ $attributes array with object name and values in the format ('attrib' => 'value')
References _OWL::set_status().
Referenced by addField().
DOMElement::setId ($ _value) [inherited]
Set the element ID
Parameters
$\leftarrow$ $_value Identification
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
$\leftarrow$ $level An optional severity level; message will only be displayed when it is at least of this level.
$\rightarrow$ $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
References ConfigHandler::get().
Referenced by _OWL::set_status(), and _OWL::traceback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
$\rightarrow$ $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
$\leftarrow$ $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
References _OWL::signal().
Referenced by _OWL::check(), UserHandler::login(), and SessionHandler::read().
Member Data Documentation
DOMElement::$class = '' [protected, inherited]
Class specification
FormElement::$fields [private]
Array holding all field objects
DOMElement::$id = '' [protected, inherited]
Element ID
_OWL::$severity [protected, inherited]
Severity level of the current object status
DOMElement::$style = '' [protected, inherited]
Element style
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/ui/class.formelement.php