Session Class Reference
the OWL-PHP session object
Public Member Functions
__construct ()
__destruct ()
newSession ()
setRights ($bitmap, $app=OWL_ID)
hasRight ($bit, $appl)
setSessionVar ($var, $val=0, $flg=SESSIONVAR_SET)
getSessionVar ($var, $default=null)
open ()
close ()
read ($id)
write ($id, $data)
destroy ($id)
gc ($lifetime)
getLastWarning ()
getStatus ()
getSeverity ($status=null)
succeeded ($_ok=OWL_SUCCESS, &$_object=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Protected Member Functions
init ()
setCallback ($_dispatcher)
setCallbackArgument (array $_arg)
getCallback ()
reset ()
saveStatus ()
restoreStatus ()
check (&$object, $level=OWL_WARNING)
setStatus ($status, $params=array())
setHighSeverity (&$object=null)
Protected Attributes
$dataset = null
$severity
Private Member Functions
restoreSession ()
saveSession ()
ipAddress ()
Private Attributes
$rights
Detailed Description
the OWL-PHP session object
This class handles the OWL session
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Aug 13, 2008 -- O van Eijk -- initial version
Constructor & Destructor Documentation
Session::__construct ()
When a new run is initialised, restore an older session or create a new one
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from SessionHandler .
References ConfigHandler::get(), getSessionVar(), ipAddress(), newSession(), restoreSession(), setSessionVar(), and _OWL::setStatus().
Session::__destruct ()
When a run ends, write the sessiondata
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from SessionHandler .
References saveSession().
Member Function Documentation
_OWL::check (&$ object, $ level = OWL_WARNING) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
in $object Pointer to an object to check against
in $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::reset(), _OWL::setHighSeverity(), and _OWL::traceback().
Referenced by SessionHandler::write().
SessionHandler::close () [inherited]
Close the session
Returns
bool
Author
Oscar van Eijk, Oveas Functionality Provider
SessionHandler::destroy ($ id) [inherited]
Destroy a session
Parameters
in $id ID of the session to destroy
Returns
Boolean indicating success (true) or failure (false)
Author
Oscar van Eijk, Oveas Functionality Provider
SessionHandler::gc ($ lifetime) [inherited]
Garbage Collector. By default, this has a 1% change of being executed (session.gc_probability/session.gc_divisor). The values can be changed in the constructor.
Parameters
in $lifetime Session lifetime in seconds. By default, 1440 seconds. This can be changed in the constructor
Returns
Status code
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::getCallback () [protected, inherited]
Retrieve a previously set (callback) dispatcher. The (callback) dispatcher is cleared immediatly.
Returns
The dispatcher, of null on failure.
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in Dispatcher .
References OWL::factory().
_OWL::getLastWarning () [inherited]
Get the last warning or error message.
Returns
null if there was no error (severity below OWL_WARNING), otherwise the error text.
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
Session::getSessionVar ($ var, $ default = null)
Get a session variable
Parameters
in $var Variable name
in $default Default value to return if the variable was not set (default null)
Returns
The value from the session, null if not set
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by __construct(), and restoreSession().
_OWL::getSeverity ($ status = null) [inherited]
Get the current object severity level.
Parameters
in $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::$status.
Referenced by LogHandler::composeMessage(), LogHandler::log(), and DataHandler::setKey().
_OWL::getStatus () [final, inherited]
Get the current object status.
Returns
Object's status code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by SchemeHandler::compare().
Session::hasRight ($ bit, $ appl)
Check if a rightsbit has been set for this session
Parameters
in $bit Rightsbit to check
in $appl ID of the application the bit belongs to
Returns
Boolean; true when the bit is set
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory(), and _OWL::setStatus().
Referenced by FormFieldPlugin::__construct(), Tablerow::__construct(), Tablecell::__construct(), Table::__construct(), Document::__construct(), ContainerPlugin::__construct(), Container::__construct(), SocketHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), HDataHandler::__construct(), DataHandler::__construct(), OWL::__construct(), Mail::__construct(), Group::__construct(), Form::__construct(), Dispatcher::__construct(), and User::construct().
Session::ipAddress () [private]
Identify the clients IP address where the client can use a shared internet source (HTTP_CLIENT_IP), a proxy server (HTTP_X_FORWARDED_FOR) is direct access (REMOTE_ADDR)
Returns
The IP address, or 0.0.0.0 when none was found
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by __construct(), and newSession().
Session::newSession ()
Initialize a session
Author
Oscar van Eijk, Oveas Functionality Provider
References ipAddress(), and setSessionVar().
Referenced by __construct().
SessionHandler::open () [inherited]
Open the session
Returns
bool
Author
Oscar van Eijk, Oveas Functionality Provider
SessionHandler::read ($ id) [inherited]
Read the session
Parameters
in $id session id
Returns
Session data or null when not found
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::reset(), _OWL::setHighSeverity(), and _OWL::traceback().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in DbHandler , and SchemeHandler .
References _OWL::resetCalltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::setStatus().
Session::restoreSession () [private]
Restore a session environment
Author
Oscar van Eijk, Oveas Functionality Provider
References getSessionVar().
Referenced by __construct().
_OWL::restoreStatus () [protected, inherited]
Restore the previously saved status object and destroy the copy
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by User::logout().
Session::saveSession () [private]
Save active data to the session environment
Author
Oscar van Eijk, Oveas Functionality Provider
References setSessionVar().
Referenced by __destruct().
_OWL::saveStatus () [protected, inherited]
Create a copy of the status object
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::logout().
_OWL::setCallback ($ _dispatcher) [protected, inherited]
Set a dispatcher for later callback
Parameters
in $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher()
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
_OWL::setCallbackArgument (array $ _arg) [protected, inherited]
Add an argument to a previously registered callback dispatcher
Parameters
in $_arg Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
Referenced by User::register().
_OWL::setHighSeverity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
Session::setRights ($ bitmap, $ app = OWL_ID)
Set the default right bitmap for this session
Parameters
in $bitmap The bitmap value which is either the default group value, or the complete list of rights for this user (depending on the configuration)
in $app Application ID
Author
Oscar van Eijk, Oveas Functionality Provider
Session::setSessionVar ($ var, $ val = 0, $ flg = SESSIONVAR_SET)
Set a session variable
Parameters
in $var Variable name
in $val Variable value (default 0)
in $flg How to handle the value. Default SESSIONVAR_SET
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by __construct(), newSession(), and saveSession().
_OWL::setStatus ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
in $status OWL status code
in $params
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::getCode(), _OWL::reset(), and _OWL::signal().
Referenced by DbHandler::__clone(), Container::__construct(), SocketHandler::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), __construct(), Mail::__construct(), BaseElement::_getContent(), Mail::addBcc(), Mail::addCc(), Form::addField(), FormFieldRadioPlugin::addOption(), Mail::addTo(), BaseElement::addToContent(), DbHandler::alt(), SchemeHandler::alterScheme(), FileHandler::close(), DbHandler::commitTransaction(), Dispatcher::composeDispatcher(), User::confirm(), SocketHandler::connect(), DbHandler::connect(), DbHandler::create(), SchemeHandler::createScheme(), SchemeHandler::defineIndex(), SchemeHandler::defineScheme(), SocketHandler::disconnect(), Dispatcher::dispatch(), FormHandler::get(), DataHandler::get(), SchemeHandler::getTableColumns(), SchemeHandler::getTableIndexes(), _OWL::init(), Document::loadScript(), Document::loadStyle(), DbHandler::lockTable(), User::login(), FileHandler::open(), DbHandler::open(), LogHandler::openLogfile(), DataHandler::prepare(), DbHandler::prepareDelete(), DbHandler::prepareField(), DbHandler::prepareInsert(), DbHandler::prepareRead(), DbHandler::prepareUpdate(), SocketHandler::read(), DbHandler::read(), FileHandler::readLine(), HDataHandler::readQuery(), User::readUserdata(), User::register(), Dispatcher::registerArgument(), Dispatcher::registerCallback(), _OWL::restoreStatus(), DbHandler::rollbackTransaction(), SchemeHandler::scheme(), Mail::send(), FormHandler::set(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), Document::setFavicon(), Form::setFieldAttributes(), Mail::setFrom(), DataHandler::setJoin(), DataHandler::setKey(), FormFieldTextPlugin::setMaxsize(), Document::setMeta(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), Mail::setSender(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), Form::showField(), DbHandler::startTransaction(), SchemeHandler::tableDescription(), DbHandler::unlockTable(), SchemeHandler::validateScheme(), SocketHandler::write(), and DbHandler::write().
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
in $level An optional severity level; message will only be displayed when it is at least of this level.
out $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
Referenced by _OWL::getLastWarning(), _OWL::setStatus(), and _OWL::traceback().
_OWL::succeeded ($ _ok = OWL_SUCCESS, &$ _object = null) [inherited]
Check if the object currenlty has a success state
Parameters
in $_ok The highest severity that's considered successfull, default OWL_SUCCESS
in $_object REference to the object to check, defaults to the current object
Returns
Boolean true when successfull
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::construct(), Dispatcher::registerArgument(), and Dispatcher::registerCallback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
out $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
in $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
Referenced by _OWL::check(), User::login(), and SessionHandler::read().
SessionHandler::write ($ id, $ data) [inherited]
Write the session
Parameters
in $id Session id
in $data Session data
Returns
True on success, Failure otherwise
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::check().
Member Data Documentation
SessionHandler::$dataset = null [protected, inherited]
Link to a datahandler object. This dataset is used as an interface to all database IO.
Session::$rights [private]
Right object holding the currently active right for this session
_OWL::$severity [protected, inherited]
Severity level of the current object status
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/bo/class.session.php