Dispatcher Class Reference
Dispatcher singleton.
Public Member Functions
__clone ()
composeDispatcher ($_dispatcher)
dispatch ($_dispatcher=null)
registerCallback ($_dispatcher)
registerArgument (array $_argument)
getCallback ()
getLastWarning ()
getStatus ()
getSeverity ($status=null)
succeeded ($_ok=OWL_SUCCESS, &$_object=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Static Public Member Functions
static getInstance ()
Protected Member Functions
init ()
setCallback ($_dispatcher)
setCallbackArgument (array $_arg)
reset ()
saveStatus ()
restoreStatus ()
check (&$object, $level=OWL_WARNING)
setStatus ($status, $params=array())
setHighSeverity (&$object=null)
Protected Attributes
$severity
Private Member Functions
__construct ()
decodeDispatcher ($_dispatcher)
Private Attributes
$dispatcher
Static Private Attributes
static $instance
Detailed Description
Dispatcher singleton.
Define the dispatcher. This class calls the proper method based in the request or form data
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Nov 23, 2010 -- O van Eijk -- initial version
Constructor & Destructor Documentation
Dispatcher::__construct () [private]
Constructor
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::init().
Member Function Documentation
Dispatcher::__clone ()
Implementation of the __clone() function to prevent cloning of this singleton; it triggers a fatal (user)error
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::check (&$ object, $ level = OWL_WARNING) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
in $object Pointer to an object to check against
in $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::reset(), _OWL::setHighSeverity(), and _OWL::traceback().
Referenced by SessionHandler::write().
Dispatcher::composeDispatcher ($ _dispatcher)
Translate a given dispatcher to the URL encoded format
Parameters
in $_dispatcher Dispatcher as an indexed array with the following keys:
application: Name of the application. When the include path is no constant, it must be equal to the name of the directory directly under the server's document root.
include_path: A path relative from the application toplevel, or a constant
class_file: Filename, this can be the full file name (`class.myclass.php`) or just the name (`myclass`). When omitted, it defaults to the classname (e.g. `MyClass`) in lowercase.
class_name Name of the class.
method_name: Method that will be called when the form is submitted.
argument: An optional argument for the method called. The method which is called by the dispatcher must accept this argument type. If ommitted, no arguments will be passed by the dispatcher For short, a string in the format `application#include_path-path#class_file#class_name#method_name[#argument]` may also be given.
Returns
URL encoded dispatcher
Author
Oscar van Eijk, Oveas Functionality Provider
References owlCrypt(), and _OWL::setStatus().
Referenced by registerArgument(), and registerCallback().
Dispatcher::decodeDispatcher ($ _dispatcher) [private]
Check the format a a dispatcher and decode it
Parameters
in $_dispatcher Dispatcher
Returns
Dispatcher as an indexed array
Author
Oscar van Eijk, Oveas Functionality Provider
References owlCrypt().
Referenced by dispatch(), and registerArgument().
Dispatcher::dispatch ($ _dispatcher = null)
Get the dispatcher info from the formdata, load the specified classfile and call the method specified.
Parameters
in $_dispatcher An optional dispatcher can be given (
See also
Dispatcher::composeDispatcher() for the format). When omitted, the dispatcher will be taken from the formdata.
Returns
On errors during dispatch, the severity level, otherwise the return value of the given method
Author
Oscar van Eijk, Oveas Functionality Provider
References $_form, decodeDispatcher(), OWL::factory(), OWLloader::getClass(), and _OWL::setStatus().
Dispatcher::getCallback ()
Retrieve a previously set (callback) dispatcher. The (callback) dispatcher is cleared immediatly.
Returns
The dispatcher, or null when no dispatched was registered
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from _OWL .
static Dispatcher::getInstance () [static]
Return a reference to my implementation. If necessary, create that implementation first.
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References $instance.
_OWL::getLastWarning () [inherited]
Get the last warning or error message.
Returns
null if there was no error (severity below OWL_WARNING), otherwise the error text.
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
_OWL::getSeverity ($ status = null) [inherited]
Get the current object severity level.
Parameters
in $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::$status.
Referenced by LogHandler::composeMessage(), LogHandler::log(), and DataHandler::setKey().
_OWL::getStatus () [final, inherited]
Get the current object status.
Returns
Object's status code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by SchemeHandler::compare().
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory(), and _OWL::setStatus().
Referenced by FormFieldPlugin::__construct(), Tablerow::__construct(), Tablecell::__construct(), Table::__construct(), Document::__construct(), ContainerPlugin::__construct(), Container::__construct(), SocketHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), HDataHandler::__construct(), DataHandler::__construct(), OWL::__construct(), Mail::__construct(), Group::__construct(), Form::__construct(), __construct(), and User::construct().
Dispatcher::registerArgument (array $ _argument)
Add an argument to a previously registered callback dispatcher
Parameters
in $_argument Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References composeDispatcher(), decodeDispatcher(), _OWL::setStatus(), and _OWL::succeeded().
Dispatcher::registerCallback ($ _dispatcher)
Register a callback that wal later be retrieved as dispatcher
Parameters
in $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher() for the format
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References composeDispatcher(), _OWL::setStatus(), and _OWL::succeeded().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in DbHandler , and SchemeHandler .
References _OWL::resetCalltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::setStatus().
_OWL::restoreStatus () [protected, inherited]
Restore the previously saved status object and destroy the copy
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by User::logout().
_OWL::saveStatus () [protected, inherited]
Create a copy of the status object
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::logout().
_OWL::setCallback ($ _dispatcher) [protected, inherited]
Set a dispatcher for later callback
Parameters
in $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher()
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
_OWL::setCallbackArgument (array $ _arg) [protected, inherited]
Add an argument to a previously registered callback dispatcher
Parameters
in $_arg Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
Referenced by User::register().
_OWL::setHighSeverity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
_OWL::setStatus ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
in $status OWL status code
in $params
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::getCode(), _OWL::reset(), and _OWL::signal().
Referenced by DbHandler::__clone(), Container::__construct(), SocketHandler::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), Session::__construct(), Mail::__construct(), BaseElement::_getContent(), HDataHandler::_getNewLeft(), Mail::addBcc(), Mail::addCc(), Form::addField(), FormFieldRadioPlugin::addOption(), HDataHandler::addParent(), Mail::addTo(), BaseElement::addToContent(), DbHandler::alt(), SchemeHandler::alterScheme(), FileHandler::close(), DbHandler::commitTransaction(), composeDispatcher(), User::confirm(), SocketHandler::connect(), DbHandler::connect(), DbHandler::create(), SchemeHandler::createScheme(), SchemeHandler::defineIndex(), SchemeHandler::defineScheme(), SocketHandler::disconnect(), dispatch(), HDataHandler::enableCrossLink(), FormHandler::get(), DataHandler::get(), HDataHandler::getDirectChildren(), HDataHandler::getFullOffspring(), SchemeHandler::getTableColumns(), SchemeHandler::getTableIndexes(), _OWL::init(), Document::loadScript(), Document::loadStyle(), DbHandler::lockTable(), User::login(), HDataHandler::moveNode(), FileHandler::open(), DbHandler::open(), LogHandler::openLogfile(), DataHandler::prepare(), DbHandler::prepareDelete(), DbHandler::prepareField(), DbHandler::prepareInsert(), DbHandler::prepareRead(), DbHandler::prepareUpdate(), SocketHandler::read(), DbHandler::read(), FileHandler::readLine(), HDataHandler::readQuery(), User::readUserdata(), User::register(), registerArgument(), registerCallback(), _OWL::restoreStatus(), DbHandler::rollbackTransaction(), SchemeHandler::scheme(), Mail::send(), FormHandler::set(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), Document::setFavicon(), Form::setFieldAttributes(), Mail::setFrom(), DataHandler::setJoin(), DataHandler::setKey(), FormFieldTextPlugin::setMaxsize(), Document::setMeta(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), Mail::setSender(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), Form::showField(), DbHandler::startTransaction(), SchemeHandler::tableDescription(), DbHandler::unlockTable(), SchemeHandler::validateScheme(), SocketHandler::write(), DbHandler::write(), and HDataHandler::writeQuery().
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
in $level An optional severity level; message will only be displayed when it is at least of this level.
out $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
Referenced by _OWL::getLastWarning(), _OWL::setStatus(), and _OWL::traceback().
_OWL::succeeded ($ _ok = OWL_SUCCESS, &$ _object = null) [inherited]
Check if the object currenlty has a success state
Parameters
in $_ok The highest severity that's considered successfull, default OWL_SUCCESS
in $_object REference to the object to check, defaults to the current object
Returns
Boolean true when successfull
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::construct(), registerArgument(), and registerCallback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
out $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
in $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
Referenced by _OWL::check(), User::login(), and SessionHandler::read().
Member Data Documentation
Dispatcher::$dispatcher [private]
string - A dispatcher registered for callback
Dispatcher::$instance [static, private]
integer - self reference
Referenced by getInstance().
_OWL::$severity [protected, inherited]
Severity level of the current object status
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/bo/class.dispatcher.php