User Class Reference
the OWL-PHP user object
Public Member Functions
__destruct ()
login ($username, $password)
logout ($resetStatus=true)
hasRight ($bit, $appl)
isLoggedIn ()
getUsername ()
getUserId ()
getSessionId ()
setSessionVar ($var, $val=0, $flg=SESSIONVAR_SET)
getSessionVar ($var, $default=null)
getStatus ()
getSeverity ($status=null)
succeeded ($_ok=OWL_SUCCESS, &$_object=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Static Public Member Functions
static passwordStrength ($_pwd, $_compare=array())
Protected Member Functions
construct ($username=null)
register ($username, $email, $password, $vpassword, $group=0)
confirm (array $_confirmation)
init ()
setCallback ($_dispatcher)
setCallbackArgument (array $_arg)
getCallback ()
reset ()
saveStatus ()
restoreStatus ()
check (&$object, $level=OWL_WARNING)
setStatus ($status, $params=array())
setHighSeverity (&$object=null)
Protected Attributes
$severity
Private Member Functions
clearUser ($newSession=false)
newUser ()
saveUser ()
restoreUser ()
readUserdata ()
hashPassword ($password)
usernameExists ($username)
getMemberships ()
Private Attributes
$session
$dataset
$group
$memberships
$user_data
$rights
Detailed Description
the OWL-PHP user object
This class handles the OWL users
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Aug 27, 2008 -- O van Eijk -- initial version
Constructor & Destructor Documentation
User::__destruct ()
When a run ends, write the sessiondata
Reimplemented from _OWL .
References saveUser().
Member Function Documentation
_OWL::check (&$ object, $ level = OWL_WARNING) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
in $object Pointer to an object to check against
in $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
References _OWL::reset(), _OWL::setHighSeverity(), and _OWL::traceback().
Referenced by SessionHandler::write().
User::clearUser ($ newSession = false) [private]
Cleanup the existing user environment
Parameters
in $newSession Boolean set to true when a new session must be created
Referenced by login(), and logout().
User::confirm (array $ _confirmation) [protected]
Confirm a user registration.
Parameters
in $_confirmation Array that must contain at least the keys 'uid' and 'vcode'
Returns
True on success, false on failure
References _OWL::setStatus().
User::construct ($ username = null) [protected]
Class constructor; create a new user environment. This is not a regular constructor, since it's up to the application to decide if this is a normal object or a singleton.
Parameters
in $username Username when logged in. Default username is 'anonymous'
References ConfigHandler::get(), getUserId(), _OWL::init(), newUser(), restoreUser(), OWLCache::set(), and _OWL::succeeded().
_OWL::getCallback () [protected, inherited]
Retrieve a previously set (callback) dispatcher. The (callback) dispatcher is cleared immediatly.
Returns
The dispatcher, of null on failure.
Reimplemented in Dispatcher .
References OWL::factory().
User::getMemberships () [private]
Get the list of all objects this user is member of
References $dataset, ConfigHandler::get(), and getUserId().
Referenced by newUser().
User::getSessionId ()
Return the current session ID
Returns
the session ID
User::getSessionVar ($ var, $ default = null)
Get a session variable
Parameters
in $var Variable name
in $default Default value to return if the variable was not set (default null)
Returns
The value from the session, null if not set
Referenced by getUserId(), and restoreUser().
_OWL::getSeverity ($ status = null) [inherited]
Get the current object severity level.
Parameters
in $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
References _OWL::$status.
Referenced by LogHandler::composeMessage(), LogHandler::log(), and DataHandler::setKey().
_OWL::getStatus () [final, inherited]
Get the current object status.
Returns
Object's status code
Referenced by SchemeHandler::compare().
User::getUserId ()
Return the userID of the current session
References getSessionVar().
Referenced by construct(), getMemberships(), and readUserdata().
User::getUsername ()
Return the username of the current session
User::hashPassword ($ password) [private]
Encrypt a given password
Parameters
in $password Given password in plain text format
Returns
The encrypted password
References ConfigHandler::get().
Referenced by login(), and register().
User::hasRight ($ bit, $ appl)
Check if a rightsbit has been set for this user
Parameters
in $bit Rightsbit to check
in $appl ID of the application the bit belongs to
Returns
Boolean; true when the bit is set
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
References OWL::factory(), and _OWL::setStatus().
Referenced by FormFieldPlugin::__construct(), Tablerow::__construct(), Tablecell::__construct(), Table::__construct(), Document::__construct(), ContainerPlugin::__construct(), Container::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), OWL::__construct(), Group::__construct(), Form::__construct(), Dispatcher::__construct(), and construct().
User::isLoggedIn ()
Check is the current user is logged in
Returns
True when logged in
References ConfigHandler::get().
User::login ($ username, $ password)
Log in
Parameters
in $username Given username. Might be taken from the session as well, but given as a parameter here to suppress the E_STRICT Declaration warning
in $password The user provided password
Returns
True on success, False otherwise
References clearUser(), ConfigHandler::get(), hashPassword(), logout(), newUser(), _OWL::setStatus(), and _OWL::traceback().
User::logout ($ resetStatus = true)
Log out the current user Note: After logging out, the session still continues. The calling app must take care of the forward (e.g. with a header('location: ' . $_SERVER['PHP_SELF']) after a call to User::logout()).
Parameters
in $resetStatus When true (default) the object status will be reset
References clearUser(), ConfigHandler::get(), newUser(), _OWL::restoreStatus(), and _OWL::saveStatus().
Referenced by login().
User::newUser () [private]
(Re)initialize the user environment
References ConfigHandler::get(), getMemberships(), and readUserdata().
Referenced by construct(), login(), and logout().
static User::passwordStrength ($ _pwd, $ _compare = array()) [static]
Calculate the strenbgth of a given password. This method uses string length and checks for variations in the characters and digits used.
Parameters
in $_pwd The password as a string
in $_compare An optional array of string to compare with, like username and or email address. If the password if (part of) any of the strings in the array, the strength is decreased.
Returns
An integer from 0-10 indicating the strength, where 0 is the lowest and 10 the highest level
User::readUserdata () [private]
When a new session starts for a use that was logged in before retrieve the userdata back from the database
References ConfigHandler::get(), getUserId(), and _OWL::setStatus().
Referenced by newUser(), and restoreUser().
User::register ($ username, $ email, $ password, $ vpassword, $ group = 0) [protected]
Register a new username
Parameters
in $username Given username
in $email Given username
in $password Given password
in $vpassword Given password
in $group Default Group ID, defaults to the user|default_group config setting
Returns
New user ID or -1 on failure
References $group, ConfigHandler::get(), hashPassword(), RandomString(), _OWL::setCallbackArgument(), _OWL::setStatus(), and usernameExists().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Reimplemented in DbHandler , and SchemeHandler .
References _OWL::resetCalltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::setStatus().
_OWL::restoreStatus () [protected, inherited]
Restore the previously saved status object and destroy the copy
References _OWL::setStatus().
Referenced by logout().
User::restoreUser () [private]
Restore a user environment
References getSessionVar(), and readUserdata().
Referenced by construct().
_OWL::saveStatus () [protected, inherited]
Create a copy of the status object
Referenced by logout().
User::saveUser () [private]
Save the current user environment in the session
References setSessionVar().
Referenced by __destruct().
_OWL::setCallback ($ _dispatcher) [protected, inherited]
Set a dispatcher for later callback
Parameters
in $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher()
Returns
True on success, false on failure
References OWL::factory().
_OWL::setCallbackArgument (array $ _arg) [protected, inherited]
Add an argument to a previously registered callback dispatcher
Parameters
in $_arg Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
References OWL::factory().
Referenced by register().
_OWL::setHighSeverity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
User::setSessionVar ($ var, $ val = 0, $ flg = SESSIONVAR_SET)
Set a session variable
Parameters
in $var Variable name
in $val Variable value (default 0)
in $flg How to handle the value. Default SESSIONVAR_SET
Referenced by saveUser().
_OWL::setStatus ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
in $status OWL status code
in $params
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::getCode(), _OWL::reset(), and _OWL::signal().
Referenced by DbHandler::__clone(), Container::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), Session::__construct(), BaseElement::_getContent(), Form::addField(), FormFieldRadioPlugin::addOption(), BaseElement::addToContent(), DbHandler::alt(), SchemeHandler::alterScheme(), FileHandler::close(), DbHandler::commitTransaction(), Dispatcher::composeDispatcher(), confirm(), DbHandler::connect(), DbHandler::create(), SchemeHandler::createScheme(), SchemeHandler::defineIndex(), SchemeHandler::defineScheme(), Dispatcher::dispatch(), FormHandler::get(), DataHandler::get(), SchemeHandler::getTableColumns(), SchemeHandler::getTableIndexes(), _OWL::init(), Document::loadScript(), Document::loadStyle(), login(), FileHandler::open(), DbHandler::open(), LogHandler::openLogfile(), DataHandler::prepare(), DbHandler::prepareDelete(), DbHandler::prepareField(), DbHandler::prepareInsert(), DbHandler::prepareRead(), DbHandler::prepareUpdate(), DbHandler::read(), FileHandler::readLine(), readUserdata(), register(), Dispatcher::registerArgument(), Dispatcher::registerCallback(), _OWL::restoreStatus(), DbHandler::rollbackTransaction(), SchemeHandler::scheme(), FormHandler::set(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), Document::setFavicon(), Form::setFieldAttributes(), DataHandler::setJoin(), DataHandler::setKey(), FormFieldTextPlugin::setMaxsize(), Document::setMeta(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), Form::showField(), DbHandler::startTransaction(), SchemeHandler::tableDescription(), SchemeHandler::validateScheme(), and DbHandler::write().
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
in $level An optional severity level; message will only be displayed when it is at least of this level.
out $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
References ConfigHandler::get().
Referenced by _OWL::setStatus(), and _OWL::traceback().
_OWL::succeeded ($ _ok = OWL_SUCCESS, &$ _object = null) [inherited]
Check if the object currenlty has a success state
Parameters
in $_ok The highest severity that's considered successfull, default OWL_SUCCESS
in $_object REference to the object to check, defaults to the current object
Returns
Boolean true when successfull
Referenced by construct(), Dispatcher::registerArgument(), and Dispatcher::registerCallback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
out $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
in $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
References _OWL::signal().
Referenced by _OWL::check(), login(), and SessionHandler::read().
User::usernameExists ($ username) [private]
Check is a given username exists
Parameters
in $username The username to check
Returns
True when the username exists false otherwise
Referenced by register().
Member Data Documentation
User::$dataset [private]
Link to a datahandler object. This dataset is used as an interface to all database IO.
Referenced by getMemberships().
User::$group [private]
Primary group object
Referenced by register().
User::$memberships [private]
Array with the group objects the user is member of
User::$rights [private]
This users rightslist
User::$session [private]
The PHP session object
_OWL::$severity [protected, inherited]
Severity level of the current object status
Referenced by DbHandler::commitTransaction(), DbHandler::rollbackTransaction(), and DbHandler::startTransaction().
User::$user_data [private]
An indexed array with the user information as take from the database
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/bo/class.user.php