Form Class Reference
Form Element class.
Public Member Functions
__construct ($_dispatcher, $_attribs=array())
setMethod ($method)
setEncoding ($enctype)
addField ($type, $name, $value= '', $attributes=array())
setFieldAttributes ($index, $attributes)
setFieldEvents ($index, $events)
showField ($name)
showElement ()
setId ($_value)
getId ()
setName ($_value)
setStyle ($_value)
setClass ($_value)
setContent (&$_content)
addToContent (&$_content)
getContent ()
setEvent ($_event, $_action, $_add=false)
setAttributes (array $_attribs)
getLastWarning ()
getStatus ()
getSeverity ($status=null)
succeeded ($_ok=OWL_SUCCESS, &$_object=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Protected Member Functions
getAttributes (array $_ignore=array())
init ()
setCallback ($_dispatcher)
setCallbackArgument (array $_arg)
getCallback ()
reset ()
saveStatus ()
restoreStatus ()
check (&$object, $level=OWL_WARNING)
setStatus ($status, $params=array())
setHighSeverity (&$object=null)
Protected Attributes
$class = ''
$style = ''
$events = array()
$name = ''
$id = ''
$severity
Private Member Functions
openForm ()
closeForm ()
Private Attributes
$fields
$dispatcher
$method
$enctype
Detailed Description
Form Element class.
Define an HTML Form.
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Aug 29, 2008 -- O van Eijk -- initial version
Examples:
exa.form.php.
Constructor & Destructor Documentation
Form::__construct ($ _dispatcher, $ _attribs = array())
Class constructor
Parameters
in $_dispatcher OWL dispatcher as string or array,
See also
Dispatcher::composeDispatcher()
Parameters
in $_attribs Indexed array with the HTML attributes
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory(), _OWL::init(), and BaseElement::setAttributes().
Member Function Documentation
Form::addField ($ type, $ name, $ value = '', $ attributes = array())
Add a formfield to the formelement
Parameters
in $type Field type
in $name Field name
in $value Optional field value. For a selectlist type this must be an array, see FormFieldSelect::setValue()
in $attributes Indexed array with additional values in the format, where the key must be a supported attributed for the given type.
Returns
Reference to the field object, or the severity in case of errors
Author
Oscar van Eijk, Oveas Functionality Provider
References BaseElement::$name, OWLloader::getClass(), setFieldAttributes(), and _OWL::setStatus().
Referenced by closeForm().
BaseElement::addToContent (&$ _content) [inherited]
Add a content to the container. If the container is not an array yet, it will be converted to obe.
Parameters
in $_content Reference to the content, which can be HTML code or an object, of which the showElement() method will be called to retrieve the HTML.
Author
Oscar van Eijk, Oveas Functionality Provider
Examples:
exa.form.php.
References _OWL::setStatus().
_OWL::check (&$ object, $ level = OWL_WARNING) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
in $object Pointer to an object to check against
in $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::reset(), _OWL::setHighSeverity(), and _OWL::traceback().
Referenced by SessionHandler::write().
Form::closeForm () [private]
Close the form and set a hidden field defining the dispatcher
Returns
HTML code
Author
Oscar van Eijk, Oveas Functionality Provider
References addField(), and showField().
Referenced by showElement().
BaseElement::getAttributes (array $ _ignore = array()) [protected, inherited]
Return the general element attributes that are set
Parameters
in $_ignore Array with attributes names that should be ignored
Returns
string attributes in HTML format (' fld=`value`...)
Author
Oscar van Eijk, Oveas Functionality Provider
References BaseElement::getEvents().
Referenced by FormFieldPlugin::getGenericFieldAttributes(), openForm(), Tablerow::showElement(), Tablecell::showElement(), Table::showElement(), Document::showElement(), and Container::showElement().
_OWL::getCallback () [protected, inherited]
Retrieve a previously set (callback) dispatcher. The (callback) dispatcher is cleared immediatly.
Returns
The dispatcher, of null on failure.
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in Dispatcher .
References OWL::factory().
BaseElement::getContent () [inherited]
Get the content of the current container, which can be plain HTML, an object, or an array which can mix both types.
Returns
HTML code
Author
Oscar van Eijk, Oveas Functionality Provider
References BaseElement::_getContent().
Referenced by Tablecell::showElement(), Document::showElement(), Container::showElement(), and showElement().
BaseElement::getId () [inherited]
Get the element's HTML ID
Returns
The ID
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by BaseElement::_getContent().
_OWL::getLastWarning () [inherited]
Get the last warning or error message.
Returns
null if there was no error (severity below OWL_WARNING), otherwise the error text.
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
_OWL::getSeverity ($ status = null) [inherited]
Get the current object severity level.
Parameters
in $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::$status.
Referenced by LogHandler::composeMessage(), LogHandler::log(), and DataHandler::setKey().
_OWL::getStatus () [final, inherited]
Get the current object status.
Returns
Object's status code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by SchemeHandler::compare().
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory(), and _OWL::setStatus().
Referenced by FormFieldPlugin::__construct(), Tablerow::__construct(), Tablecell::__construct(), Table::__construct(), Document::__construct(), ContainerPlugin::__construct(), Container::__construct(), SocketHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), HDataHandler::__construct(), DataHandler::__construct(), OWL::__construct(), Mail::__construct(), Group::__construct(), __construct(), Dispatcher::__construct(), and User::construct().
Form::openForm () [private]
Return the form code to open the form
Returns
HTML code
Author
Oscar van Eijk, Oveas Functionality Provider
References BaseElement::getAttributes().
Referenced by showElement().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in DbHandler , and SchemeHandler .
References _OWL::resetCalltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::setStatus().
_OWL::restoreStatus () [protected, inherited]
Restore the previously saved status object and destroy the copy
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by User::logout().
_OWL::saveStatus () [protected, inherited]
Create a copy of the status object
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::logout().
BaseElement::setAttributes (array $ _attribs) [inherited]
Set the attributes of the DOM element by calling the 'set<Attrib>' method for this class.
Parameters
in $_attribs Array with attributes in the format attrib=>value
Returns
Severity level. The status increased when a set<Attrib> method does not exist.
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by Table::__construct(), Container::__construct(), and __construct().
_OWL::setCallback ($ _dispatcher) [protected, inherited]
Set a dispatcher for later callback
Parameters
in $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher()
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
_OWL::setCallbackArgument (array $ _arg) [protected, inherited]
Add an argument to a previously registered callback dispatcher
Parameters
in $_arg Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
Referenced by User::register().
BaseElement::setClass ($ _value) [inherited]
Set the element Class
Parameters
in $_value Class name
Author
Oscar van Eijk, Oveas Functionality Provider
BaseElement::setContent (&$ _content) [inherited]
Fill the content for a container. Existing content (e.g. set during instantiation) will be overwritten. If that is not desired, the addToContent method should be used instead.
Parameters
in $_content Reference to the content, which can be HTML code or an object, of which the showElement() method will be called to retrieve the HTML.
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by Tablecell::__construct(), and Container::__construct().
Form::setEncoding ($ enctype)
Set the form encoding
Parameters
in $enctype The encoding type, multipart/form-data and application/x-www-form-urlencoded are supported
Returns
Severity level of the object status
Author
Oscar van Eijk, Oveas Functionality Provider
References $enctype, and _OWL::setStatus().
BaseElement::setEvent ($ _event, $ _action, $ _add = false) [inherited]
Add an event to the events array
Parameters
in $_event Javascript event name (onXxx)
in $_action Javascript function or code
in $_add Boolean; when true, the action will be added if the event name already exists. Default is false; overwrite the action for this event.
Author
Oscar van Eijk, Oveas Functionality Provider
Form::setFieldAttributes ($ index, $ attributes)
Set one or more formfield attributes
Parameters
in $index Index of the fieldobject
in $attributes array with object name and values in the format ('attrib' => 'value')
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by addField().
Form::setFieldEvents ($ index, $ events)
Set one or more formfield events
Parameters
in $index Index of the fieldobject
in $events array with eventnames and JavaScript code in the format ('event' => 'action')
Author
Oscar van Eijk, Oveas Functionality Provider
References BaseElement::$events.
_OWL::setHighSeverity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
BaseElement::setId ($ _value) [inherited]
Set the element ID
Parameters
in $_value Identification
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by BaseElement::setName().
Form::setMethod ($ method)
Set the form method
Parameters
in $method The method, GET and POST are supported
Returns
Severity level of the object status
Author
Oscar van Eijk, Oveas Functionality Provider
References $method, and _OWL::setStatus().
BaseElement::setName ($ _value) [inherited]
Set the element name
Parameters
in $_value Element name
Author
Oscar van Eijk, Oveas Functionality Provider
References BaseElement::setId().
_OWL::setStatus ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
in $status OWL status code
in $params
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::getCode(), _OWL::reset(), and _OWL::signal().
Referenced by DbHandler::__clone(), Container::__construct(), SocketHandler::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), Session::__construct(), Mail::__construct(), BaseElement::_getContent(), Mail::addBcc(), Mail::addCc(), addField(), FormFieldRadioPlugin::addOption(), Mail::addTo(), BaseElement::addToContent(), DbHandler::alt(), SchemeHandler::alterScheme(), FileHandler::close(), DbHandler::commitTransaction(), Dispatcher::composeDispatcher(), User::confirm(), SocketHandler::connect(), DbHandler::connect(), DbHandler::create(), SchemeHandler::createScheme(), SchemeHandler::defineIndex(), SchemeHandler::defineScheme(), SocketHandler::disconnect(), Dispatcher::dispatch(), FormHandler::get(), DataHandler::get(), SchemeHandler::getTableColumns(), SchemeHandler::getTableIndexes(), _OWL::init(), Document::loadScript(), Document::loadStyle(), DbHandler::lockTable(), User::login(), FileHandler::open(), DbHandler::open(), LogHandler::openLogfile(), DataHandler::prepare(), DbHandler::prepareDelete(), DbHandler::prepareField(), DbHandler::prepareInsert(), DbHandler::prepareRead(), DbHandler::prepareUpdate(), SocketHandler::read(), DbHandler::read(), FileHandler::readLine(), HDataHandler::readQuery(), User::readUserdata(), User::register(), Dispatcher::registerArgument(), Dispatcher::registerCallback(), _OWL::restoreStatus(), DbHandler::rollbackTransaction(), SchemeHandler::scheme(), Mail::send(), FormHandler::set(), BaseElement::setAttributes(), BaseElement::setContent(), setEncoding(), Document::setFavicon(), setFieldAttributes(), Mail::setFrom(), DataHandler::setJoin(), DataHandler::setKey(), FormFieldTextPlugin::setMaxsize(), Document::setMeta(), setMethod(), FormFieldRadioPlugin::setSelected(), Mail::setSender(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), showField(), DbHandler::startTransaction(), SchemeHandler::tableDescription(), DbHandler::unlockTable(), SchemeHandler::validateScheme(), SocketHandler::write(), and DbHandler::write().
BaseElement::setStyle ($ _value) [inherited]
Set the element style
Parameters
in $_value Element style
Author
Oscar van Eijk, Oveas Functionality Provider
Form::showElement ()
Display the form
See also
BaseElement::showElement()
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from BaseElement .
References closeForm(), BaseElement::getContent(), and openForm().
Form::showField ($ name)
Get the HTML code for a given field
Parameters
in $name Fieldname
Returns
HTML code defining the field
Author
Oscar van Eijk, Oveas Functionality Provider
References BaseElement::$name, and _OWL::setStatus().
Referenced by closeForm().
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
in $level An optional severity level; message will only be displayed when it is at least of this level.
out $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
Referenced by _OWL::getLastWarning(), _OWL::setStatus(), and _OWL::traceback().
_OWL::succeeded ($ _ok = OWL_SUCCESS, &$ _object = null) [inherited]
Check if the object currenlty has a success state
Parameters
in $_ok The highest severity that's considered successfull, default OWL_SUCCESS
in $_object REference to the object to check, defaults to the current object
Returns
Boolean true when successfull
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::construct(), Dispatcher::registerArgument(), and Dispatcher::registerCallback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
out $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
in $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
Referenced by _OWL::check(), User::login(), and SessionHandler::read().
Member Data Documentation
BaseElement::$class = '' [protected, inherited]
Class specification
Form::$dispatcher [private]
String holding dispatch info.
Form::$enctype [private]
Form encoding; application/x-www-form-urlencoded (defauls) or multipart/form-data
Referenced by setEncoding().
BaseElement::$events = array() [protected, inherited]
Array with javascript events
Referenced by setFieldEvents().
Form::$fields [private]
Array holding all field objects
BaseElement::$id = '' [protected, inherited]
Element ID
Form::$method [private]
Method; post (default) or get
Referenced by setMethod().
BaseElement::$name = '' [protected, inherited]
Name of the element
Referenced by addField(), and showField().
_OWL::$severity [protected, inherited]
Severity level of the current object status
BaseElement::$style = '' [protected, inherited]
Element style
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/bo/class.form.php