OWLinstaller Class Reference
Application installer.
Static Public Member Functions
static construct ()
static installApplication ($code, $name, $version, $description= '', $link= '', $author= '', $license= '')
static enableApplication ($id)
static parseSQLFile ($fname)
static installTables ($sqlFile, $prefix=null)
static addGroupRights ($aid, $grp, array $rights)
static addGroups ($aid, array $grps)
static addRights ($aid, array $rights)
static addConfig ($aid, $item, $value, $protect=false, $hide=false, $group=null)
Static Private Member Functions
static uncommentSQL ($line)
static addTablePrefix ($q, $prefix)
Static Private Attributes
static $rights = array()
static $groups = array()
Detailed Description
Application installer.
Abstract class to install applications
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Apr 19, 2011 -- O van Eijk -- Initial version for OWL-PHP
Member Function Documentation
static OWLinstaller::addConfig ($ aid, $ item, $ value, $ protect = false, $ hide = false, $ group = null) [static]
Add an application specific dynamic config item. It is set or overwritten in the current configuration immediately.
Parameters
in $aid Application ID
in $item Name of the configuration item in the same format it appears in the configuration file (e.g. 'group|subject|item)
in $value Value of the configuration item
in $protect True if this is a protected item
in $hide True if this is an hidden item
in $group An optional groupname to which this item belongs
Returns
Boolean indicating success (true) or any failure (false)
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get(), and ConfigHandler::set().
static OWLinstaller::addGroupRights ($ aid, $ grp, array $ rights) [static]
Set the rights bitvalue for a given group
Parameters
in $aid Application ID.
in $grp Group name. This can be an existing OWL group
in $rights Array with right identifiers
Returns
Boolean indicating success (true) or any failure (false)
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
static OWLinstaller::addGroups ($ aid, array $ grps) [static]
Add the application specific groups to the database
Parameters
in $aid Application ID
in $grps Array of groups in the format (groupname => groupdescription)
Returns
Boolean indicating success (true) or any failure (false)
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
static OWLinstaller::addRights ($ aid, array $ rights) [static]
Add the application specific rights to the database
Parameters
in $aid Application ID
in $rights Array of rights in the format name => description
Returns
Boolean indicating success (true) or any failure (false)
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
static OWLinstaller::addTablePrefix ($ q, $ prefix) [static, private]
Check an SQL statement and lok for table names. When a tablename has been found, the table prefix will be added.
The following SQL queries are supported by the regular expressions (with and without backticks):
CREATE [TEMPORARY] TABLE [IF NOT EXISTS] `tblname`
ALTER [IGNORE] TABLE `tblname`
DROP [TEMPORARY] TABLE [IF EXISTS] `tblname`
INSERT [insert type] [IGNORE] [INTO] `tblname` (...)
CREATE [type] INDEX [name] [using type] ON `tblname` (...)
Parameters
in $q SQL query
in $prefix Prefix, or null to use the default
Returns
SQL statement with the prefixed tablename
Todo Add support for UPDATE, DELETE, RENAME and other statements that *might* occur in SQL install files
Handle constraints ([...] REFERENCES `tblname` (...))
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
Referenced by installTables().
static OWLinstaller::construct () [static]
Preload OWL data that can be used during the application install
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
static OWLinstaller::enableApplication ($ id) [static]
Enable an application
Parameters
in $id Application ID
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
static OWLinstaller::installApplication ($ code, $ name, $ version, $ description = '', $ link = '', $ author = '', $ license = '') [static]
Register an application in the database
Parameters
in $code Application code
in $name Name of the application
in $version Version number of the application
in $description Optional description
in $link Optional link to the applications homepage
in $author Optional name of the copyright holder
in $license Optional license
Returns
The application ID
Author
Oscar van Eijk, Oveas Functionality Provider
Todo Error checking
References ConfigHandler::get().
static OWLinstaller::installTables ($ sqlFile, $ prefix = null) [static]
Execute the queries from a given SQL file to install all tables for this application
Parameters
in $sqlFile Full path specification of the file containing SQL statements
in $prefix Table prefix to add if it's not in the SQL file. Specify 'false' to disable adding the prefix
Returns
Boolean indicating success (true) or any failure (false)
Author
Oscar van Eijk, Oveas Functionality Provider
References addTablePrefix(), OWL::factory(), and OWLdbg_add().
static OWLinstaller::parseSQLFile ($ fname) [static]
Parse a given SQL file
Parameters
in $fname Full path specification of the file containing SQL statements
Returns
An array with all SQL statements from the file, or null when an error occured
Author
Oscar van Eijk, Oveas Functionality Provider
References OWLdbg_add(), and uncommentSQL().
static OWLinstaller::uncommentSQL ($ line) [static, private]
Parse a line from an SQL file, stripping all comments
Parameters
in $line Line as read from the SQL file
Author
Oscar van Eijk, Oveas Functionality Provider
Returns
String with a (part of the) SQL statement
Referenced by parseSQLFile().
Member Data Documentation
OWLinstaller::$groups = array() [static, private]
Array with registered groups and their IDs
OWLinstaller::$rights = array() [static, private]
Array with registered rights and their bitvalues
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/OWLinstaller.php