SchemeHandler Class Reference
Scheme handler.
Public Member Functions
__destruct ()
__clone ()
createScheme ($_tblname)
defineScheme ($_scheme)
defineIndex ($_index)
scheme ($_drops=false)
alterScheme ($_field)
tableDescription ($tablename, &$data)
reset ()
getLastWarning ()
getStatus ()
getSeverity ($status=null)
succeeded ($_ok=OWL_SUCCESS, &$_object=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Static Public Member Functions
static getInstance ()
Protected Member Functions
init ()
setCallback ($_dispatcher)
setCallbackArgument (array $_arg)
getCallback ()
saveStatus ()
restoreStatus ()
check (&$object, $level=OWL_WARNING)
setStatus ($status, $params=array())
setHighSeverity (&$object=null)
stackMessage ($level=OWL_WARNING)
Protected Attributes
$severity
Private Member Functions
__construct ()
validateScheme ()
compare ()
createTable ()
alterTable ($_diffs, $_drops)
_define_field ($_desc)
getTableColumns ($_tablename)
getTableIndexes ($_tablename)
Private Attributes
$id
$db
$scheme
$table = ''
$inuse = false
Static Private Attributes
static $instance
Detailed Description
Scheme handler.
Handler for all database schemes. This singleton class handles all updates to db tables
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Oct 7, 2010 -- O van Eijk -- initial version for OWL
Note
A port of this class has been created for VirtueMart
Todo This handler currently doesn't use the DbDriver driver class
Constructor & Destructor Documentation
SchemeHandler::__construct () [private]
Class constructor
Author
Oscar van Eijk, Oveas Functionality Provider
References getInstance(), _OWL::init(), and _OWL::setStatus().
SchemeHandler::__destruct ()
Class destructor
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from _OWL .
Member Function Documentation
SchemeHandler::__clone ()
Implementation of the __clone() function to prevent cloning of this singleton; it triggers a fatal (user)error
Author
Oscar van Eijk, Oveas Functionality Provider
SchemeHandler::_define_field ($ _desc) [private]
Create the SQL code for a field definition
Parameters
in $_desc Indexed array with the field properties from scheme definition
Returns
string SQL code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by alterTable(), and createTable().
SchemeHandler::alterScheme ($ _field)
Modify 1 or more fields in an existing scheme definition
Parameters
in $_field Array holding 1 or more field descriptions
See also
defineScheme()
Returns
Boolean; false if the table description contains errors
Author
Oscar van Eijk, Oveas Functionality Provider
References scheme(), _OWL::setStatus(), and validateScheme().
SchemeHandler::alterTable ($ _diffs, $ _drops) [private]
Make changes to the table
Parameters
in $_diffs Changes to make
in $_drops True if existing fields should be dropped
Author
Oscar van Eijk, Oveas Functionality Provider
References _define_field().
Referenced by scheme().
_OWL::check (&$ object, $ level = OWL_WARNING) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
in $object Pointer to an object to check against
in $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::reset(), _OWL::setHighSeverity(), and _OWL::traceback().
Referenced by SessionHandler::write().
SchemeHandler::compare () [private]
Compare the scheme with an existing database table
Returns
mixed True if there are no differences, False if the table does not exist, or an array with differences
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::getStatus(), scheme(), and tableDescription().
Referenced by scheme().
SchemeHandler::createScheme ($ _tblname)
Set a new tablename
Parameters
in $_tblname Name of the table to create, check or modify
Author
Oscar van Eijk, Oveas Functionality Provider
References reset(), and _OWL::setStatus().
SchemeHandler::createTable () [private]
Create the defined table
Author
Oscar van Eijk, Oveas Functionality Provider
References _define_field(), and scheme().
Referenced by scheme().
SchemeHandler::defineIndex ($ _index)
Define the indexes for a table
Parameters
in $_index Array holding the index description. This is a 2 dimensional array where the first level holds the indexname. The second array defines the attributes for each index:
unique : Boolean; True for unique keys
primary : Boolean; True for the primary key
columns : Array; List with columnnames that will be indexed
type : String (optional); Index type, currenty only supports 'FULLTEXT'
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References scheme(), _OWL::setStatus(), and validateScheme().
SchemeHandler::defineScheme ($ _scheme)
Define the layout for a table
Parameters
in $_scheme Array holding the table description. This is a 2 dimensional array where the first level holds the fieldnames. The second array defines the attributes for each field:
type : String; the field-type (INT|TINYINT|VARCHAR|MEDIUMTEXT|TEXT|LONGTEXT|BLOB|LONGBLOB|ENUM|SET)
length : Integer; indicating the length for fieldtypes that use that (like INT and VARCHAR)
null : Boolean; when true the value can be NULL
auto-inc : Boolean; True for auto-increment values (will be set as primary key)
default : Mixed; default value
options : Array; for SET and ENUM types. the list of possible values
comment : String; field comment
Author
Oscar van Eijk, Oveas Functionality Provider
References scheme(), _OWL::setStatus(), and validateScheme().
_OWL::getCallback () [protected, inherited]
Retrieve a previously set (callback) dispatcher. The (callback) dispatcher is cleared immediatly.
Returns
The dispatcher, of null on failure.
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in Dispatcher .
References OWL::factory().
static SchemeHandler::getInstance () [static]
Return a reference to my implementation. If necessary, create that implementation first.
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References $instance.
Referenced by __construct().
_OWL::getLastWarning () [inherited]
Get the last warning or error message.
Returns
null if there was no error (severity below OWL_WARNING), otherwise the error text.
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
_OWL::getSeverity ($ status = null) [inherited]
Get the current object severity level.
Parameters
in $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::$status.
Referenced by LogHandler::composeMessage(), LogHandler::log(), and DataHandler::setKey().
_OWL::getStatus () [final, inherited]
Get the current object status.
Returns
Object's status code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by compare().
SchemeHandler::getTableColumns ($ _tablename) [private]
Get the columns for a given table
Parameters
in $_tablename The tablename
Returns
Indexed array holding all fields => datatypes, or null on errors
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by tableDescription().
SchemeHandler::getTableIndexes ($ _tablename) [private]
Get the indexes for a given table
Parameters
in $_tablename The tablename
Returns
Indexed array holding all fields => datatypes, or null on errors
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by tableDescription().
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory(), and _OWL::setStatus().
Referenced by FormFieldPlugin::__construct(), Document::__construct(), ContainerPlugin::__construct(), Container::__construct(), SocketHandler::__construct(), SessionHandler::__construct(), __construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), HDataHandler::__construct(), DataHandler::__construct(), OWL::__construct(), Mail::__construct(), Group::__construct(), Form::__construct(), Dispatcher::__construct(), and User::construct().
SchemeHandler::reset ()
Reset the internal data structure
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from _OWL .
References scheme().
Referenced by createScheme().
_OWL::restoreStatus () [protected, inherited]
Restore the previously saved status object and destroy the copy
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by User::logout().
_OWL::saveStatus () [protected, inherited]
Create a copy of the status object
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::logout().
SchemeHandler::scheme ($ _drops = false)
If the table does not exist, or differs from the defined scheme, create of modify the table
Parameters
in $_drops True if existing fields should be dropped; default false. If existing fields should be converted to new fields, call with DbScheme::scheme(false) first, then do the conversions, next call DbScheme::scheme(true).
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References alterTable(), compare(), createTable(), and _OWL::setStatus().
Referenced by alterScheme(), compare(), createTable(), defineIndex(), defineScheme(), reset(), and validateScheme().
_OWL::setCallback ($ _dispatcher) [protected, inherited]
Set a dispatcher for later callback
Parameters
in $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher()
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
_OWL::setCallbackArgument (array $ _arg) [protected, inherited]
Add an argument to a previously registered callback dispatcher
Parameters
in $_arg Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
Referenced by User::register().
_OWL::setHighSeverity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
_OWL::setStatus ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
in $status OWL status code
in $params
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::getCode(), _OWL::reset(), and _OWL::signal().
Referenced by DbHandler::__clone(), Container::__construct(), SocketHandler::__construct(), __construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), Session::__construct(), Mail::__construct(), BaseElement::_getContent(), HDataHandler::_getNewLeft(), Mail::addBcc(), Mail::addCc(), Container::addContainer(), Form::addField(), FormFieldRadioPlugin::addOption(), HDataHandler::addParent(), Mail::addTo(), BaseElement::addToContent(), DbHandler::alt(), alterScheme(), FileHandler::close(), DbHandler::commitTransaction(), Dispatcher::composeDispatcher(), User::confirm(), SocketHandler::connect(), DbHandler::connect(), DbHandler::create(), createScheme(), DbHandler::dbread(), defineIndex(), defineScheme(), SocketHandler::disconnect(), Dispatcher::dispatch(), HDataHandler::enableCrossLink(), FormHandler::get(), DataHandler::get(), HDataHandler::getDirectChildren(), HDataHandler::getFullOffspring(), Group::getGroupByName(), getTableColumns(), getTableIndexes(), _OWL::init(), Document::loadScript(), Document::loadStyle(), DbHandler::lockTable(), User::login(), HDataHandler::moveNode(), FileHandler::open(), DbHandler::open(), LogHandler::openLogfile(), DataHandler::prepare(), DbHandler::prepareDelete(), DbHandler::prepareField(), DbHandler::prepareInsert(), DbHandler::prepareRead(), DbHandler::prepareUpdate(), SocketHandler::read(), DbHandler::read(), FileHandler::readLine(), HDataHandler::readQuery(), User::readUserdata(), User::register(), Dispatcher::registerArgument(), Dispatcher::registerCallback(), DbHandler::resetTable(), _OWL::restoreStatus(), DbHandler::rollbackTransaction(), scheme(), Mail::send(), FormHandler::set(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), Document::setFavicon(), Form::setFieldAttributes(), Mail::setFrom(), DataHandler::setJoin(), DataHandler::setKey(), FormFieldTextPlugin::setMaxsize(), Document::setMeta(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), Mail::setSender(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), Form::showField(), DbHandler::startTransaction(), tableDescription(), DbHandler::unlockTable(), validateScheme(), SocketHandler::write(), DbHandler::write(), and HDataHandler::writeQuery().
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
in $level An optional severity level; message will only be displayed when it is at least of this level.
out $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get(), OutputHandler::outputLine(), and OutputHandler::outputRaw().
Referenced by _OWL::getLastWarning(), _OWL::setStatus(), _OWL::stackMessage(), and _OWL::traceback().
_OWL::stackMessage ($ level = OWL_WARNING) [protected, inherited]
Add the message for the latests status change to the document
See also
Document::addMessage()
Parameters
in $level Minimum severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References $_doc, _OWL::$severity, OWL::factory(), and _OWL::signal().
_OWL::succeeded ($ _ok = OWL_SUCCESS, &$ _object = null) [inherited]
Check if the object currenlty has a success state
Parameters
in $_ok The highest severity that's considered successfull, default OWL_SUCCESS
in $_object REference to the object to check, defaults to the current object
Returns
Boolean true when successfull
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::construct(), Dispatcher::registerArgument(), and Dispatcher::registerCallback().
SchemeHandler::tableDescription ($ tablename, &$ data)
Get a description of a database table
Parameters
in $tablename The tablename
out $data Indexed array holding all fields => datatypes
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References getTableColumns(), getTableIndexes(), and _OWL::setStatus().
Referenced by compare().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
out $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
in $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
Referenced by _OWL::check(), User::login(), and SessionHandler::read().
SchemeHandler::validateScheme () [private]
Validate the defined scheme. Some values will be modified to make sure the SQL statements can be prepared and compare() won't find differences on case diffs
Returns
boolean False if there is an error in the scheme definition, True if no errors were found
Author
Oscar van Eijk, Oveas Functionality Provider
References scheme(), and _OWL::setStatus().
Referenced by alterScheme(), defineIndex(), and defineScheme().
Member Data Documentation
SchemeHandler::$db [private]
integer - Reference to the database class
SchemeHandler::$id [private]
integer - Scheme Handle ID
SchemeHandler::$instance [static, private]
integer - self reference
Referenced by getInstance().
SchemeHandler::$inuse = false [private]
boolean - True when a scheme is filled with data and not yet used
SchemeHandler::$scheme [private]
Array - table description
_OWL::$severity [protected, inherited]
Severity level of the current object status
Referenced by _OWL::stackMessage().
SchemeHandler::$table = '' [private]
Array - table name
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.schemehandler.php