FormFieldButton Class Reference
Formfield.
Public Member Functions
__construct ($type= 'button')
getFieldCode ()
setName ($_value)
setValue ($_value)
getType ()
Public Attributes
$alt
$src
Protected Member Functions
getGenericFieldAttributes ($_ignore=array())
Protected Attributes
$type
$name
$value
$disabled
$readonly
Detailed Description
Formfield. Formfield button elements
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Oct 19, 2010 -- O van Eijk -- initial version
Constructor & Destructor Documentation
FormFieldButton::__construct ($ type = 'button')
Class constructor;
Parameters
$\leftarrow$ $type Element type: button (default), image, submit or reset
References FormField::$type, and FormField::__construct().
Member Function Documentation
FormFieldButton::getFieldCode ()
Return the HTML code to display the form element
Returns
Textstring with the complete code for the form element
References FormField::getGenericFieldAttributes().
FormField::getGenericFieldAttributes ($ _ignore = array()) [protected, inherited]
Return the attributes for an HTML formfield in the ` attrib='value' [...]` format
Parameters
$\leftarrow$ $_ignore Array with attributes names that should be ignored, e.g. for a textarea, the value is not returned as an attribute.
Returns
Textstring with the HTML code
Referenced by FormFieldTextarea::getFieldCode(), FormFieldText::getFieldCode(), FormFieldRadio::getFieldCode(), FormFieldCheckbox::getFieldCode(), and getFieldCode().
FormField::getType () [inherited]
Give the field type
Returns
Field type
FormField::setName ($ _value) [inherited]
Set the field name
Parameters
$\leftarrow$ $_value Field name
FormField::setValue ($ _value) [inherited]
Set the field value
Parameters
$\leftarrow$ $_value Field value
Reimplemented in FormFieldCheckbox, FormFieldRadio, and FormFieldSelect.
Member Data Documentation
FormFieldButton::$alt
Alternate text (image-type only)
FormField::$disabled [protected, inherited]
Boolean indicating a disabled field when true
FormField::$name [protected, inherited]
Name of the formfield
FormField::$readonly [protected, inherited]
Boolean indicating a readonly field when true
FormFieldButton::$src
Image src (image-type only)
FormField::$type [protected, inherited]
Field type
Reimplemented in FormFieldTextarea.
Referenced by FormFieldText::__construct(), and __construct().
FormField::$value [protected, inherited]
Field value
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/ui/class.formfield.button.php