HDataHandler Class Reference
The OWL Hierarchical Data object.
Public Member Functions
__construct ($tablename= '')
setLeft ($fieldname)
setRight ($fieldname)
enableCrossLink ($fieldname)
setPrimaryKey ($fieldname)
getLeafNodes ()
getNode ($field, $value)
getPathByChild ($field, $value)
getPathByParent ($field, $value)
getNodeDepth ($field, $value=null)
getFullOffspring ($field, $value, $follow=HDATA_XLINK_FOLLOW_NO)
getDirectChildren ($field, $value, $xlink=true)
getNodesByDepth ($depth, $field, $value=null)
insertNode (array $data, array $parent, $position=-1)
addParent (array $node, array $parent)
removeNode ($field, $value)
removeTree ($field, $value)
moveNode ($field, $value, array $newParent, $position=-1)
reset ($level=DATA_RESET_PREPARE)
getDbLink ()
set ($variable, $value, $table=null, array $fieldFunction=null, array $valueFunction=null)
setKey ($variable)
escapeString ($string)
get ($variable)
setJoin ($lvalue, $rvalue, $linktype= '=')
setTablename ($tblname)
prepare ($type=DATA_READ)
db (&$data=null, $line=0, $file= '[unknown]')
setPrefix ($prefix)
dbStatus ()
insertedId ()
getLastWarning ()
getStatus ()
getSeverity ($status=null)
succeeded ($_ok=OWL_SUCCESS, &$_object=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Protected Member Functions
reset ()
init ()
setCallback ($_dispatcher)
setCallbackArgument (array $_arg)
getCallback ()
saveStatus ()
restoreStatus ()
check (&$object, $level=OWL_WARNING)
setStatus ($status, $params=array())
setHighSeverity (&$object=null)
stackMessage ($level=OWL_WARNING)
Protected Attributes
$owl_tablename
$owl_database
$severity
Private Member Functions
readQuery ($query, $line)
_getNewLeft (array $parent, $position=-1)
writeQuery ($query, $line)
Private Attributes
$left
$right
$xlink
$xlinkID
Detailed Description
The OWL Hierarchical Data object.
This class contains DB datasets for hierarchical tables
Author
Oscar van Eijk, Oveas Functionality Provider
Version
May 13, 2011 -- O van Eijk -- initial version
Constructor & Destructor Documentation
HDataHandler::__construct ($ tablename = '')
Class constructor.
Parameters
in $tablename Default table name for this dataset
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from DataHandler .
References _OWL::init().
Member Function Documentation
HDataHandler::_getNewLeft (array $ parent, $ position = -1) [private]
Get the new left position for a node being moved or inserted
Parameters
in $parent Parent under which the (new) node will be added.
in $position Position at which the new node will be inserted.
Returns
The value for the left position
Author
Oscar van Eijk, Oveas Functionality Provider
References getDirectChildren(), getNode(), getNodesByDepth(), and _OWL::setStatus().
Referenced by insertNode(), and moveNode().
HDataHandler::addParent (array $ node, array $ parent)
Add a crosslink so a given node, adding (or overwriting) a second parent.
Parameters
in $node Identification if the node to change. This must be an indexed array with the keys 'field' and 'value' identifying the node, where field is the name of a unique indexed tablefield and value the value for the requested node.
in $parent Identification of the additional parent. This must be an indexed array with the keys 'field' and 'value' identifying the parent node, where field is the name of a unique indexed tablefield and value the value for the requested parent.
Returns
True on success, false on errors
Author
Oscar van Eijk, Oveas Functionality Provider
References getNode(), _OWL::setStatus(), and writeQuery().
_OWL::check (&$ object, $ level = OWL_WARNING) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
in $object Pointer to an object to check against
in $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::reset(), _OWL::setHighSeverity(), and _OWL::traceback().
Referenced by SessionHandler::write().
DataHandler::db (&$ data = null, $ line = 0, $ file = '[unknown]') [inherited]
Forward a call to the DBHandler object (which is private in this DataHandler)
Parameters
out $data The result of DBHandler function, or false when no query was prepared yet
in $line Line number of this call
in $file File that made the call to this method
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setHighSeverity().
DataHandler::dbStatus () [inherited]
Return the last status of the database
Returns
Current status of the database object
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by getFullOffspring().
HDataHandler::enableCrossLink ($ fieldname)
Enable crosslinks allowing items in the hierarchy to be reachable via 2 parents
Parameters
in $fieldname Name of the field holding the additional parent
Returns
True on success, false when the ID field has not been defined yet
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
DataHandler::escapeString ($ string) [inherited]
Interface to the DbHander::escapeString()
Parameters
in $string String to escape
Returns
Return value of DbHandler::escapeString()
Author
Oscar van Eijk, Oveas Functionality Provider
DataHandler::get ($ variable) [inherited]
Retrieve a value from the data array. The variable name can be a fully qualified table/fieldname (format `table#field`), or only a field name, in which case it has to be unique. If the fieldname cannot be found directly, the array is scanned to find a matching field. If more matches are found, the object status is set to DATA_AMBFIELD.
Note
The data array contains arrays where the first element is the matchtype (=, <, <= etc) and the second element is the actual value!
Parameters
in $variable The name of the variable that should be retrieved
Returns
The value, or NULL when the value was not found or abigious.
Author
Oscar van Eijk, Oveas Functionality Provider
References DataHandler::findField(), and _OWL::setStatus().
_OWL::getCallback () [protected, inherited]
Retrieve a previously set (callback) dispatcher. The (callback) dispatcher is cleared immediatly.
Returns
The dispatcher, of null on failure.
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in Dispatcher .
References OWL::factory().
DataHandler::getDbLink () [inherited]
Get the link to the actual database object of the dataset, which might be the original singleton, or the clone in use.
Author
Oscar van Eijk, Oveas Functionality Provider
HDataHandler::getDirectChildren ($ field, $ value, $ xlink = true)
Retrieve the direct chilren of a given parent
Parameters
in $field Name of the field on which the parent should be matched, must be a primary key or unique indexed field
in $value Value of the parent's field
in $xlink True (default) of crosslinked childnodes should be included
Returns
Array with all matched records including the depth (always 1, but required for the match)
Author
Oscar van Eijk, Oveas Functionality Provider
References $xlink, readQuery(), and _OWL::setStatus().
Referenced by _getNewLeft().
HDataHandler::getFullOffspring ($ field, $ value, $ follow = HDATA_XLINK_FOLLOW_NO)
Retrieve all childnodes starting with a given parent
Parameters
in $field Name of the field on which the parent should be matched, must be a primary key or unique indexed field
in $value Value of the parent's field
in $follow When crosslinks are enabled, this identifies to what level crosslinks should be followed.
Warning
User yje $follow parameter with care! Right now, only 3 options are implemented. HDATA_XLINK_FOLLOW_NO is the default value, but checks are made only for HDATA_XLINK_FOLLOW_NO and HDATA_XLINK_FOLLOW_ONCE. Any other value will be interpreted as HDATA_XLINK_FOLLOW_UNLIMITED! See Follow crosslinks for more info!
Returns
2-D array with all records for all direct children, or false on errors
Author
Oscar van Eijk, Oveas Functionality Provider
References DataHandler::dbStatus(), readQuery(), and _OWL::setStatus().
_OWL::getLastWarning () [inherited]
Get the last warning or error message.
Returns
null if there was no error (severity below OWL_WARNING), otherwise the error text.
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
HDataHandler::getLeafNodes ()
Get all items without children
Returns
2-D array with all records for all leaf nodes, or false on errors
Author
Oscar van Eijk, Oveas Functionality Provider
References readQuery().
HDataHandler::getNode ($ field, $ value)
Get the record for a single node
Parameters
in $field Name of the field on which the value should be matched, must be a primary key or unique indexed field
in $value Value of the field to match
Returns
Array with all fields for this node, or false on errors
Author
Oscar van Eijk, Oveas Functionality Provider
References readQuery().
Referenced by _getNewLeft(), addParent(), moveNode(), removeNode(), and removeTree().
HDataHandler::getNodeDepth ($ field, $ value = null)
Get the depth of all nodes or a single node.
Parameters
in $field The fieldname of which value that will be returned with the depth, must be a primary key or unique indexed field
in $value An optional value to match if only the depth of 1 field is requested
Returns
Array with all matched records including the depth
Author
Oscar van Eijk, Oveas Functionality Provider
References readQuery().
HDataHandler::getNodesByDepth ($ depth, $ field, $ value = null)
Get all nodes from the given depth, optionally from a given tree
Parameters
in $depth Depth level, where 0 is the toplevel
in $field Fieldname of a unique indexed field used to identify records.
in $value Value for fieldname identifying the top node for a tree. When this is null (default), all nodes with the same depth will be returned. If depth eqs 0, the value is ignored.
Note
Crosslinks, when enabled, are not followed in this method
Returns
Array with all matched records including the given depth (required for the match)
Author
Oscar van Eijk, Oveas Functionality Provider
References readQuery().
Referenced by _getNewLeft().
HDataHandler::getPathByChild ($ field, $ value)
Get the complete path of ancestors for a given node
Parameters
in $field Name of the field on which the field should be matched, must be a primary key or unique indexed field
in $value Value of the field to match
Returns
2-D array with all records for the full path, or false on errors
Author
Oscar van Eijk, Oveas Functionality Provider
References readQuery().
HDataHandler::getPathByParent ($ field, $ value)
Get the complete path of offspring for a given node
Parameters
in $field Name of the field on which the field should be matched, must be a primary key or unique indexed field
in $value Value of the field to match
Returns
2-D array with all records for the full path, or false on errors
Author
Oscar van Eijk, Oveas Functionality Provider
References readQuery().
_OWL::getSeverity ($ status = null) [inherited]
Get the current object severity level.
Parameters
in $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::$status.
Referenced by LogHandler::composeMessage(), LogHandler::log(), and DataHandler::setKey().
_OWL::getStatus () [final, inherited]
Get the current object status.
Returns
Object's status code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by SchemeHandler::compare().
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory(), and _OWL::setStatus().
Referenced by FormFieldPlugin::__construct(), Document::__construct(), ContainerPlugin::__construct(), Container::__construct(), SocketHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), __construct(), DataHandler::__construct(), OWL::__construct(), Mail::__construct(), Group::__construct(), Form::__construct(), Dispatcher::__construct(), and User::construct().
DataHandler::insertedId () [inherited]
Return the last inserted AutoIncrement value
Returns
Last ID
Author
Oscar van Eijk, Oveas Functionality Provider
HDataHandler::insertNode (array $ data, array $ parent, $ position = -1)
Insert a new node
Parameters
in $data Indexed array with the data, in the format (field => value, ...) where all table fields must be provided that are not allowed to be null. The fields for left and right will be ignored, if the primary key is an auto increment, this must not be given in the array.
in $parent Parent under which the new node will be added. This must be an indexed array with the keys 'field' and 'value' identifying the parent node, where field is the name of a unique indexed tablefield and value the value for the requested parent. To insert a new node at toplevel, leave out the value, but 'field' is always required!
in $position Position at which the new node will be inserted, where '0' results as an insert as the leftmost childnode, and any negative value (default) or a value greater than the current number of children will result in an insert as the rightmost child.
Note
During the insert operation, left and right values are changed and might be conflicting at a certain point. Technically that is no problem during a transaction, but some databases will fail when the left and right values are indexed unique, so these fields should be indexed nut not UNIQUE!
Returns
True on success, false on errors
Author
Oscar van Eijk, Oveas Functionality Provider
References _getNewLeft(), and writeQuery().
HDataHandler::moveNode ($ field, $ value, array $ newParent, $ position = -1)
Move a node or a complete tree to a new parent.
Parameters
in $field Name of the field on which the value should be matched, must be a primary key or unique indexed field
in $value Value of the field to match to identifying the node
in $newParent Parent to which the node will be moved. This must be an indexed array with the keys 'field' and 'value' identifying the parent node, where field is the name of a unique indexed tablefield and value the value for the requested parent.
in $position Position at which the node will be inserted, where '0' results as an insert as the leftmost childnode, and any negative value (default) or a value greater than the current number of children will result in an postision as the rightmost child.
Note
To keep a complete tree together while being moved, the left and right values are temporarily set to a negative value. Therefore, this method will not work when the left and right values are defined as UNSIGNED!
Returns
True on success
Todo Is the tree being moved contains crosslinks to the new parent already, they should be deleted
Author
Oscar van Eijk, Oveas Functionality Provider
References _getNewLeft(), getNode(), _OWL::setStatus(), and writeQuery().
DataHandler::prepare ($ type = DATA_READ) [inherited]
Prepare a database query
Parameters
in $type Specify which type of query should be prepared:
DATA_READ (default); Read data from the database
DATA_WRITE; Write new data to the database
DATA_UPDATE; Update data in the database
Returns
Severity level
Todo add limit and cache
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setHighSeverity(), and _OWL::setStatus().
HDataHandler::readQuery ($ query, $ line) [private]
Internal helper method to execute a read query
Parameters
in $query Query to execute
in $line Line number from which this method is called
Returns
Result of the query, or false on errors
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by getDirectChildren(), getFullOffspring(), getLeafNodes(), getNode(), getNodeDepth(), getNodesByDepth(), getPathByChild(), getPathByParent(), and removeTree().
HDataHandler::removeNode ($ field, $ value)
Delete a single node from the table. If the node has children, they will be added to the deleted nodes parent (so if the deleted node is a toplevel node, the children will be toplevel). All exising cross references will be removed (nullified).
Parameters
in $field Name of the field on which the value should be matched, must be a primary key or unique indexed field
in $value Value of the field to match
Returns
True on success
Author
Oscar van Eijk, Oveas Functionality Provider
References getNode(), and writeQuery().
HDataHandler::removeTree ($ field, $ value)
Delete a complete tree, removeing all cross references to from outside the tree to any of the nodes being deleted. All exising cross references will be removed (nullified).
Warning
This deletes the given node and all values under it! Use with care!
Parameters
in $field Name of the field on which the value should be matched, must be a primary key or unique indexed field
in $value Value of the field identifying the toplevel of the tree
Returns
True on success
Author
Oscar van Eijk, Oveas Functionality Provider
References getNode(), readQuery(), and writeQuery().
DataHandler::reset ($ level = DATA_RESET_PREPARE) [inherited]
Reset the object
Parameters
in $level Bitmap indicating which items must be reset. Default is DATA_RESET_PREPARE
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::reset().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in DbHandler , and SchemeHandler .
References _OWL::resetCalltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::setStatus().
_OWL::restoreStatus () [protected, inherited]
Restore the previously saved status object and destroy the copy
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by User::logout().
_OWL::saveStatus () [protected, inherited]
Create a copy of the status object
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::logout().
DataHandler::set ($ variable, $ value, $ table = null, array $ fieldFunction = null, array $ valueFunction = null) [inherited]
Define or override a variable in the data array
Parameters
in $variable The name of the variable that should be set.
in $value Value to set the variable to. For read operations, this can be a value, in which case the fieldname be will looked for matching all given values. Values with unescaped percent signs will be searched using the SQL LIKE keyword. If the matchtype is DBMATCH_NONE, the value is ignored.
in $table An optional tablename for this field. Defaults to $this->owl_tablename
in $fieldFunction An optional array with SQL functions and statements that apply to the fieldname. This is an indexed array, where all keys must have an array as value. The following keys are supported:
function: An array where the first element is an SQL function, which must exist in the database driver as 'functionFunction' (e.g., for 'function'=> array(`ifnull`, `default`), the method `functionIfnull()` must exist). The first argument passed to the method is always the fieldname, additional arguments will be taken from the array.
groupby: Add the fieldname to a groupby list. The value for this key must be an empty array
orderby: Add the fieldname to the orderby list. The given array can contain 1 element; `ASC` or `DESC`. When empty, it defaults to the SQL default (ASC)
having: Add the fieldname to to the having clause. The array must contain 2 elements, where the first element is the matchtype and the second argument is the value to match
name: The DataHandler returns data as indexed arrays on read operations, where the index equals the fieldname. This might contain complete SQL code when functions are called; this can be overwritten by specifying a name for the field
in $valueFunction An optional array with SQL functions and statements that apply to the value. This is an indexed array, where all keys must have an array as value. The following keys are supported:
function: An array where the first element is an SQL function, which must exist in the database driver as 'functionFunction' (e.g., for 'function'=> array(`ifnull`, `default`), the method `functionIfnull()` must exist). The first argument passed to the method is always the fieldname, additional arguments will be taken from the array.
match: The matchtype. When omitted, default is DBMATCH_EQ ('='). If the field should be in a SELECT list and not in the where clause, use the matchtype DBMATCH_NONE (if no fields are set with DBMATCH_NONE, read queries will select with SELECT *)
See also
exa.datahandler-set.php
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by DataHandler::setPrefix().
_OWL::setCallback ($ _dispatcher) [protected, inherited]
Set a dispatcher for later callback
Parameters
in $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher()
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
_OWL::setCallbackArgument (array $ _arg) [protected, inherited]
Add an argument to a previously registered callback dispatcher
Parameters
in $_arg Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
Referenced by User::register().
_OWL::setHighSeverity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
DataHandler::setJoin ($ lvalue, $ rvalue, $ linktype = '=') [inherited]
Define a link between 2 fields that will be recognized when the database query is built.
Parameters
in $lvalue Left value as array(table, field)
in $rvalue Right value as array(table, field)
in $linktype How are the fields linked. Can be any binary operator as recognized by SQL.
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
DataHandler::setKey ($ variable) [inherited]
Lock variables for update by adding them to an array. Fields in this array will not be overwritten on updates, but used in WHERE clauses.
Parameters
in $variable Variable name to lock, optionally as an array (table, field)
Returns
Severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::getSeverity(), and _OWL::setStatus().
HDataHandler::setLeft ($ fieldname)
Set or overwrite the fieldname of the left position indicator
Parameters
in $fieldname Name of the tablefield
Author
Oscar van Eijk, Oveas Functionality Provider
DataHandler::setPrefix ($ prefix) [inherited]
Overwrite the table prefix for this dataset. Since the prefix is stored in the database handler object, a clone is used (or made) here.
Parameters
in $prefix Table prefix
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory(), OWLCache::get(), and DataHandler::set().
HDataHandler::setPrimaryKey ($ fieldname)
Set the name of the primary key field. This is required for crosslinks
Parameters
in $fieldname Name of the field
Author
Oscar van Eijk, Oveas Functionality Provider
HDataHandler::setRight ($ fieldname)
Set or overwrite the fieldname of the right position indicator
Parameters
in $fieldname Name of the tablefield
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::setStatus ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
in $status OWL status code
in $params
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::getCode(), _OWL::reset(), and _OWL::signal().
Referenced by Container::__call(), DbHandler::__clone(), Container::__construct(), SocketHandler::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), Session::__construct(), Mail::__construct(), BaseElement::_getContent(), _getNewLeft(), Mail::addBcc(), Mail::addCc(), Container::addContainer(), Form::addField(), FormFieldRadioPlugin::addOption(), addParent(), Mail::addTo(), BaseElement::addToContent(), DbHandler::alt(), SchemeHandler::alterScheme(), FileHandler::close(), DbHandler::commitTransaction(), Dispatcher::composeDispatcher(), User::confirm(), SocketHandler::connect(), DbHandler::connect(), DbHandler::create(), SchemeHandler::createScheme(), DbHandler::dbread(), SchemeHandler::defineIndex(), SchemeHandler::defineScheme(), SocketHandler::disconnect(), Dispatcher::dispatch(), enableCrossLink(), FormHandler::get(), DataHandler::get(), getDirectChildren(), getFullOffspring(), Group::getGroupByName(), SchemeHandler::getTableColumns(), SchemeHandler::getTableIndexes(), _OWL::init(), Document::loadScript(), Document::loadStyle(), DbHandler::lockTable(), User::login(), moveNode(), FileHandler::open(), DbHandler::open(), LogHandler::openLogfile(), DataHandler::prepare(), DbHandler::prepareDelete(), DbHandler::prepareField(), DbHandler::prepareInsert(), DbHandler::prepareRead(), DbHandler::prepareUpdate(), SocketHandler::read(), DbHandler::read(), FileHandler::readLine(), readQuery(), User::readUserdata(), User::register(), Dispatcher::registerArgument(), Dispatcher::registerCallback(), DbHandler::resetTable(), _OWL::restoreStatus(), DbHandler::rollbackTransaction(), SchemeHandler::scheme(), Mail::send(), FormHandler::set(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), Document::setFavicon(), Form::setFieldAttributes(), Mail::setFrom(), DataHandler::setJoin(), DataHandler::setKey(), FormFieldTextPlugin::setMaxsize(), Document::setMeta(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), Mail::setSender(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), Form::showField(), DbHandler::startTransaction(), SchemeHandler::tableDescription(), DbHandler::unlockTable(), SchemeHandler::validateScheme(), SocketHandler::write(), DbHandler::write(), and writeQuery().
DataHandler::setTablename ($ tblname) [inherited]
Set or overwrite the default table name
Parameters
in $tblname Default table name
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
in $level An optional severity level; message will only be displayed when it is at least of this level.
out $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get(), OutputHandler::outputLine(), and OutputHandler::outputRaw().
Referenced by _OWL::getLastWarning(), _OWL::setStatus(), _OWL::stackMessage(), and _OWL::traceback().
_OWL::stackMessage ($ level = OWL_WARNING) [protected, inherited]
Add the message for the latests status change to the document
See also
Document::addMessage()
Parameters
in $level Minimum severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References $_doc, _OWL::$severity, OWL::factory(), and _OWL::signal().
_OWL::succeeded ($ _ok = OWL_SUCCESS, &$ _object = null) [inherited]
Check if the object currenlty has a success state
Parameters
in $_ok The highest severity that's considered successfull, default OWL_SUCCESS
in $_object REference to the object to check, defaults to the current object
Returns
Boolean true when successfull
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::construct(), Dispatcher::registerArgument(), and Dispatcher::registerCallback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
out $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
in $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
Referenced by _OWL::check(), User::login(), and SessionHandler::read().
HDataHandler::writeQuery ($ query, $ line) [private]
Internal helper method to execute a write query
Parameters
in $query Query to execute
in $line Line number from which this method is called
Returns
Number of lines written, false on errors
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by addParent(), insertNode(), moveNode(), removeNode(), and removeTree().
Member Data Documentation
HDataHandler::$left [private]
Field name of the Left position indicator. Defaults to 'lft'
DataHandler::$owl_database [protected, inherited]
An optional link to a database object. This has to be specified if the data needs to be written to or read from a dabatase.
DataHandler::$owl_tablename [protected, inherited]
All variable names are expected to be fields in a database as well. If a table name is not given, the default table name will be used. This is useful for datasets that come from only one database table. For datasets that are not read from or written to a database, the tablename can be null.
HDataHandler::$right [private]
Field name of the Right position indicator. Defaults to 'rgt'
_OWL::$severity [protected, inherited]
Severity level of the current object status
Referenced by _OWL::stackMessage().
HDataHandler::$xlink [private]
Name of the crosslink field to allow multiple parents
Referenced by getDirectChildren().
HDataHandler::$xlinkID [private]
Name if the primary key field, required for closslinks
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.datahandlerh.php