FormField Class Reference
Formfield.
Public Member Functions
__construct ()
setName ($_value)
setValue ($_value)
getType ()
Protected Member Functions
getGenericFieldAttributes ($_ignore=array())
Protected Attributes
$type
$name
$value
$disabled
$readonly
Detailed Description
Formfield. Abstract base class for Formfield elements
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Oct 19, 2010 -- O van Eijk -- initial version
Constructor & Destructor Documentation
FormField::__construct ()
Class constructor;
Reimplemented in FormFieldCheckbox, FormFieldFile, FormFieldRadio, FormFieldSelect, and FormFieldTextarea.
Referenced by FormFieldText::__construct(), and FormFieldButton::__construct().
Member Function Documentation
FormField::getGenericFieldAttributes ($ _ignore = array()) [protected]
Return the attributes for an HTML formfield in the ` attrib='value' [...]` format
Parameters
$\leftarrow$ $_ignore Array with attributes names that should be ignored, e.g. for a textarea, the value is not returned as an attribute.
Returns
Textstring with the HTML code
Referenced by FormFieldTextarea::getFieldCode(), FormFieldText::getFieldCode(), FormFieldRadio::getFieldCode(), FormFieldCheckbox::getFieldCode(), and FormFieldButton::getFieldCode().
FormField::getType ()
Give the field type
Returns
Field type
FormField::setName ($ _value)
Set the field name
Parameters
$\leftarrow$ $_value Field name
FormField::setValue ($ _value)
Set the field value
Parameters
$\leftarrow$ $_value Field value
Reimplemented in FormFieldCheckbox, FormFieldRadio, and FormFieldSelect.
Member Data Documentation
FormField::$disabled [protected]
Boolean indicating a disabled field when true
FormField::$name [protected]
Name of the formfield
FormField::$readonly [protected]
Boolean indicating a readonly field when true
FormField::$type [protected]
Field type
Reimplemented in FormFieldTextarea.
Referenced by FormFieldText::__construct(), and FormFieldButton::__construct().
FormField::$value [protected]
Field value
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/ui/class.formfield.php