Mail Class Reference
Mail class.
Public Member Functions
__construct ()
setSender ($addr)
setFrom ($addr)
setSubject ($subject)
setDate ($date=null)
setBody ($text)
addToBody ($text)
addTo ($addr)
addCc ($addr)
addBcc ($addr)
addHeaders (array $headers)
get ($item)
send ()
makeDisplayableAddress ($address, array $name)
getLastWarning ()
getStatus ()
getSeverity ($status=null)
succeeded ($_ok=OWL_SUCCESS, &$_object=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Protected Member Functions
init ()
setCallback ($_dispatcher)
setCallbackArgument (array $_arg)
getCallback ()
reset ()
saveStatus ()
restoreStatus ()
check (&$object, $level=OWL_WARNING)
setStatus ($status, $params=array())
setHighSeverity (&$object=null)
Protected Attributes
$severity
Private Member Functions
addRecipient ($addr)
Private Attributes
$driver
$mail
Detailed Description
Mail class.
Define an email for sending.
Author
Oscar van Eijk, Oveas Functionality Provider
Version
May 11, 2011 -- O van Eijk -- initial version
Constructor & Destructor Documentation
Mail::__construct ()
Class constructor; loads the maildriver
Author
Oscar van Eijk, Oveas Functionality Provider
References addHeaders(), get(), OWLloader::getDriver(), _OWL::init(), and _OWL::setStatus().
Member Function Documentation
Mail::addBcc ($ addr)
Check the given mail address and add it to the recipients list
Parameters
in $addr A (displayable) email address
Returns
Boolean; true on success. False indicates an invalid mail address
Author
Oscar van Eijk, Oveas Functionality Provider
References addRecipient(), _OWL::setStatus(), and verifyMailAddress().
Mail::addCc ($ addr)
Check the given mail address and add it to the recipients and the CC- list
Parameters
in $addr A (displayable) email address
Returns
Boolean; true on success. False indicates an invalid mail address
Author
Oscar van Eijk, Oveas Functionality Provider
References addRecipient(), _OWL::setStatus(), and verifyMailAddress().
Mail::addHeaders (array $ headers)
Add one or more headers to this mail. Headers that already exist will be overwritten.
Parameters
in $headers Indexed array with the header info in the format (header => value)
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by __construct().
Mail::addRecipient ($ addr) [private]
Add an email address to the list of recipients. This list is for use by the SMTP driver only and will not appear in the headers
Parameters
in $addr A validated email address
Returns
Boolean; true on success. False indicates an invalid mail address
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by addBcc(), addCc(), and addTo().
Mail::addTo ($ addr)
Check the given mail address and add it to the recipients and the To- list
Parameters
in $addr A (displayable) email address
Returns
Boolean; true on success. False indicates an invalid mail address
Author
Oscar van Eijk, Oveas Functionality Provider
References addRecipient(), _OWL::setStatus(), and verifyMailAddress().
Mail::addToBody ($ text)
Add text to the mailbody
Parameters
in $text Mail text
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::check (&$ object, $ level = OWL_WARNING) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
in $object Pointer to an object to check against
in $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::reset(), _OWL::setHighSeverity(), and _OWL::traceback().
Referenced by SessionHandler::write().
Mail::get ($ item)
Get previously set data from the email
Parameters
in $item One of the items as specified in MailDriver::mailSend()
Returns
Item value, or null if it does not exist
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by __construct().
_OWL::getCallback () [protected, inherited]
Retrieve a previously set (callback) dispatcher. The (callback) dispatcher is cleared immediatly.
Returns
The dispatcher, of null on failure.
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in Dispatcher .
References OWL::factory().
_OWL::getLastWarning () [inherited]
Get the last warning or error message.
Returns
null if there was no error (severity below OWL_WARNING), otherwise the error text.
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
_OWL::getSeverity ($ status = null) [inherited]
Get the current object severity level.
Parameters
in $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::$status.
Referenced by LogHandler::composeMessage(), LogHandler::log(), and DataHandler::setKey().
_OWL::getStatus () [final, inherited]
Get the current object status.
Returns
Object's status code
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by SchemeHandler::compare().
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory(), and _OWL::setStatus().
Referenced by FormFieldPlugin::__construct(), Tablerow::__construct(), Tablecell::__construct(), Table::__construct(), Document::__construct(), ContainerPlugin::__construct(), Container::__construct(), SocketHandler::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), OWL::__construct(), __construct(), Group::__construct(), Form::__construct(), Dispatcher::__construct(), and User::construct().
Mail::makeDisplayableAddress ($ address, array $ name)
Create a displayable email address based on name and mail address info. Refer to MailDriver::mailSend() for an explanation what I mean with 'displayable'.
Parameters
in $address Email address
in $name Indexed array with either 1 key ('name') holding the full name, or one or more seperate keys for first name ('fname'), middle name ('mname') and last name ('lname') that will be checked and combined
Returns
Displayable mail address in the format `Personal name <email@example.org>`
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in DbHandler , and SchemeHandler .
References _OWL::resetCalltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::setStatus().
_OWL::restoreStatus () [protected, inherited]
Restore the previously saved status object and destroy the copy
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Referenced by User::logout().
_OWL::saveStatus () [protected, inherited]
Create a copy of the status object
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::logout().
Mail::send ()
Call the maildriver's mailSend() method and check the result.
Returns
Object severity
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus().
Mail::setBody ($ text)
Set the body for the email
Parameters
in $text Mail text
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::setCallback ($ _dispatcher) [protected, inherited]
Set a dispatcher for later callback
Parameters
in $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher()
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
_OWL::setCallbackArgument (array $ _arg) [protected, inherited]
Add an argument to a previously registered callback dispatcher
Parameters
in $_arg Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
Referenced by User::register().
Mail::setDate ($ date = null)
Set the maildate, if it should not be the actual timestamp
Parameters
in $date Date, oir null to use the actual
Author
Oscar van Eijk, Oveas Functionality Provider
Mail::setFrom ($ addr)
Check and set the from address
Parameters
in $addr A (displayable) email address
Returns
Boolean; true on success. False indicates an invalid mail address
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::setStatus(), and verifyMailAddress().
Referenced by setSender().
_OWL::setHighSeverity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
Mail::setSender ($ addr)
Check and set the Sender address as it appears in the header. It no from address is set yet, this method will also set the same address for the from SMTP command by calling setFrom()
Parameters
in $addr A (displayable) email address
Returns
Boolean; true on success. False indicates an invalid mail address
Author
Oscar van Eijk, Oveas Functionality Provider
References setFrom(), _OWL::setStatus(), and verifyMailAddress().
_OWL::setStatus ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
in $status OWL status code
in $params
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::getCode(), _OWL::reset(), and _OWL::signal().
Referenced by DbHandler::__clone(), Container::__construct(), SocketHandler::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), Session::__construct(), __construct(), BaseElement::_getContent(), addBcc(), addCc(), Form::addField(), FormFieldRadioPlugin::addOption(), addTo(), BaseElement::addToContent(), DbHandler::alt(), SchemeHandler::alterScheme(), FileHandler::close(), DbHandler::commitTransaction(), Dispatcher::composeDispatcher(), User::confirm(), SocketHandler::connect(), DbHandler::connect(), DbHandler::create(), SchemeHandler::createScheme(), SchemeHandler::defineIndex(), SchemeHandler::defineScheme(), SocketHandler::disconnect(), Dispatcher::dispatch(), FormHandler::get(), DataHandler::get(), SchemeHandler::getTableColumns(), SchemeHandler::getTableIndexes(), _OWL::init(), Document::loadScript(), Document::loadStyle(), User::login(), FileHandler::open(), DbHandler::open(), LogHandler::openLogfile(), DataHandler::prepare(), DbHandler::prepareDelete(), DbHandler::prepareField(), DbHandler::prepareInsert(), DbHandler::prepareRead(), DbHandler::prepareUpdate(), SocketHandler::read(), DbHandler::read(), FileHandler::readLine(), User::readUserdata(), User::register(), Dispatcher::registerArgument(), Dispatcher::registerCallback(), _OWL::restoreStatus(), DbHandler::rollbackTransaction(), SchemeHandler::scheme(), send(), FormHandler::set(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), Document::setFavicon(), Form::setFieldAttributes(), setFrom(), DataHandler::setJoin(), DataHandler::setKey(), FormFieldTextPlugin::setMaxsize(), Document::setMeta(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), setSender(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), Form::showField(), DbHandler::startTransaction(), SchemeHandler::tableDescription(), SchemeHandler::validateScheme(), SocketHandler::write(), and DbHandler::write().
Mail::setSubject ($ subject)
Set the mail subject
Parameters
in $subject Subject line
Author
Oscar van Eijk, Oveas Functionality Provider
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
in $level An optional severity level; message will only be displayed when it is at least of this level.
out $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
Referenced by _OWL::getLastWarning(), _OWL::setStatus(), and _OWL::traceback().
_OWL::succeeded ($ _ok = OWL_SUCCESS, &$ _object = null) [inherited]
Check if the object currenlty has a success state
Parameters
in $_ok The highest severity that's considered successfull, default OWL_SUCCESS
in $_object REference to the object to check, defaults to the current object
Returns
Boolean true when successfull
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::construct(), Dispatcher::registerArgument(), and Dispatcher::registerCallback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
out $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
in $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
Author
Oscar van Eijk, Oveas Functionality Provider
References _OWL::signal().
Referenced by _OWL::check(), User::login(), and SessionHandler::read().
Member Data Documentation
Mail::$driver [private]
Mail driver object
Mail::$mail [private]
Array defining the mail. This is an indexed array; see MailDriver::mailSend() for the layout
_OWL::$severity [protected, inherited]
Severity level of the current object status
Referenced by DbHandler::commitTransaction(), DbHandler::rollbackTransaction(), and DbHandler::startTransaction().
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/bo/class.mail.php