Tablerow Class Reference
Tablerow.
Public Member Functions
__construct ()
addCell ($_content= '&nbsp;', array $_attribs=array())
showElement ()
setId ($_value)
getId ()
setName ($_value)
setStyle ($_value)
setClass ($_value)
setContent (&$_content)
addToContent (&$_content)
getContent ()
setEvent ($_event, $_action, $_add=false)
setAttributes (array $_attribs)
get_status ()
get_severity ($status=null)
succeeded ($_ok=OWL_SUCCESS, &$_object=null)
signal ($level=OWL_INFO, &$text=false)
traceback (&$text=false, $depth=0)
Protected Member Functions
getAttributes (array $_ignore=array())
init ()
set_callback ($_dispatcher)
set_callback_argument (array $_arg)
get_callback ()
reset ()
save_status ()
restore_status ()
check (&$object, $level=OWL_WARNING)
set_status ($status, $params=array())
set_high_severity (&$object=null)
Protected Attributes
$class = ''
$style = ''
$events = array()
$name = ''
$id = ''
$severity
Private Attributes
$cells = array()
Detailed Description
Tablerow. Class for Table row elements
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Jan 9, 2011 -- O van Eijk -- initial version
Constructor & Destructor Documentation
Tablerow::__construct ()
Class constructor;
References _OWL::init().
Member Function Documentation
Tablerow::addCell ($ _content = '&nbsp;', array $ _attribs = array())
Add a new tablecell
Parameters
[in] $_content HTML code that will be placed in the cell
[in] $_attribs An optional array with HTML attributes
Returns
Reference to the cell object
BaseElement::addToContent (&$ _content) [inherited]
Add a content to the container. If the container is not an array yet, it will be converted to obe.
Parameters
[in] $_content Reference to the content, which can be HTML code or an object, of which the showElement() method will be called to retrieve the HTML.
References _OWL::set_status().
_OWL::check (&$ object, $ level = OWL_WARNING) [protected, inherited]
This is a helper function for lazy developers. Some checks have to be made quite often, this is a kinda macro to handle that. It compares the own severity level with that of a given object. If the highest level is above a given max, a traceback and reset are performed.
Parameters
[in] $object Pointer to an object to check against
[in] $level The maximum severity level
Returns
True if the severity level was correct (below the max), otherwise false
References _OWL::reset(), _OWL::set_high_severity(), and _OWL::traceback().
Referenced by SessionHandler::write().
_OWL::get_callback () [protected, inherited]
Retrieve a previously set (callback) dispatcher. The (callback) dispatcher is cleared immediatly.
Returns
The dispatcher, of null on failure.
Reimplemented in Dispatcher.
References OWL::factory().
_OWL::get_severity ($ status = null) [inherited]
Get the current object severity level.
Parameters
[in] $status An optional parameter to check an other status code i.s.o the object's current status.
Returns
Status severity level
References _OWL::$status.
Referenced by LogHandler::compose_message(), LogHandler::log(), and DataHandler::set_key().
_OWL::get_status () [final, inherited]
Get the current object status.
Returns
Object's status code
Referenced by SchemeHandler::compare().
BaseElement::getAttributes (array $ _ignore = array()) [protected, inherited]
Return the general element attributes that are set
Parameters
[in] $_ignore Array with attributes names that should be ignored
Returns
string attributes in HTML format (' fld=`value`...)
References BaseElement::getEvents().
Referenced by FormFieldPlugin::getGenericFieldAttributes(), Form::openForm(), showElement(), Tablecell::showElement(), Table::showElement(), Document::showElement(), and Container::showElement().
BaseElement::getContent () [inherited]
Get the content of the current container, which can be plain HTML, an object, or an array which can mix both types.
Returns
HTML code
References BaseElement::_getContent().
Referenced by Tablecell::showElement(), Document::showElement(), Container::showElement(), and Form::showElement().
BaseElement::getId () [inherited]
Get the element's HTML ID
Returns
The ID
Referenced by BaseElement::_getContent().
_OWL::init () [protected, inherited]
This function should be called by all constuctors. It initializes the general characteristics. Status is 'warning' by default, it's up to the contructor to set a proper status; if it's still 'warning', this *might* indicate something went wrong.
References OWL::factory(), and _OWL::set_status().
Referenced by FormFieldPlugin::__construct(), __construct(), Tablecell::__construct(), Table::__construct(), Document::__construct(), ContainerPlugin::__construct(), Container::__construct(), SessionHandler::__construct(), SchemeHandler::__construct(), LogHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), OWL::__construct(), Form::__construct(), Dispatcher::__construct(), and UserHandler::construct().
_OWL::reset () [protected, inherited]
General reset function for all objects. Should be called after each non-fatal error
Reimplemented in DbHandler, and SchemeHandler.
References _OWL::reset_calltree().
Referenced by _OWL::check(), SessionHandler::read(), DataHandler::reset(), and _OWL::set_status().
_OWL::restore_status () [protected, inherited]
Restore the previously saved status object and destroy the copy
References _OWL::set_status().
Referenced by UserHandler::logout().
_OWL::save_status () [protected, inherited]
Create a copy of the status object
Referenced by UserHandler::logout().
_OWL::set_callback ($ _dispatcher) [protected, inherited]
Set a dispatcher for later callback
Parameters
[in] $_dispatcher Dispatched,
See also
Dispatcher::composeDispatcher()
Returns
True on success, false on failure
References OWL::factory().
_OWL::set_callback_argument (array $ _arg) [protected, inherited]
Add an argument to a previously registered callback dispatcher
Parameters
[in] $_arg Argument, must be an array type. When non- arrays should be passed as arguments, the must be set when the callback is registered already
Returns
True on success, false on failure
References OWL::factory().
Referenced by UserHandler::register().
_OWL::set_high_severity (&$ object = null) [protected, inherited]
Compare the severity level of the current object with a given one and set my statuspointer to the object with the highest level.
Referenced by _OWL::check(), DataHandler::db(), DataHandler::prepare(), and SessionHandler::read().
_OWL::set_status ($ status, $ params = array ()) [final, protected, inherited]
Set the current object status to the specified value.
Parameters
[in] $status OWL status code
[in] $params
References $GLOBALS, _OWL::$status, ConfigHandler::get(), Register::get_code(), _OWL::reset(), and _OWL::signal().
Referenced by DbHandler::__clone(), Container::__construct(), SchemeHandler::__construct(), ImageHandler::__construct(), FormHandler::__construct(), FileHandler::__construct(), DbHandler::__construct(), DataHandler::__construct(), Session::__construct(), BaseElement::_getContent(), Form::addField(), FormFieldRadioPlugin::addOption(), BaseElement::addToContent(), DbHandler::alt(), SchemeHandler::alter_scheme(), FileHandler::close(), Dispatcher::composeDispatcher(), UserHandler::confirm(), User::confirm(), DbHandler::connect(), DbHandler::create(), SchemeHandler::create_scheme(), SchemeHandler::define_index(), SchemeHandler::define_scheme(), Dispatcher::dispatch(), FormHandler::get(), DataHandler::get(), SchemeHandler::get_table_columns(), SchemeHandler::get_table_indexes(), _OWL::init(), Document::loadScript(), Document::loadStyle(), UserHandler::login(), FileHandler::open(), DbHandler::open(), LogHandler::open_logfile(), DataHandler::prepare(), DbHandler::prepare_delete(), DbHandler::prepare_insert(), DbHandler::prepare_read(), DbHandler::prepare_update(), DbHandler::read(), FileHandler::read_line(), UserHandler::read_userdata(), User::register(), Dispatcher::register_argument(), Dispatcher::register_callback(), _OWL::restore_status(), SchemeHandler::scheme(), FormHandler::set(), DataHandler::set(), DataHandler::set_join(), DataHandler::set_key(), BaseElement::setAttributes(), BaseElement::setContent(), Form::setEncoding(), Document::setFavicon(), Form::setFieldAttributes(), FormFieldTextPlugin::setMaxsize(), Document::setMeta(), Form::setMethod(), FormFieldRadioPlugin::setSelected(), FormFieldTextPlugin::setSize(), FormFieldSelectPlugin::setSize(), FormFieldSelectPlugin::setValue(), Form::showField(), SchemeHandler::table_description(), SchemeHandler::validate_scheme(), and DbHandler::write().
BaseElement::setAttributes (array $ _attribs) [inherited]
Set the attributes of the DOM element by calling the 'set<Attrib>' method for this class.
Parameters
[in] $_attribs Array with attributes in the format attrib=>value
Returns
Severity level. The status increased when a set<Attrib> method does not exist.
References _OWL::set_status().
Referenced by Table::__construct(), Container::__construct(), and Form::__construct().
BaseElement::setClass ($ _value) [inherited]
Set the element Class
Parameters
[in] $_value Class name
BaseElement::setContent (&$ _content) [inherited]
Fill the content for a container. Existing content (e.g. set during instantiation) will be overwritten. If that is not desired, the addToContent method should be used instead.
Parameters
[in] $_content Reference to the content, which can be HTML code or an object, of which the showElement() method will be called to retrieve the HTML.
References _OWL::set_status().
Referenced by Tablecell::__construct(), and Container::__construct().
BaseElement::setEvent ($ _event, $ _action, $ _add = false) [inherited]
Add an event to the events array
Parameters
[in] $_event Javascript event name (onXxx)
[in] $_action Javascript function or code
[in] $_add Boolean; when true, the action will be added if the event name already exists. Default is false; overwrite the action for this event.
BaseElement::setId ($ _value) [inherited]
Set the element ID
Parameters
[in] $_value Identification
Referenced by BaseElement::setName().
BaseElement::setName ($ _value) [inherited]
Set the element name
Parameters
[in] $_value Element name
References BaseElement::setId().
BaseElement::setStyle ($ _value) [inherited]
Set the element style
Parameters
[in] $_value Element style
Tablerow::showElement ()
Get the HTML code to display the tablerow
Returns
string with the HTML code
Reimplemented from BaseElement.
References BaseElement::getAttributes().
_OWL::signal ($ level = OWL_INFO, &$ text = false) [inherited]
Display the message for the current object status
Parameters
[in] $level An optional severity level; message will only be displayed when it is at least of this level.
[out] $text If this parameter is given, the message text is returned in this string instead of echood.
Returns
The severity level for this object
References ConfigHandler::get().
Referenced by _OWL::set_status(), and _OWL::traceback().
_OWL::succeeded ($ _ok = OWL_SUCCESS, &$ _object = null) [inherited]
Check if the object currenlty has a success state
Parameters
[in] $_ok The highest severity that's considered successfull, default OWL_SUCCESS
[in] $_object REference to the object to check, defaults to the current object
Returns
Boolean true when successfull
Referenced by UserHandler::construct(), Dispatcher::register_argument(), and Dispatcher::register_callback().
_OWL::traceback (&$ text = false, $ depth = 0) [inherited]
If somehwere in the nested calls an error occured, we can traceback the original failing object with this function and signal the message.
Parameters
[out] $text Optional variable in which the message text can be stored. If not given, the text will be written to standard output
[in] $depth This paramater should be initially empty. It calculates the depth in recursive calls.
Returns
Severity code of the failing object
References _OWL::signal().
Referenced by _OWL::check(), UserHandler::login(), and SessionHandler::read().
Member Data Documentation
Tablerow::$cells = array() [private]
Array with pointers to the tablecell objects
BaseElement::$class = '' [protected, inherited]
Class specification
BaseElement::$events = array() [protected, inherited]
Array with javascript events
Referenced by Form::setFieldEvents().
BaseElement::$id = '' [protected, inherited]
Element ID
BaseElement::$name = '' [protected, inherited]
Name of the element
Referenced by Form::addField(), and Form::showField().
_OWL::$severity [protected, inherited]
Severity level of the current object status
BaseElement::$style = '' [protected, inherited]
Element style
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/ui/class.tablerow.php