OWLCache Class Reference
Cache handler.
Static Public Member Functions
static get ($cache, $key)
static set ($cache, $key, $value)
static loadCache ()
static saveCache ()
Static Private Member Functions
static init ()
Static Private Attributes
static $cache = null
Detailed Description
Cache handler.
Abstract class to handle all caching
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Apr 14, 2011 -- O van Eijk -- Initial version for OWL-PHP
Member Function Documentation
static OWLCache::get ($ cache, $ key) [static]
Get a value from cache
Parameters
in $cache Name of the cache array
in $key Key in the cache array
Returns
Value that was found, of null when nothing was found
Author
Oscar van Eijk, Oveas Functionality Provider
References $cache.
Referenced by Rights::__construct(), Rights::__wakeup(), OWLloader::_tryLoad(), ContentArea::hasRight(), LogHandler::logSession(), Register::registerLabels(), Register::registerMessages(), and DataHandler::setPrefix().
static OWLCache::init () [static, private]
Initialise the cache array with the predefined keys
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by set().
static OWLCache::loadCache () [static]
Load cached data
Todo Data caching is not yet implemented - this is a placeholder for future use
Author
Oscar van Eijk, Oveas Functionality Provider
static OWLCache::saveCache () [static]
Write data to te general cache
Todo Data caching is not yet implemented - this is a placeholder for future use
Author
Oscar van Eijk, Oveas Functionality Provider
static OWLCache::set ($ cache, $ key, $ value) [static]
Store a value in cache. Non existing cache arrays will dynamically be created
Parameters
in $cache Name of the cache array
in $key Key in the cache array
in $value Value to store
Returns
The given value is also returned
Author
Oscar van Eijk, Oveas Functionality Provider
References $cache, and init().
Referenced by OWLloader::_tryLoad(), User::construct(), Register::registerLabels(), Register::registerMessages(), and Rights::registerRights().
Member Data Documentation
OWLCache::$cache = null [static, private]
Array in which the cache data is stored
Referenced by get(), and set().
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.cache.php