OWLloader Class Reference
Class loader.
Static Public Member Functions
static getArea ($_classFile, $_classLocation)
static getDriver ($_driverName, $_driverType)
static getClass ($_className, $_classLocation=array(OWL_SO_INC, OWL_BO_INC, OWL_UI_INC), $_loadMultiple=false)
static getOWLId ()
Static Private Member Functions
static _tryLoad ($_className, $_classLocation)
Detailed Description
Class loader.
Abstract class to load other classfiles
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Oct 7, 2010 -- O van Eijk -- Initial version for OWL-PHP
Member Function Documentation
static OWLloader::_tryLoad ($ _className, $ _classLocation) [static, private]
Try loading a class from a specific location
Parameters
in $_className Name of the classfile
in $_classLocation Location where to tru loading it from
Returns
True on success
Author
Oscar van Eijk, Oveas Functionality Provider
References OWLCache::get(), and OWLCache::set().
Referenced by getClass().
static OWLloader::getArea ($ _classFile, $ _classLocation) [static]
Load a contentarea. This is done by calling the loadArea() method of the given class.
Parameters
in $_classFile Name of the classfile. This must the full filename without '.php' The name must be equal to the name of the class without 'Area in camelcase, so if the name of the classfile is 'myspot.php', the classname must be 'MyspotArea' and this argument must be 'myspot'
in $_classLocation Full path specification (can be as a constant) where the file can be found
Returns
Reference to the object which is an instantiation of the class, null on erros
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::stat().
static OWLloader::getClass ($ _className, $ _classLocation = array(OWL_SO_INC, OWL_BO_INC, OWL_UI_INC), $ _loadMultiple = false) [static]
Load a PHP classfile
Parameters
in $_className Name of the class; either file full name (<filename.php> or the identifying name ([class.]<name>[.php])
in $_classLocation (Array of) location(s) where to look for the class
in $_loadMultiple Boolean; by default, the first matching classname will be loaded. Set this to true to load all files with the same name from multiple locations
Returns
True on success
Author
Oscar van Eijk, Oveas Functionality Provider
Examples:
exa.form.php.
References _tryLoad().
Referenced by Container::__construct(), Form::addField(), Dispatcher::dispatch(), and getDriver().
static OWLloader::getDriver ($ _driverName, $ _driverType) [static]
Load a driverfile
Parameters
in $_driverName Name of the class. Will be converted to lowercase to find the classfile
in $_driverType Driver type, must match the directoryname in OWL_DRIVERS where the classfile can be found, and the filenams for the interface (class.<driverType>driver.php) and abstract default class (class.<driverType>defaults.php) if they exist.
Returns
True on success
Author
Oscar van Eijk, Oveas Functionality Provider
References getClass().
Referenced by Mail::__construct(), and DbHandler::loadDriver().
static OWLloader::getOWLId () [static]
Read OWL's own ID from the database
Returns
Application code for OWL
Author
Oscar van Eijk, Oveas Functionality Provider
References ConfigHandler::get().
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/OWLloader.php