OWLException Class Reference
Exception handler.
Public Member Functions
__construct ($msg=null, $code=0, OWLException $caller=null)
get_trace ()
stack_dump ($textmode=true)
Public Attributes
$thrown_code
Private Member Functions
check_hide ($trace)
traceback ($trace, $step, $textmode)
Private Attributes
$caller
$hidden_args
Detailed Description
Exception handler.
Extend the default PHP Exception handler .
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Jul 29, 2008 -- O van Eijk -- Initial version
Constructor & Destructor Documentation
OWLException::__construct ($ msg = null, $ code = 0, OWLException $ caller = null)
Create the Exception handler object
Parameters
in $msg Message text
in $code Code of the event
in $caller Backlink to the calling object
References $caller, and ConfigHandler::get().
Member Function Documentation
OWLException::check_hide ($ trace) [private]
Check if this traced call has arguments that should be hidden in the stackdump.
Parameters
in $trace The call
Returns
integer holding the argument index that should be hidden, of -1 if nothing has to be hidden.
References ConfigHandler::get().
Referenced by traceback().
OWLException::get_trace ()
Trace back the previous object in the stack
Referenced by stack_dump().
OWLException::stack_dump ($ textmode = true)
Create an overview of the calling stack
Parameters
in $textmode specify the format in which the stackdump should be returned; text (true, default) of HTML (false).
References Register::get_code(), Register::get_severity(), get_trace(), and traceback().
Referenced by OWLExceptionHandler::log_exception().
OWLException::traceback ($ trace, $ step, $ textmode) [private]
Trace a single call from the stack
Parameters
in $trace The call
in $step Number of the call
in $textmode True if the stackdump is created as ASCII text, False for HTML
References check_hide(), and ConfigHandler::get().
Referenced by stack_dump().
Member Data Documentation
OWLException::$caller [private]
Backlink to the calling object
Referenced by __construct().
OWLException::$hidden_args [private]
Array with function call info of which arguments should be hidden
OWLException::$thrown_code
Store the error code to allow the logger to retrieve it
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.exceptionhandler.php