OWLExceptionHandler Class Reference
Default exception handler.
Static Public Member Functions
static logException (OWLException $exception)
static handleException (OWLException $exception)
Detailed Description
Default exception handler.
Establish a default exception handler. En exception is thrown whenever a status is set above a specified severity level. These exceptions are caught only by this default handler
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Jul 29, 2008 -- O van Eijk -- Initial version
Member Function Documentation
static OWLExceptionHandler::handleException (OWLException $ exception) [static]
Catch an uncaught exception
Parameters
in $exception The exception
Author
Oscar van Eijk, Oveas Functionality Provider
References logException().
static OWLExceptionHandler::logException (OWLException $ exception) [static]
Show the stackdump of an exception
Parameters
in $exception The exception
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, OWL::factory(), ConfigHandler::get(), and OWLException::stackDump().
Referenced by handleException().
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/kernel/so/class.exceptionhandler.php