MySQL Class Reference
Database driver.
Public Member Functions
__construct ()
dbCreate (&$_resource, $_name)
dbError (&$_resource, &$_number, &$_text)
dbConnect (&$_resource, $_server, $_name, $_user, $_password, $_multiple=false)
dbOpen (&$_resource, $_server, $_name, $_user, $_password)
dbTransactionCommit (&$_resource, $_name, $_name=null, $_new=false)
dbTransactionRollback (&$_resource, $_name, $_name=null, $_new=false)
dbTableList (&$_resource, $_pattern, $_views=false)
dbExec (&$_resource, $_statement)
dbRead (&$_data, &$_resource, $_query)
dbWrite (&$_resource, $_query)
dbInsertId (&$_resource, $_table, $_field)
dbRowCount (&$_data)
dbFetchNextRecord (&$_data)
dbClear (&$_data)
dbClose (&$_resource)
dbEscapeString ($_string)
functionIf ($_field, array $_arguments=array())
functionIfnull ($_field, array $_arguments=array())
functionConcat ($_field, array $_arguments=array())
__constructor ()
dbTransactionStart (&$_resource, $_name=null)
dbUnescapeString ($_string)
functionCount ($_field, array $_arguments=array())
dbTransactionStart (&$_resource, $_name=null)
dbUnescapeString ($_string)
functionCount ($_field, array $_arguments=array())
Detailed Description
Database driver.
Abstract class that defines the database drivers
See also
class DbDriver
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Apr 12, 2011 -- O van Eijk -- initial version
Constructor & Destructor Documentation
MySQL::__construct ()
Constructor; must exist but can be empty
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
Member Function Documentation
DbDefaults::__constructor () [inherited]
Class constructor
Author
Oscar van Eijk, Oveas Functionality Provider
MySQL::dbClear (&$ _data)
Clear a dataset
Parameters
in $_data as returned by DbDriver::dbRead()
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
Referenced by dbTableList().
MySQL::dbClose (&$ _resource)
Close a database connection
Parameters
in $_resource Link with the database server
Returns
True on success, false on failures
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
MySQL::dbConnect (&$ _resource, $ _server, $ _name, $ _user, $ _password, $ _multiple = false)
Make a connection with a database server
Parameters
out $_resource Link with the database server
in $_server Server to connect to
in $_name Database name to open
in $_user Username to connect with
in $_password Password to connect with
in $_multiple True when multiple connections are allowed, default is false
Returns
True on success, false on failures
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
MySQL::dbCreate (&$ _resource, $ _name)
Create a new database
Parameters
in $_resource Link with the database server
in $_name Name of the new database
Returns
a negative value on failures, any other integer on success
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
References dbWrite().
MySQL::dbError (&$ _resource, &$ _number, &$ _text)
Get the last error number and error text from the database server
Parameters
in $_resource Link with the database server
out $_number Error number
out $_text Error text
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
MySQL::dbEscapeString ($ _string)
Escape a given string for use in queries
Parameters
in $_string The input string
Returns
String in SQL safe format
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from DbDefaults .
MySQL::dbExec (&$ _resource, $ _statement)
Execute a database statement that does not return any value
Parameters
in $_resource Link with the database server
in $_statement Statement to execute
Returns
True on success, false on failures
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
Referenced by dbTransactionCommit(), and dbTransactionRollback().
MySQL::dbFetchNextRecord (&$ _data)
Get the next record from a dataset
Parameters
in $_data as returned by DbDriver::dbRead()
Returns
Record as an associative array (fieldname => fieldvalue)
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
Referenced by dbTableList().
MySQL::dbInsertId (&$ _resource, $ _table, $ _field)
Retrieve the last auto generated ID value
Parameters
in $_resource Link with the database server
in $_table Table to take the value from
in $_field Name of the Auto field
Returns
The last generated ID, or 0 when not found
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
MySQL::dbOpen (&$ _resource, $ _server, $ _name, $ _user, $ _password)
Open a database
Parameters
in,out $_resource Link with the database server
in $_server Server to connect to
in $_name Database name to open
in $_user Username to connect with
in $_password Password to connect with
Returns
True on success, false on failures
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
MySQL::dbRead (&$ _data, &$ _resource, $ _query)
Read from the database
Parameters
out $_data Dataset retrieved by the given query
in $_resource Link with the database server
in $_query Query to execute
Returns
True on success, false on failures
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
Referenced by dbTableList().
MySQL::dbRowCount (&$ _data)
Get the number of rows in a dataset
Parameters
in $_data as returned by DbDriver::dbRead()
Returns
Number of rows in the set
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
MySQL::dbTableList (&$ _resource, $ _pattern, $ _views = false)
Get a list with tablenames
Parameters
in $_resource Link with the database server
in $_pattern Search pattern
in $_views True when views should be included. Default is false
Returns
Indexed array with matching tables and their attributes
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
References dbClear(), dbFetchNextRecord(), and dbRead().
MySQL::dbTransactionCommit (&$ _resource, $ _name, $ _name = null, $ _new = false)
Open a new transaction
Parameters
in $_resource Link with the database server
in $_name Transaction name for databases that support named transactions
in $_new Boolean, true when a new transaction should be started after the commit
Returns
True on success, false on failures
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from DbDefaults .
References dbExec().
MySQL::dbTransactionRollback (&$ _resource, $ _name, $ _name = null, $ _new = false)
Open a new transaction
Parameters
in $_resource Link with the database server
in $_name Transaction name for databases that support named transactions
in $_new Boolean, true when a new transaction should be started after the rollback
Returns
True on success, false on failures
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented from DbDefaults .
References dbExec().
DbDefaults::dbTransactionStart (&$ _resource, $ _name = null) [inherited]
Open a new transaction
Parameters
in $_resource Link with the database server
in $_name Transaction name for databases that support named transactions
Returns
True on success, false on failures
Author
Oscar van Eijk, Oveas Functionality Provider
DbDriver::dbTransactionStart (&$ _resource, $ _name = null) [inherited]
Open a new transaction
Parameters
in $_resource Link with the database server
in $_name Transaction name for databases that support named transactions
Returns
True on success, false on failures
Author
Oscar van Eijk, Oveas Functionality Provider
DbDefaults::dbUnescapeString ($ _string) [inherited]
Unescape a string fthat is formatted for use in SQL
Parameters
in $_string The input string in SQL safe format
Returns
String without SQL formatting
Author
Oscar van Eijk, Oveas Functionality Provider
DbDriver::dbUnescapeString ($ _string) [inherited]
Unescape a string fthat is formatted for use in SQL This method is implemented by class DbDefaults
Parameters
in $_string The input string in SQL safe format
Returns
String without SQL formatting
Author
Oscar van Eijk, Oveas Functionality Provider
MySQL::dbWrite (&$ _resource, $ _query)
Write to the database
Parameters
in $_resource Link with the database server
in $_query Query to execute
Returns
Number of affected rows, or -1 on failures
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
Referenced by dbCreate().
MySQL::functionConcat ($ _field, array $ _arguments = array())
Inplementation of the SQL CONCAT() function.
Parameters
in $_field Name of the field
in $_arguments Array with arguments. The array should have 1 element, which is the value that will be concatenaterd to $_field. Note for literal string values this field must be quoted, e.g. `'value'`!
Returns
Complete SQL function code
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
DbDriver::functionCount ($ _field, array $ _arguments = array()) [inherited]
Inplementation of the SQL COUNT() function.
Parameters
in $_field Name of the field
in $_arguments Array with arguments, which is required by syntax
Returns
Complete SQL function code
Author
Oscar van Eijk, Oveas Functionality Provider
DbDefaults::functionCount ($ _field, array $ _arguments = array()) [inherited]
Inplementation of the SQL COUNT() function.
Parameters
in $_field Name of the field
in $_arguments Array with arguments, which is required by syntax
Returns
Complete SQL function code
Author
Oscar van Eijk, Oveas Functionality Provider
MySQL::functionIf ($ _field, array $ _arguments = array())
Inplementation of the SQL IF() function.
Parameters
in $_field Name of the field
in $_arguments Array with arguments. This array should be in the format (check, value, then, else), e.g. array('<', 5 , 'Less then 5', '5 or more')
Returns
Complete SQL function code
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
MySQL::functionIfnull ($ _field, array $ _arguments = array())
Inplementation of the SQL IFNULL() function.
Parameters
in $_field Name of the field
in $_arguments Array with arguments. The array should have 1 element, which is the default value when $_field is empty. Note for literal string values this field must be quoted, e.g. `'value'`!
Returns
Complete SQL function code
Author
Oscar van Eijk, Oveas Functionality Provider
Implements DbDriver .
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/src/drivers/database/class.mysql.php