/home/oscar/projects/owl-php/src/lib/contrib/enabled/formtable.helpers.php File Reference
Functions
addFormRow (Container &$table, Form &$form, $fieldType, $fieldName, $fieldValue, array $fieldAttributes, $label, array $labelAttributes)
Detailed Description
This file provides some helper functions for lazy developers like me setting up form tables
Version
Id:
formtable.helpers.php,v 1.1 2011-05-18 12:03:49 oscar Exp
Author
Oscar van Eijk, Oveas Functionality Provider
Function Documentation
addFormRow (Container &$ table, Form &$ form, $ fieldType, $ fieldName, $ fieldValue, array $ fieldAttributes, $ label, array $ labelAttributes)
This function adds a new table row to an exising form with 2 cells; in the right cell a new formfield that is created as well, left the label that should be displayed. To make sure no mistakes are made in the long list of arguments, no defaults are accepted.
Parameters
in $table Reference to the table container object to which the row is added
in $form Reference to the form object to which the field is added
in $fieldType Form field type (text, password, textarea etc)
in $fieldName Name of the field as it will appear in the form
in $fieldValue Optional fieldvalue
in $fieldAttributes Optional HTML attributes for the field
in $label Label as it will appear in the form (must be translated already!)
in $labelAttributes Optional HTML attributes for the label
Author
Oscar van Eijk, Oveas Functionality Provider
References Container::addContainer(), Form::addField(), and Form::showField().