/home/oscar/projects/owl-php/src/index.php File Reference
Enumerations
enum OWL_ROOT
Variables
if(!OWLloader::getClass('form')) $LoginForm = new Form('applic#include-path#classfile#class#method')
$_form = OWL::factory('FormHandler')
$_user = new User()
switch ($_form->get('act'))
$_scheme = SchemeHandler::get_instance()
$_table
$_index
$_t = serialize($_data['columns'])
Detailed Description
This is the entry point for OWL-PHP teststub
Version
Id:
index.php,v 1.12 2011-04-06 14:42:16 oscar Exp
Enumeration Type Documentation
enum OWL_ROOT
Variable Documentation
$_form = OWL::factory('FormHandler')
Referenced by Dispatcher::dispatch().
$_index
Initial value:
 array (
         'name' => array(
                         'columns' => array ('name')
                        ,'primary' => false
                        ,'unique' => false
                        ,'type' => null
        )
        ,'address' => array(
                         'columns' => array ('address')
                        ,'primary' => false
                        ,'unique' => false
                        ,'type' => 'FULLTEXT'
        )
)
Referenced by SchemeHandler::define_index(), and SchemeHandler::get_table_indexes().
$_scheme = SchemeHandler::get_instance()
Referenced by SchemeHandler::define_scheme().
$_t = serialize($_data['columns'])
Referenced by DbHandler::expand_field(), DbHandler::extract_tablelist(), and DataHandler::prepare().
$_table
Referenced by ConfigHandler::config_table(), DbHandler::extract_tablelist(), DataHandler::prepare(), and DbHandler::tablelist().
$_user = new User()
Referenced by ConfigHandler::config_table(), and MySQL::dbConnect().
if (!OWLloader::getClass('form')) $LoginForm = new Form('applic#include-path#classfile#class#method')
switch($_form->get('act'))