/home/oscar/projects/owl-php/src/lib/owl.debug.functions.php File Reference
Enumerations
Application debug level
These constants define the debug bits that can be used by the application
enum OWLDEBUG_APP_VAR
enum OWLDEBUG_APP_OBJ
enum OWLDEBUG_APP_FUN
enum OWLDEBUG_APP_BLK
enum OWLDEBUG_APP_LOOP
enum OWLDEBUG_APP_SQL
enum OWLDEBUG_APP_RET
enum OWLDEBUG_APP_RES
enum OWLDEBUG_APP_S01
enum OWLDEBUG_APP_S02
enum OWLDEBUG_APP_S03
enum OWLDEBUG_APP_S04
enum OWLDEBUG_APP_S05
enum OWLDEBUG_APP_S06
enum OWLDEBUG_APP_S07
enum OWLDEBUG_APP_S08
OWL debug levels
< Special 8, reserved for the application
These constants define the debug bits that are used by OWL
enum OWLDEBUG_OWL_VAR
enum OWLDEBUG_OWL_OBJ
enum OWLDEBUG_OWL_FUN
enum OWLDEBUG_OWL_BLK
enum OWLDEBUG_OWL_LOOP
enum OWLDEBUG_OWL_SQL
enum OWLDEBUG_OWL_RET
enum OWLDEBUG_OWL_RES
enum OWLDEBUG_OWL_S01
enum OWLDEBUG_OWL_S02
enum OWLDEBUG_OWL_S03
enum OWLDEBUG_OWL_S04
enum OWLDEBUG_OWL_S05
enum OWLDEBUG_OWL_S06
enum OWLDEBUG_OWL_S07
enum OWLDEBUG_OWL_S08
Functions
OWLdbg_traceCall ($shiftUp)
OWLdbg_add ($level, &$var, $name= 'Unknown variable', $shiftUp=0)
OWLdbg_show ()
Variables
$GLOBALS ['OWLDebugData'] = array()
Detailed Description
This file defines helper functions in debug mode
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Id:
owl.debug.functions.php,v 1.1 2010-12-03 12:07:42 oscar Exp
Enumeration Type Documentation
enum OWLDEBUG_APP_BLK
< Debug at function level
enum OWLDEBUG_APP_FUN
< Dump object contents
enum OWLDEBUG_APP_LOOP
< Debug at block leven within a function
enum OWLDEBUG_APP_OBJ
< Show contents of variables
enum OWLDEBUG_APP_RES
< Show return value
enum OWLDEBUG_APP_RET
< Show SQL statements
enum OWLDEBUG_APP_S01
< Show results of a statement
enum OWLDEBUG_APP_S02
< Special 1, reserved for the application
enum OWLDEBUG_APP_S03
< Special 2, reserved for the application
enum OWLDEBUG_APP_S04
< Special 3, reserved for the application
enum OWLDEBUG_APP_S05
< Special 4, reserved for the application
enum OWLDEBUG_APP_S06
< Special 5, reserved for the application
enum OWLDEBUG_APP_S07
< Special 6, reserved for the application
enum OWLDEBUG_APP_S08
< Special 7, reserved for the application
enum OWLDEBUG_APP_SQL
< Debug a loop (do/while/foreach etc)
enum OWLDEBUG_APP_VAR
enum OWLDEBUG_OWL_BLK
< Debug at function level
enum OWLDEBUG_OWL_FUN
< Dump object contents
enum OWLDEBUG_OWL_LOOP
< Debug at block leven within a function
enum OWLDEBUG_OWL_OBJ
< Show contents of variables
enum OWLDEBUG_OWL_RES
< Show return value
enum OWLDEBUG_OWL_RET
< Show SQL statements
enum OWLDEBUG_OWL_S01
< Show results of a statement
enum OWLDEBUG_OWL_S02
< Special 1 (reserved)
enum OWLDEBUG_OWL_S03
< Special 2 (reserved)
enum OWLDEBUG_OWL_S04
< Special 3 (reserved)
enum OWLDEBUG_OWL_S05
< Special 4 (reserved)
enum OWLDEBUG_OWL_S06
< Special 5 (reserved)
enum OWLDEBUG_OWL_S07
< Special 6 (reserved)
enum OWLDEBUG_OWL_S08
< Special 7 (reserved)
enum OWLDEBUG_OWL_SQL
< Debug a loop (do/while/foreach etc)
enum OWLDEBUG_OWL_VAR
Function Documentation
OWLdbg_add ($ level, &$ var, $ name = 'Unknown variable', $ shiftUp = 0)
Add information to the debug array. OWLdbg_traceCall() is called to find out from where this function was called.
Parameters
in $level Debug level. This is a single bit, the information will only be added if this bit is true in the debug config setting.
in $var Variable that will be dumped
in $name Information about the variable, e.g. the name.
in $shiftUp Number of levels to shift up (e.g. 1 for the caller's caller). Default 0
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS, ConfigHandler::get(), and OWLdbg_traceCall().
Referenced by BaseElement::_getContent(), DbHandler::prepareDelete(), DbHandler::prepareInsert(), DbHandler::prepareRead(), and DbHandler::prepareUpdate().
OWLdbg_show ()
Show the debug data that was filled during this run.
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
OWLdbg_traceCall ($ shiftUp)
Function to trace the location of the last OWLdbg_add() call. It uses the Exception class to trace the call.
Parameters
in $shiftUp When true, don't trace the caller, but the caller's caller.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by OWLdbg_add().
Variable Documentation
$GLOBALS['OWLDebugData'] = array()
< Special 8 (reserved) Array that will be filled with all debug information