/home/oscar/projects/owl-php/src/lib/owl.helper.functions.php File Reference
Functions
toBool ($_val, $_trueValues=array('yes', 'y', 'true', '1'), $_forceLowercase=true)
owlCrypt ($_string)
randomString ($_size, $_lowercase=false)
urlToPath ($_file)
urlExpand ($_file)
getReferer ($def= 'http://localhost/', $hostOnly=true)
verifyMailAddress ($email, $extract=true)
Detailed Description
This file defines general helper functions
Version
Id:
owl.helper.functions.php,v 1.10 2011-05-12 14:37:58 oscar Exp
Author
Oscar van Eijk, Oveas Functionality Provider
Function Documentation
getReferer ($ def = 'http://localhost/', $ hostOnly = true)
Get the current requests refering page
Parameters
in $def Default when no referer is found
in $hostOnly Boolean; true (default) when only the hostname should be returned
Returns
The HTTP referer
Author
Oscar van Eijk, Oveas Functionality Provider
Todo This function is based on the unreliable HTTP_REFERER... but what else can we use??
owlCrypt ($ _string)
Very basic encryption/decryption routine. This is not meant for critical data, but should be used only to hide non-critical info that must be transferred.
Parameters
in $_string The string to be encrypted or decrypted
Returns
Encrypted or decrypted string
Author
Oscar van Eijk, Oveas Functionality Provider
Todo Add a method to decrypt strings (dispatchers) that were crypted ad a remote server (using keyrings)
References ConfigHandler::get().
Referenced by ConfigHandler::_set(), Dispatcher::composeDispatcher(), Dispatcher::decodeDispatcher(), and ConfigHandler::get().
randomString ($ _size, $ _lowercase = false)
Return a random string. The string will contain characters only (A-Z)
Parameters
in $_size The string size in characters
in $_lowercase Boolean that indicates the string should contain lowercase characters only. Default is uppercase only.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by User::register().
toBool ($ _val, $ _trueValues = array('yes', 'y', 'true', '1'), $ _forceLowercase = true)
Convert a given value to a strict boolean.
Parameters
in $_val Value to convert, can be any type
in $_trueValues Array with string values that should be considered 'true'. Defaults to 'yes', 'y', 'true' and '1'
in $_forceLowercase Compare the input in lowercase only, defaults to true.
Returns
Strict boolean value
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by Security::controlBitmap(), DbHandler::loadDriver(), ConfigHandler::readConfig(), FormFieldCheckboxPlugin::setChecked(), FormFieldPlugin::setDisabled(), FormFieldSelectPlugin::setMultiple(), FormFieldPlugin::setReadonly(), and FormFieldSelectPlugin::setValue().
urlExpand ($ _file)
Expand a given location to a fully qualified URL
Parameters
in $_file Location of the file, either a full URL or relative from the base url (the path MUST start with 'http(s)://' or '/'!)
Returns
Fully qualified URL, or null when the input is invalid
Author
Oscar van Eijk, Oveas Functionality Provider
References OWL::factory().
Referenced by Document::loadScript(), Document::loadStyle(), and Document::setFavicon().
urlToPath ($ _file)
Translate a fully specified URL to the path specification
Parameters
in $_file URL of the file
Returns
Path specification of the file, or null of the file is not on the local host
Author
Oscar van Eijk, Oveas Functionality Provider
References $GLOBALS.
Referenced by Document::loadScript(), Document::loadStyle(), and Document::setFavicon().
verifyMailAddress ($ email, $ extract = true)
See if the given string contants a valid email address. Refer to MailDriver::mailSend() for an explanation what I mean with 'displayable'.
Parameters
in $email String that contains the (displayable) mail address
in $extract Boolean, set to false when the email address must be exact (not extract from a displayable address)
Returns
The valid mail address or an empty string when none was found
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by Mail::addBcc(), Mail::addCc(), Mail::addTo(), Mail::setFrom(), and Mail::setSender().