<?php
/**
 * \file
 * This file creates the page footer
 * \author Oscar van Eijk, Oveas Functionality Provider
 */

/**
 * \ingroup TT_TTADMIN
 * Setup the contentarea hoPage footerUser menu
 * \author Oscar van Eijk, Oveas Functionality Provider
 * \version Nov 24, 2011 -- O van Eijk -- initial version
 */
class PagefooterArea extends ContentArea
{
	/**
	 * Show the pagefooter
	 * \param[in] $arg Not used here but required by ContentArea
	 */
	public function loadArea($arg = null)
	{
		$this->contentObject = new Container('div', array('class' => 'pageFooter'));
		$_c = 'Page generated by Terra-Terra';
		$this->contentObject->setContent($_c);
	}
}
