OTKTranslations_Messages Class Reference
Check message codes.
Public Member Functions
__construct ()
prepareTest ()
performTest ()
checkCodes ()
cleanupTest ()
getDetails ()
Private Member Functions
checkDirectory ($dir)
checkFile ($file)
Private Attributes
$messages
$details
$returnCodes
$statusCodes
$topLocation
$libLocation
$applCode
Detailed Description
Check message codes.
Check all messages codes that are registered with Register::registerCode() but not in the message file
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Jun 7, 2011 -- O van Eijk -- initial version
Constructor & Destructor Documentation
OTKTranslations_Messages::__construct ()
Class constuctor. All testcases must be implemented.
Author
Oscar van Eijk, Oveas Functionality Provider
Implements TestCase .
References OTKTranslations_applicCode(), OTKTranslations_libLocation(), and OTKTranslations_topLocation().
Member Function Documentation
OTKTranslations_Messages::checkCodes ()
Referenced by performTest().
OTKTranslations_Messages::checkDirectory ($ dir) [private]
References checkFile().
Referenced by performTest().
OTKTranslations_Messages::checkFile ($ file) [private]
Referenced by checkDirectory().
OTKTranslations_Messages::cleanupTest ()
Cleanup the testenvironment, e.g. drop temporary tables
Returns
OTK_RESULT_SUCCESS on success, OTK_RESULT_NONE when this testcase needs no cleanup or an error message when failed
Author
Oscar van Eijk, Oveas Functionality Provider
Implements TestCase .
OTKTranslations_Messages::getDetails ()
Gather all testdetails. During the tests, the testcase can collect all additional information in an internal datastructure, e.g. further details or explanations concerning failed tests. After finishing the testcase (and after cleanupTest()), the information will be retrieved.
Returns
Tekstblock, can contain HTML. Null and an empty textstring are allowed if no details are available.
Author
Oscar van Eijk, Oveas Functionality Provider
Implements TestCase .
OTKTranslations_Messages::performTest ()
Perform the test(s) for this testcase. Multiple tests can be performed, each writing a single message in an internal array explaining what the result was ('step X completed succefully', an error message in case of failures etc). Additional (private) methods can be created for each step.
Returns
A 2 dimensional array with messages for all steps that were performed in this testcase. Each step in the testcase has exactly 1 element in the array, being an array with 2 elements: first is the code as defined in Test result code, the second is an human readable message. null when the step was skipped, e.g.
        array(
                 array(OTK_RESULT_SUCCESS, 'Step 1 completed successfully')
                ,array(OTK_RESULT_SUCCESS, 'Step 2 completed successfully')
                ,array(OTK_RESULT_FAIL, 'Step 3 failed with code XX')
                ,array(OTK_RESULT_SKIPPED, 'Step 4 could not execute because step
       3 failed')
        )
Author
Oscar van Eijk, Oveas Functionality Provider
Implements TestCase .
References checkCodes(), and checkDirectory().
OTKTranslations_Messages::prepareTest ()
Prepare a testcase, e.g. create some database tables that are required for this testcase.
Returns
OTK_RESULT_SUCCESS on success, OTK_RESULT_NONE when this testcase needs no preparation or an error message when failed
Author
Oscar van Eijk, Oveas Functionality Provider
Implements TestCase .
Member Data Documentation
OTKTranslations_Messages::$applCode [private]
OTKTranslations_Messages::$details [private]
OTKTranslations_Messages::$libLocation [private]
OTKTranslations_Messages::$messages [private]
OTKTranslations_Messages::$returnCodes [private]
OTKTranslations_Messages::$statusCodes [private]
OTKTranslations_Messages::$topLocation [private]
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/owltestkit/testsets/translations/case.messages.php