TestSet Class Reference
Testset.
Public Member Functions
__construct ()
loadTestcases ($location)
performTests ()
Static Public Member Functions
static getDescription ()
Private Member Functions
doTest ($name, $file)
showTestResults ()
Private Attributes
$setName
$helper
$testCases
$details
$testResults
$errors
$warnings
$succeeded
$skipped
Detailed Description
Testset.
Baseclass that defines the testsets. Classes that derive from this baseclass must have the name OTK<Location>, where 'location' is the name of the subdirectory in OTK_TESTSETS. The filename must be testset.php.
The classes only need to reimplement the static getDescription() method, all other required methods are in this baseclass.
The class collects all files belonging to a testset that contain testcases and helper functions. All files must be in the same directory as testset.php.
Files that contain testcases must have the name case.<name>.php. Refer to the interface TestCase for more information.
Optionally, testset directories can contain a file with the name helper.php. This can be a file containing one or more classes or functions. That file will be included but not called; it is up to the testcases to make the proper calls to these files. In order prevent duplicate class or function names, it is a good practice to include the name of the testset in in all names.
Author
Oscar van Eijk, Oveas Functionality Provider
Version
May 19, 2011 -- O van Eijk -- initial version
Constructor & Destructor Documentation
TestSet::__construct ()
Class constructor
Author
Oscar van Eijk, Oveas Functionality Provider
Member Function Documentation
TestSet::doTest ($ name, $ file) [private]
Execute a single testcase
Parameters
in $name Name of the testcase
in $file Full path to the testcase file
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by performTests().
static TestSet::getDescription () [static]
This is the only required method that should be implemented by Testset classes; it shows a description of the testset.
Note
This method must be reimplemented, but it cannot be declared abstract since it is a static method. Since it is static, it does belong to the class itself, meaning this method here will never be called; it is included just for documentation purposes.
Returns
A textstring (HTML allowed) describing the testset
Author
Oscar van Eijk, Oveas Functionality Provider
Reimplemented in OTKDbdriver , OTKHdata , and OTKTranslations .
TestSet::loadTestcases ($ location)
Scan the testset directory for all files holeing either testcases (case.<name>.php) or helper functions or class (helper.php).
Parameters
in $location Directory to scan
Author
Oscar van Eijk, Oveas Functionality Provider
TestSet::performTests ()
Go through all selected testcases and execute them
Author
Oscar van Eijk, Oveas Functionality Provider
References doTest(), and showTestResults().
TestSet::showTestResults () [private]
Create the contentarea to display the results. To make sure we don't need to wait until all tests completed, the output is echoed immediatly.
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by performTests().
Member Data Documentation
TestSet::$details [private]
Details description of the testresults
TestSet::$errors [private]
Total number of teststeps that ended in an error
TestSet::$helper [private]
Full path to the helper file ('helper.php') if this set contains one
TestSet::$setName [private]
Name of the testset. It will be taken from the classname (without the leading 'OTK')
TestSet::$skipped [private]
Total number of teststeps that have been skipped
TestSet::$succeeded [private]
Total number of teststeps that completed successfull
TestSet::$testCases [private]
Indexed array holding all testcases found in this set
TestSet::$testResults [private]
Indexed array with the results of all steps per testcase
TestSet::$warnings [private]
Total number of teststeps that ended with a warning
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/owltestkit/bo/class.testset.php