TestKit Class Reference
Testset loader.
Public Member Functions
getTestSets ()
performTests ($testSet)
Static Public Member Functions
static getInstance ()
Private Member Functions
__construct ()
loadTestSet ($name)
getClassName ($setName)
Private Attributes
$sets
Static Private Attributes
static $instance
Detailed Description
Testset loader.
Singleton class that loads all testsets
Author
Oscar van Eijk, Oveas Functionality Provider
Version
May 19, 2011 -- O van Eijk -- initial version
Constructor & Destructor Documentation
TestKit::__construct () [private]
Class constructor; scan the testsets directory for subdirectories that can contain testsets, and load all testset - classfiles that have been found.
Author
Oscar van Eijk, Oveas Functionality Provider
References loadTestSet().
Member Function Documentation
TestKit::getClassName ($ setName) [private]
Translate the setname (taken from the directory name) into a classname in the required format
Parameters
in $setName Name of the set and directory
Returns
Classname
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by loadTestSet(), and performTests().
static TestKit::getInstance () [static]
Return a reference to my implementation. If necessary, create that implementation first.
Returns
Object instance ID
Author
Oscar van Eijk, Oveas Functionality Provider
References $instance.
TestKit::getTestSets ()
Return the available tests
Returns
Testsets as an indexed array in the format (name => description)
Author
Oscar van Eijk, Oveas Functionality Provider
TestKit::loadTestSet ($ name) [private]
Check if a directory contains a testset. If so, load the classfile and add the testset name and description to the internal array.
Parameters
in $name Name of the directory to check
Returns
null if the directory contains no valid testset, true when successfully loaded, false on errors.
Author
Oscar van Eijk, Oveas Functionality Provider
References getClassName().
Referenced by __construct().
TestKit::performTests ($ testSet)
Perform the testcases of a given testset
Parameters
in $testSet Testset to perform
Author
Oscar van Eijk, Oveas Functionality Provider
References getClassName().
Member Data Documentation
TestKit::$instance [static, private]
Self reference
Referenced by getInstance().
TestKit::$sets [private]
Indexed array with all testsets and their descriptions
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/owltestkit/so/class.testkit.php