OTKHdata_Nodehandling Class Reference
HData Node Testcase.
Public Member Functions
__construct ()
prepareTest ()
performTest ()
cleanupTest ()
getDetails ()
Private Member Functions
checkResult ($retVal, $data, $step, $stepDescription)
insertNodes ($node, $parent)
getExpected ($step)
Private Attributes
$hdatahandler
$details
$returnCodes
Detailed Description
HData Node Testcase.
This testcase does some node handling, like inserts, move and remove
Author
Oscar van Eijk, Oveas Functionality Provider
Version
May 26, 2011 -- O van Eijk -- initial version
Constructor & Destructor Documentation
OTKHdata_Nodehandling::__construct ()
Class constuctor. All testcases must be implemented.
Author
Oscar van Eijk, Oveas Functionality Provider
Implements TestCase .
References OTKHdata_tableName().
Member Function Documentation
OTKHdata_Nodehandling::checkResult ($ retVal, $ data, $ step, $ stepDescription) [private]
References OTKHelpers::compareTable(), and getExpected().
Referenced by performTest().
OTKHdata_Nodehandling::cleanupTest ()
Cleanup the testenvironment, e.g. drop temporary tables
Returns
OTK_RESULT_SUCCESS on success, OTK_RESULT_NONE when this testcase needs no cleanup or an error message when failed
Author
Oscar van Eijk, Oveas Functionality Provider
Implements TestCase .
OTKHdata_Nodehandling::getDetails ()
Gather all testdetails. During the tests, the testcase can collect all additional information in an internal datastructure, e.g. further details or explanations concerning failed tests. After finishing the testcase (and after cleanupTest()), the information will be retrieved.
Returns
Tekstblock, can contain HTML. Null and an empty textstring are allowed if no details are available.
Author
Oscar van Eijk, Oveas Functionality Provider
Implements TestCase .
OTKHdata_Nodehandling::getExpected ($ step) [private]
Referenced by checkResult().
OTKHdata_Nodehandling::insertNodes ($ node, $ parent) [private]
Referenced by performTest(), and prepareTest().
OTKHdata_Nodehandling::performTest ()
Perform the test(s) for this testcase. Multiple tests can be performed, each writing a single message in an internal array explaining what the result was ('step X completed succefully', an error message in case of failures etc). Additional (private) methods can be created for each step.
Returns
A 2 dimensional array with messages for all steps that were performed in this testcase. Each step in the testcase has exactly 1 element in the array, being an array with 2 elements: first is the code as defined in Test result code, the second is an human readable message. null when the step was skipped, e.g.
        array(
                 array(OTK_RESULT_SUCCESS, 'Step 1 completed successfully')
                ,array(OTK_RESULT_SUCCESS, 'Step 2 completed successfully')
                ,array(OTK_RESULT_FAIL, 'Step 3 failed with code XX')
                ,array(OTK_RESULT_SKIPPED, 'Step 4 could not execute because step
       3 failed')
        )
Author
Oscar van Eijk, Oveas Functionality Provider
Implements TestCase .
References checkResult(), insertNodes(), and OTKHdata_getData().
OTKHdata_Nodehandling::prepareTest ()
Prepare a testcase, e.g. create some database tables that are required for this testcase.
Returns
OTK_RESULT_SUCCESS on success, OTK_RESULT_NONE when this testcase needs no preparation or an error message when failed
Author
Oscar van Eijk, Oveas Functionality Provider
Implements TestCase .
References insertNodes().
Member Data Documentation
OTKHdata_Nodehandling::$details [private]
OTKHdata_Nodehandling::$hdatahandler [private]
OTKHdata_Nodehandling::$returnCodes [private]
The documentation for this class was generated from the following file:
/home/oscar/projects/owl-php/owltestkit/testsets/hdata/case.nodehandling.php