/home/oscar/projects/owl-php/owltestkit/testsets/dbdriver/helper.php File Reference
Functions
OTKDbdriver_tableName ()
Detailed Description
This file defines some helper functions for the DbDriver testset
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Id:
helper.php,v 1.2 2011-10-16 11:11:44 oscar Exp
Copyright:
2011 -- Oscar van Eijk, Oveas Functionality Provider
License:
This file is part of OTK.
OTK is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
OTK is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with OTK. If not, see http://www.gnu.org/licenses/.
Function Documentation
OTKDbdriver_tableName ()
Get the name of the database table used by all testcases. It's hardcoded here, but can be used by more classes this way.
Returns
Table name without prefix
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by OTKDbdriver_Last::__construct(), OTKDbdriver_First::__construct(), and OTKDbdriver_Alter::__construct().