/home/oscar/projects/owl-php/owltestkit/testsets/hdata/helper.php File Reference
Functions
OTKHdata_tableName ()
OTKHdata_getData (&$data, $rootNode=null)
Detailed Description
This file defines some helper functions for the HData testset
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Id:
helper.php,v 1.6 2011-10-16 11:11:45 oscar Exp
Copyright:
2011 -- Oscar van Eijk, Oveas Functionality Provider
License:
This file is part of OTK.
OTK is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
OTK is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with OTK. If not, see http://www.gnu.org/licenses/.
Function Documentation
OTKHdata_getData (&$ data, $ rootNode = null)
Get the data from the testtable. The primary key will be excluded from the resulting dataset and all integer values will be casted to actual integer.
Parameters
out $data Table contents or an error message when an error occured
in $rootNode Optional toplevel to select from
Returns
True on success, false on error, null when no data data was found
Author
Oscar van Eijk, Oveas Functionality Provider
References OTKHdata_tableName().
Referenced by OTKHdata_Nodehandling::performTest(), OTKHdata_Last::performTest(), and OTKHdata_First::performTest().
OTKHdata_tableName ()
Get the name of the database table used by all testcases. It's hardcoded here, but can be used by more classes this way.
Returns
Table name without prefix
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by OTKHdata_Nodehandling::__construct(), OTKHdata_Last::__construct(), OTKHdata_First::__construct(), OTKHdata_getData(), OTKHdata_Last::performTest(), and OTKHdata_First::performTest().