/home/oscar/projects/owl-php/owltestkit/testsets/hdata/helper.php File Reference
Functions
OTKHdata_tableName ()
OTKHdata_getData (&$data, $rootNode=null)
Detailed Description
This file defines some helper functions for the HData testset
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Id:
helper.php,v 1.3 2011-05-26 12:26:30 oscar Exp
Function Documentation
OTKHdata_getData (&$ data, $ rootNode = null)
Get the data from the testtable. The primary key will be excluded from the resulting dataset and all integer values will be casted to actual integer.
Parameters
out $data Table contents or an error message when an error occured
in $rootNode Optional toplevel to select from
Returns
True on success, false on error, null when no data data was found
Author
Oscar van Eijk, Oveas Functionality Provider
References OTKHdata_tableName().
Referenced by OTKHdata_Nodehandling::performTest(), OTKHdata_Last::performTest(), and OTKHdata_First::performTest().
OTKHdata_tableName ()
Get the name of the database table used by all testcases. It's hardcoded here, but can be used by more classes this way.
Returns
Table name without prefix
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by OTKHdata_Nodehandling::__construct(), OTKHdata_Last::__construct(), OTKHdata_First::__construct(), OTKHdata_getData(), OTKHdata_Last::performTest(), and OTKHdata_First::performTest().