/home/oscar/projects/owl-php/owltestkit/testsets/translations/helper.php File Reference
Functions
OTKTranslations_topLocation ()
OTKTranslations_libLocation ()
OTKTranslations_applicCode ()
Detailed Description
This file defines some helper functions for the Translations testset
Author
Oscar van Eijk, Oveas Functionality Provider
Version
Id:
helper.php,v 1.2 2011-10-16 11:11:43 oscar Exp
Copyright:
2011 -- Oscar van Eijk, Oveas Functionality Provider
License:
This file is part of OTK.
OTK is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
OTK is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with OTK. If not, see http://www.gnu.org/licenses/.
Function Documentation
OTKTranslations_applicCode ()
Return the application to check. This is in a seperate function so it easier to perform this test for another application (but still the change must be made manually in the code!)
Returns
Toplevel of te application
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by OTKTranslations_Messages::__construct(), and OTKTranslations_Labels::__construct().
OTKTranslations_libLocation ()
Return the loation for lib files. This is in a seperate function so it easier to perform this test for another application (but still the change must be made manually in the code!)
Returns
Library location
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by OTKTranslations_Messages::__construct(), and OTKTranslations_Labels::__construct().
OTKTranslations_topLocation ()
Return the toplevel to check. This is in a seperate function so it easier to perform this test for another application (but still the change must be made manually in the code!)
Returns
Toplevel of te application
Author
Oscar van Eijk, Oveas Functionality Provider
Referenced by OTKTranslations_Messages::__construct(), and OTKTranslations_Labels::__construct().